### ISSUE TITLE
Make strings translatable

### ISSUE THREAD

**Issue by M2ck** [rkkr/simple-keyboard#1]
Strings related with options that you have added are not translatable.
I would like translate them in my language (french).

**Comment by licaon-kter** [comment]
Maybe setup a Transifex or Crowdin site for translators to contribute to.
(it's free for FOSS  apps)

**Comment by BoFFire** [comment]
Weblate

**Comment by rkkr** [comment]
Project registered: https://crowdin.com/project/simple-keyboard
Hope they will approve free FOSS license.
