### ISSUE TITLE
How to reach the settings in android samsung s10

### ISSUE THREAD

**Issue by sartreed** [rkkr/simple-keyboard#106]
How to reach the settings in android samsung s10?

**Comment by licaon-kter** [comment]
Search for Input in Settings?

**Comment by sartreed** [comment]
I should search my whole phone for the words"input in settings" ? What? No

**Comment by rkkr** [comment]
If you have it already enabled you can just long-press ",". If not, the you can enable it in a launcher icon. And if you want to find it in system settings you can call Samsung and ask where they put it. Anyways, these are in the same place as all other keybards including the stock one.

**Comment by licaon-kter** [comment]
@sartreed search for "input" in Settings or call Samsung since it's their software that hides it...

**Comment by sartreed** [comment]
Not. Thanks. I called. He was expert. We talked 15 min. Thx for time wasting. Im out
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit WEB.DE Mail gesendet.Am 05.05.2019, 13:14, Raimondas Rimkus <notifications@github.com> schrieb:
If you have it already enabled you can just long-press ",". If not, the you can enable it in a launcher icon. And if you want to find it in system settings you can call Samsung and ask where they put it. Anyways, these are in the same place as all other keybards including the stock one.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rkkr/simple-keyboard/issues/106#issuecomment-489416415",
"url": "https://github.com/rkkr/simple-keyboard/issues/106#issuecomment-489416415",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
