### ISSUE TITLE
Logo Contribution

### ISSUE THREAD

**Issue by revilationer** [rkkr/simple-keyboard#107]
Hi!
I am a graphic designer 
If your app needs a logo i can help you
I will be waiting for your reply to start :)

**Comment by rkkr** [comment]
You can make a PR if you want to. Icon needs to be minimalistic and in two formats:
1. Web icon:
  a. https://github.com/rkkr/simple-keyboard/blob/master/icons/play_icon.png
  b. 512x512 no alpha, more details at https://developer.android.com/google-play/resources/icon-design-specifications .
2. App icon: https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/drawable-xxxhdpi/ic_launcher_keyboard.png
  a. Various DPIs
  b. With alpha
