### ISSUE TITLE
Request feature: trackpad for move cursor in text

### ISSUE THREAD

**Issue by webserveis** [rkkr/simple-keyboard#108]
When I'm in IOS I really like a functionality on the keyboard, which is to use as a trackpad, it goes very well to position the cursor in the text or to select accurately, in Android I have not found any keyboard that offers something similar.

Functionality:
Long press spacebar -> to activate the trackpad mode, The keys turn white
Swipe your finger around to move the cursor.

While you have hold and double tap with another finger on the keyboard, activate select mode, when swipe your finger the selection is expanded to the cursor position

See image
https://www.imore.com/sites/imore.com/files/styles/xlarge/public/field/image/2015/09/how-to-3d-touch-trackpad-screens.jpg?itok=Chuncz1i

**Comment by rkkr** [comment]
You can just move the cursor by swiping space left/right?

**Comment by ChristianKurz** [comment]
But swiping up/down for moving through
 lines would be nice to have, too :)
