### ISSUE TITLE
Back button in settings

### ISSUE THREAD

**Issue by EmmanuelMess** [rkkr/simple-keyboard#110]
Add back button (arrow back) to appbar in app settings.

**Comment by licaon-kter** [comment]
Interestingly enough, configuring it via Settings - Input - SimpleKbd... It has  plenty of titlebar arrows, the problem is that they always go back to the keyboard list and not to the provious settings level as the BACK navbar button does.

**Comment by rkkr** [comment]
Closing as the button is there. The way how it works can be a separate issue or an update to this issue.
