### ISSUE TITLE
Text on spacebar

### ISSUE THREAD

**Issue by JonnyTech** [rkkr/simple-keyboard#116]
How can I disable the language text that appears on the spacebar? I have a single languge selected in settings: Alphabet (qwerty). The text "QWERTY" is always on the spacebar button. If I select "use system language" then the text disappears. Can the text be disabled in settings somewhere?

**Comment by rkkr** [comment]
Your observation is correct. If a custom layout is selected, then its name
is shown. There isn't a setting to hide it.

Theoretically the name could be hidden if it's the only layout, but then it
will also be shown if there are other keybaords enabled.

**Comment by JonnyTech** [comment]
Can an option be added nonetheless?

**Comment by rkkr** [comment]
Fixed in 111cd6b7318c19ff743020b1711c8907ea9a3186 . The new logic is that text is shown only if multiple languages are enabled within the current keyboard. Other keyboards aren't counted (they are still counted for globe button).

**Comment by JonnyTech** [comment]
Thank you very much @rkkr, I shall wait for the fdroid build

**Comment by JonnyTech** [comment]
It works perfectly. Thanks again.
