### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by Poussinou** [rkkr/simple-keyboard#12]
Can you please tag your releases (see [here](https://help.github.com/articles/creating-releases/)), it would be helpful for the F-Droid release. Someone from F-Droid will probably do the work to include it in F-Droid after that.

(You could also attach the binaries to your releases (see [here](https://blog.github.com/2013-07-02-release-your-software/)).)

That's pretty easy and quick, and very helpful for us.

**Comment by rkkr** [comment]
Will do
