### ISSUE TITLE
Dictionary&Swipe

### ISSUE THREAD

**Issue by Archeix7** [rkkr/simple-keyboard#122]
Before you start, I want to note that the keyboard is simply gorgeous, the design and response are on top.
1) Swipe - I understand that you do not want to increase the size of the keyboard, but some things require sacrifice in order to be even better and swipe is one of these things, as it is now found in each keyboard and it is difficult to live without it, I decided to remove gboard and switch to your keyboard in the hope that you will add them sometime
2. Dictionary - it’s not necessary to download some dictionaries from the Internet, for example, on my device I can save the words I need in the settings and use the User Dictionary Manager program to make a backup copy, the main thing is that the keyboard can have access, and save them on the server - this is garbage and I agree with you here, because there will be less privacy
3) While writing this text, I noticed that it would be nice to add the auto-correction function, but this is not as important as the first 2 points.
I hope you add these features, good luck

**Comment by Archeix7** [comment]
So bad

**Comment by Wilker-a** [comment]
spacebar swipe for moving the cursor through the text is already present, tho i cannot remember if it is an opt-in or out function. check Advanced settings.

i see that mentioning the User Dictionary brings up the idea for the auto-complete, auto-correct (etc.) to be still present, and 'start from zero', which may save a lot of space on the initial app size, but that would depend if an implementation of this kind is available (unfortunately i can't actually program, so i only comment on issues)
