### ISSUE TITLE
add a proper telegraph for the spacebar swipe

### ISSUE THREAD

**Issue by Wilker-a** [rkkr/simple-keyboard#123]
when i mention the word Telegraph, i mean it as in a visual alert of whatever that is going to happen.

in this case, it's just the spacebar swipe, because i think that a simple and small alert can make it more obvious to the person writing that they can swipe the spacebar key to move the cursor, and how to do it.

a few examples for the idea shown bellow:
![a pair visual examples of the telegraph, both shown in a pair of screenshots of the keyboard, cropped so the focus of them is the row od the keyboard where lies the Spacebar key and in grayscale so the color of the Enter key does not become too distracting. the top image showing the Spacebar key with two dashes more to the sides of the key, with the color contrasting with the background color, while the bottom picture shows what looks like two pen strokes to opposite sides away from the center of the key, at similar positions as the dashes of the previous picture](https://user-images.githubusercontent.com/10854855/62681769-facf1e00-b9a9-11e9-9033-60f4ffc5bafe.jpg)

one thing to note is that i don't know if that should be persistent or if it should only appear while the user is holding the key. i also don't know if this is a good idea at all. any thoughts on this?

**Comment by rkkr** [comment]
Try GBoard. It doesn't show any visual indicator. If google thinks this is intuitive, then it should be good enough for us also.

These two icons won't help to understand what you can do. Probably a better way is to have a tutorial. There is already a Setup launcher, so listing what to do where would probably be a logical place. But indicators won't be added.

**Comment by Wilker-a** [comment]
understandable.

i only suggested that because it took me a very long time (a year of using the Gboard, and some time with SimpleKb although i had the option enabled) to realize that i could do that.

maybe a quick text explaining the option can make it clearer? (idk sorry)

**Comment by rkkr** [comment]
Yes, tutorial in Setup dialog is logical, but that is a separate feature.

**Comment by Wilker-a** [comment]
no, i meant it like this:

![a picture of the Advanced settings screen, highlighting the option for the Spacebar swipe function, in special, the text bellow saying "Hold the spacebar key and move to the sides to move the cursor."](https://user-images.githubusercontent.com/10854855/62685704-b5fbb500-b9b2-11e9-864c-dff622dca656.jpg)
