### ISSUE TITLE
[Feature Suggestion] Shortcut buttons to select text, copy and paste

### ISSUE THREAD

**Issue by Rahmsauce** [rkkr/simple-keyboard#127]
Hi, 

a few months ago, I switched from Fleksy to this keyboard. So far, I've been really enjoying it. I especially like its small size, quick responsiveness, high stability and minimalistic approach.

However, there is one feature I've been missing from Fleksy that I found very useful: There is an option which enables an additional row on top of the keyboard which contains button for selecting, cutting, copying and pasting text. 

I would really appreciate seeing a similar feature being integrated into Simple Keyboard as this would make typing so much more convenient.

Thank you!

**Comment by rkkr** [comment]
Duplicate #95

**Comment by Rahmsauce** [comment]
Sorry, I've missed that...
