### ISSUE TITLE
Fix key spacing

### ISSUE THREAD

**Issue by Wilker-a** [rkkr/simple-keyboard#128]
the spacings (margin, padding, etc) are kind of bad at the moment, specially the vertical spacing, which makes the keyboard take a lot of unnecesaary space on the screen that could be used for things such as better paddings for the numbers at the number rows and the symbols in the keys and control keys.

![screenshot taken with the keyboard height set to 65%, on a screen of 480px of width at 72DPI.. some of these problems persists on higher keyboard height settings however.](https://user-images.githubusercontent.com/10854855/63639494-3f81d700-c683-11e9-80a5-24c82346c2d9.png)

maybe adjusting how these spacings are made can open up space to implement functions like one hand keyboard and related.

what do you think? :3

**Comment by rkkr** [comment]
You probably have a very small keyboard height set. That is why icons look too big.

As for space between the keys- there is none. Try clicking between them. That spacing is just visual.

**Comment by Wilker-a** [comment]
i see. the icons is the smaller part, although the padding still is a bit of an issue.

before posting this issue, i double checked the spacing at 100%+. and in fact, the spacing even scales with the height of the keyboard. of course, it does not really affect the functionality — the criteria for Android to process touches does not seem to be based off the exact point of the touch, but actually the radius around it, which doesn't leave much room for error — but it still uses some unecessary space on the screen that could be used for things like adding padding space for buttons like the number row to be more visible, or simply leaving it for the system to use.

where it does affect the functionality, however, is at the sizes from 60% and below. the number row at these sizes are barely visible, just enough to know that they are there, but not enough for a comfortable usage of them. adjusting how the height of the margins of the keys are made gives the space for making the number row more comfortable to use at smaller sizes, so i think that would be an improvement.
