### ISSUE TITLE
Add emoji button

### ISSUE THREAD

**Issue by licaon-kter** [rkkr/simple-keyboard#13]
:+1:

**Comment by rkkr** [comment]
Emojis were removed intentionally and I don't plan to add them back. This is however made from AOSP project, so I might eventually distribute a vanilla AOSP keyboard which has them.

**Comment by wyjek** [comment]
That is a bummer, I need emojis and I would use AOSP keyboard, but I can't change its height.

**Comment by mvfsullivan** [comment]
Please please add this option. Maybe dont enable ot by default but have the option in Settings!!

**Comment by mimi89999** [comment]
Hello. I created https://github.com/mimi89999/aosp-keyboard-patches

**Comment by orogenic** [comment]
Seems like a lot of us want to use emojis with tgis keyboard. Can we implement it and place it behind either a runtime or buildtime feature flag so it's either toggled on/off in settings, or so we at least have a supported option to build with emojis enabled?

**Comment by licaon-kter** [comment]
Why not use OpenBoard then?

**Comment by orogenic** [comment]
> Why not use OpenBoard then?

Why not integrate OpenBoard and Simple Keyboard under a set of buildtime and runtime options?

**Comment by licaon-kter** [comment]
Why not answer my question with a question?

**Comment by orogenic** [comment]
lmao i haven't even looked at openboard in quite a few months, my only comment is i think it recently changed substantially? and now it's a 40MB download for some reason? do you know? i think i used to not use it just cus i couldn't change the default background color or something. looks like that's not the case now, so idk what i'm remembering

**Comment by licaon-kter** [comment]
It's ok, it has the features everyone asks here: dictionaries and emojis.

Decide already, slim app or features.

**Comment by orogenic** [comment]
> It's ok, it has the features everyone asks here: dictionaries and emojis.
that's a good reminder, thanks
> Decide already, slim app or features.
are you implying these exclude each other? anyway i'd like both please :)

**Comment by mimi89999** [comment]
> are you implying these exclude each other? anyway i'd like both please :)

@orogenic You can't get both. Just check the size of the Noto emoji font and of the dicts. They make most of the apk size and their size can't be reduced.

> Why not integrate OpenBoard and Simple Keyboard under a set of buildtime and runtime options?

I think that having them as one repo with 2 flavors will be most practical. They are both based on the same code. They inherited the same bugs. Fixing a bug in one fork that has been fized in the other one will be duplicate work. Some features migh also benefit both.

**Comment by orogenic** [comment]
> i didn't think emojis would be a huge source of bloat because isn't all that provisioned by the operating system's fonts already?

> @orogenic You can't get both. Just check the size of the Noto emoji font and of the dicts. They make most of the apk size and their size can't be reduced.

that's a bummer. thanks for pointing that out
> I think that having them as one repo with 2 flavors will be most practical. They are both based on the same code. They inherited the same bugs. Fixing a bug in one fork that has been fized in the other one will be duplicate work. Some features migh also benefit both.

i did check after, so, they're both based on https://android.googlesource.com/platform/packages/inputmethods/LatinIME , good to know. anyway, do the core developers of simple keyboard and openboard communicate regularly with one another, do you happen to know? (i'll try and figure out more myself)

by "2 flavors", it appears to me "flavor" is a gradle term, so each flavor has different build options? sorry for this analogy, is there some analog to C macro definitions, or what is the most straightforward way to include/exclude code at build time with gradle?

**Comment by RickyM7** [comment]
For those who want something more complete, opt for OpenBoard (https://github.com/dslul/openboard), it's basically Simple Keyboard with emojis and dictionary, and I imagine it will in the future have swipe-typing as well.
The v1.4.2 of this app that was recently released has no unnecessary permissions or anything like that.
It weighs 42MB on the F-Droid, that's basically what the Simple Keyboard would weigh if it had these functions.
It makes no sense to keep asking for it here when what you want already exists.

**Comment by orogenic** [comment]
> it's basically Simple Keyboard with emojis and dictionary

> what you want already exists.

> i do seriously want to see more integration and cooperation among software projects in general, taking advantage of sophisticated build and configuration systems to share more code and integrate designs where possible

> Why not integrate OpenBoard and Simple Keyboard under a set of buildtime and runtime options?

> I think that having them as one repo with 2 flavors will be most practical. They are both based on the same code. They inherited the same bugs. Fixing a bug in one fork that has been fized in the other one will be duplicate work. Some features migh also benefit both.

**Comment by RickyM7** [comment]
@orogenic I totally agree that having only one repo would be more practical and very beneficial for both projects for various reasons such as translations, bug fixes and mainly by decreasing the work of the devs that I imagine would occur by having all the contributors together. But since they are projects with different objectives, I think having separate repos is also plausible.

**Comment by rkkr** [comment]
> 
> 
> > Why not use OpenBoard then?
> 
> Openboard doesn't run on boot but simpleboard does.

File an issue for OpenBoard. They are welcome to copy daae07b1a0a545ad8a1b918166b7302a449a2185.

**Comment by herrbrixter** [comment]
I also want emojis that's why I stopped using Simple Keyboard. 

Please use Heliboard keyboard app. [https://github.com/Helium314/HeliBoard](https://github.com/Helium314/HeliBoard
)

Heliboard is the most active keyboard app. Openboard and Florisboard seem to be dead.
