### ISSUE TITLE
Small correction

### ISSUE THREAD

**Issue by HemanthJabalpuri** [rkkr/simple-keyboard#130]
@rkkr
is ending with `>>` is required in line 47 of https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/values-sw600dp/config.xml ?
when I am building your app in android I got this error https://github.com/SDRausty/buildAPKs.

**Comment by rkkr** [comment]
Looks like a typo. It's strange that Android Studio and Lint doesn't complain about it.
