### ISSUE TITLE
Language switch key opens different keyboard

### ISSUE THREAD

**Issue by wesinator** [rkkr/simple-keyboard#134]
Android 6.0.1 Samsung 

 - 2 simple keyboard languages enabled
 - AnySoft keyboard installed. 

Touching language switch button from primary language (English), the keyboard changes to AnySoft keyboard instead of switching to other simple keyboard language. 

**Expected:** switches to other language in Simple keyboard

**Comment by rkkr** [comment]
Working as expected. System manages the language+keyboard order. AnySoft keyboard should switch back to the other Simple Keyboard language.
