### ISSUE TITLE
Backspace swipe won't work until the hold function is active / Spacebar swipe is triggered with Backspace button

### ISSUE THREAD

**Issue by Wilker-a** [rkkr/simple-keyboard#135]
in some text fields and text areas, specially in Chromium-based browsers and some other apps, won't let me use the backspace swipe function (where you finetune and delete some text at once) until the hold function is active (where it gradually deletes until the button is released). instead, it just does the action that is supposed to happen only as the spacebar swipe function (where you just move the text cursor), which doesn't make sense...

**Comment by licaon-kter** [comment]
Seeing this too, but I happen to have changed devices and blamed this on the older one that I use now.

**Comment by rkkr** [comment]
Backspace swipe logic was changed in 3.9 to only select the text on swipe. I have the same behavior in my 4.4 tablet (not reproducible in 9+). What happens is that OS shows a cursor move pointer if you manually click a text field. And while that pointer is shown, a call to select a text range only moves that pointer to the start index. Everything works after that pointer is hidden after a timeout.

I've looked at the available APIs a bit, but didn't find a way to hide that pointer. I'll call it an old Android bug for now.

**Comment by licaon-kter** [comment]
So changed in 3.9 but 3.10 is ok, while 3.11/2 is not?

**Comment by rkkr** [comment]
https://github.com/rkkr/simple-keyboard/compare/60...61

It has the same `mInputLogic.mConnection.setSelection(start, end);` line. So versions 3.10 and 3.11 both select text on delete swipe the same way. The only difference is that selection position isn't set after move by each pixel, but it calculates if user swiped by at least a distance of one index.
