### ISSUE TITLE
Custom style - forget language on edit

### ISSUE THREAD

**Issue by licaon-kter** [rkkr/simple-keyboard#14]
Steps:
* Settings
* Appearance & Layouts
* Customised input style
* New
* **Romanian** / **Dvorak**
* Save -> Use
* Close settings & Android Settings
* go back to that syle, open it
* see that the language is now listed as **Afrikaans** instead

(FYI this was a Google keyboard issue too, fixed in 5.1.23 or even earlier)

**Comment by rkkr** [comment]
Google hasn't pushed this fix to AOSP. None the less this is a workaround: [commit](https://github.com/rkkr/simple-keyboard/commit/3c5aa462f832d24ad5adbb98b32ca29a5524db7e)
