### ISSUE TITLE
Return arrow in settings not working

### ISSUE THREAD

**Issue by jorgman1** [rkkr/simple-keyboard#140]
Version: 3.12
Android version: 7.1.2
Phone: Redmi 4X (MIUI 10.3.1.0)

In the keyboard setting, the return arrow at the top left corner is not working. I have to use the return key of my phone.

**Comment by rkkr** [comment]
Should be fixed in 3436a95bb08d536622b5507832386f2f89561edf

**Comment by licaon-kter** [comment]
Funny how this gets fixed in a version that old Android devices should never get since the [backspace function](https://github.com/rkkr/simple-keyboard/issues/135) got broken after 3.10 :(

**Comment by rkkr** [comment]
> 
> 
> Funny how this gets fixed in a version that old Android devices should never get since the [backspace function](https://github.com/rkkr/simple-keyboard/issues/135) got broken after 3.10 :(

But this has nothing to do with back button in the settings?

**Comment by jorgman1** [comment]
> 
> 
> Should be fixed in [3436a95](https://github.com/rkkr/simple-keyboard/commit/3436a95bb08d536622b5507832386f2f89561edf)

I finally had time to install the new version, and I can confirm that it is now working. Thanks!
