### ISSUE TITLE
Versioning can be more comprehensive

### ISSUE THREAD

**Issue by Wilker-a** [rkkr/simple-keyboard#144]
this is just a heads-up that some version increments may become confusing as to how people interpret what was implemented or fixed depending on how you do it, and there are ways to make it easier.

[this site](https://semver.org/) offers an interesting guide as to how to handle software versioning..

i hope it helps with something \^u\^

**Comment by Wilker-a** [comment]
for an example, the last version, 3.14, was just for a bug fix, so it could have been 3.13.1 instead, as the second number gets reserved for for implementations and changes that are compatible with previous versions :3

**Comment by licaon-kter** [comment]
That's why browsers are at version 70, right? C'mon...

**Comment by rkkr** [comment]
Semantic versioning describes API compatibility. It doesn't directly apply to applications as there are no backward incompatible changes. I usually bumped the major version when usability changes are made. Adding a back button doesn't bump a major version. Then we get into what is a big change :)

I think nobody really cares. Android Studio has a version 191.5900203 which makes no sense just as majority of other google apps.

**Comment by Wilker-a** [comment]
i see. thank you for explaining \^_\^
