### ISSUE TITLE
New Signature

### ISSUE THREAD

**Issue by rjm831** [rkkr/simple-keyboard#145]
App working excellently - thank you! - but latest update has a new signature key requiring a new install.  Is this legit?  This is on both Aurora and Yelp updates, btw.

**Comment by licaon-kter** [comment]
@rjm831 in Aurora you can toggle to ignore F-Droid apps, right?

**Comment by rjm831** [comment]
Yes you can.  Funny thing:  F-Droid wasn't offering me the latest update automatically, but when I went directly to Simple Keyboard's webpage on F-D the update was available.  Either F-D is acting buggy (not unknown) or my old Motorola Droid is doing its Nougat thing again.  Either way its not a problem.  Thanks to everyone for the help, and thanks again for offering such a great no-BS app.  You guys are great!
