### ISSUE TITLE
Dark and light theme based on time

### ISSUE THREAD

**Issue by pocketlili** [rkkr/simple-keyboard#148]
It would be really useful if the theme could switch based on daylight. 

That's pretty common on anything now but still not on the keyboards.

I'd say at 90% that this will not happen since require coding, but I think it's enough important to have a ticket about it.

**Comment by rkkr** [comment]
This wont be based on daylight (light sensor).
What is used in some apps and I did think about is to "follow the OS theme". If you enable Dark Theme, then some apps automatically switch to a dark theme. A keyboard could also do the same. Then you could put some other application on top to switch the phone theme based on time or the light sensor.

**Comment by pocketlili** [comment]
That would be a good way to do it but it require at last Android 10.
Night light is available since 7 if that's also an option.

Fixed time auto-switch would be already handy on every android version though.

**Comment by rkkr** [comment]
Dup #184
