### ISSUE TITLE
Add an option to manually show the keyboard

### ISSUE THREAD

**Issue by Crestwave** [rkkr/simple-keyboard#149]
I'm not sure if this is in the scope of a "simple" keyboard, but there are situations where you can type but the virtual keyboard isn't automatically shown, such as emulators/virtual machines in js. Hacker's Keyboard has an option to enable a permanent notification that opens the keyboard.

Also, delete swiping doesn't work in Termux since it was changed to select instead of delete immediately, but I guess this is an issue on their end?

**Comment by rkkr** [comment]
I won't add a permanent notification to show the keyboard.

For delete swipe Termux can't support the current delete mode as they can't support text selection by index in a terminal. Ideally Simple Keyboard would check if target application supports indexes and fallback to old delete swipe method if it doesn't.
