### ISSUE TITLE
System language not always set as keyboard language

### ISSUE THREAD

**Issue by pnehren** [rkkr/simple-keyboard#150]
I have the same device with Android 7 and Android 8 installed. On Android 7 i never had any problems. On Android 8 I experience that the keyboard language is not always set to the system language. For example when i set system language to german the keyboard is in QWERTZ, but after a reboot the keyboard is QWERTY again and i see in Keyboard settings that it is US-Layout though it should be aligned to the system language. After i force close the keyboard via ADB it is QWERTZ again. As well when i switch system language to US and then DE again, the keyboard is right set to QWERTZ. So it must be because of the reboot or initialziation on system start.

Anyone else experienced this?

**Comment by JM480** [comment]
Does this problem still exist with the latest version?

**Comment by pnehren** [comment]
i think this can be closed... i found a workaround years ago :D
