### ISSUE TITLE
Request to add a microphone button/shortcut.

### ISSUE THREAD

**Issue by CodeBoy66** [rkkr/simple-keyboard#152]
Would it be possible to add the option to display the microphone / voice typing button or shortcut in the keyboard. 

I believe this is pretty standard in other Android keyboards, and just brings up whatever is the default voice typing option set on the device (I don't believe this would compromise the simplicity of the keyboard or require the addition of network access, since the voice typing input is its own separate program, that is run by the device, this is just a shortcut to launch it).

**Comment by rkkr** [comment]
#133 dup
