### ISSUE TITLE
After updating to Android 10, there is an indent at the bottom of the screen.

### ISSUE THREAD

**Issue by TheFuzzStone** [rkkr/simple-keyboard#154]
Yesterday I received an update on the OnePlus 6T and I decided to install it.

My current phone specs:

* Android version: **10**
* OxygenOS version: **10.3.0**
* Build number: **ONEPLUS A6013_41_191214** 
* Model: **ONEPLUS A6013**

---

1) After the update, the keyboard does not reach the bottom of the screen, it is hampered by the indent.

2) The indent itself doesn't depend on a particular application and always appears (with the same size) when Simple Keyboard is used.

Screenshots (Telegram, Twitter, Reddit):

![Screenshot_20191222-104129](https://user-images.githubusercontent.com/16173361/71319573-0d00b300-2498-11ea-901e-47d430d37eb8.jpg)

![Screenshot_20191222-104142](https://user-images.githubusercontent.com/16173361/71319576-1427c100-2498-11ea-981d-a23876e5c7e8.jpg)

![Screenshot_20191222-104206](https://user-images.githubusercontent.com/16173361/71319577-17bb4800-2498-11ea-8b1e-b4b6ae4fb75a.jpg)

**Comment by rkkr** [comment]
![image](https://user-images.githubusercontent.com/3480123/71319726-a5079800-24aa-11ea-91d5-e895efa44f91.png)

Are you talking about this black space?

**Comment by TheFuzzStone** [comment]
@rkkr,

> Are you talking about this black space?

Yes.

**Comment by rkkr** [comment]
That is your navigation bar I assume. Do the 3 buttons (back, home, apps) still work? If they do then you have black buttons on a black background. Check if "Use matching navigation bar color" is enabled. Based on OnePlus history they probably don't support the new navbar theming properly.

**Comment by TheFuzzStone** [comment]
@rkkr 

> Do the 3 buttons (back, home, apps) still work?

Yeah, I tried that last night. And yes, when I put the buttons on the screen, then it seems that everything is fine, but I do not like when I see these buttons, because they occupy part of the screen + using gestures I personally feel more comfortable.

> Check if "Use matching navigation bar color" is enabled in Advanced settings.

It wasn't enabled. After it was turned on, everything works fine!
Problem solved.
[Closing this issue]

---

I'd like to take this occasion to thank you for the best keyboard app in the world!

**Comment by rkkr** [comment]
Ok, so you're on the new navigation gestures. At least in my Pixel, it shows the same black (or colored) bar, but with a single back button. Pixel also shows a persistent line at the bottom. GBoard shows the same exact navigation bar. Please check.

**Comment by TheFuzzStone** [comment]
@rkkr, 

Yes, it turns out that the black indent is now a different color (theme color), although the keyboard itself is still slightly higher than before the update to Android 10.

![photo_2019-12-22_13-00-47](https://user-images.githubusercontent.com/16173361/71320947-ded89e80-24aa-11ea-863b-8ea9a1e3c375.jpg)

**Comment by rkkr** [comment]
That was expected, the navigation bar is still there, just uses the same color.
Check how GBoard works. It should also show the navigation bar and use the same color.

**Comment by TheFuzzStone** [comment]
@rkkr 

> Check how GBoard works.

Yeah, the same:

![photo_2019-12-22_13-13-37](https://user-images.githubusercontent.com/16173361/71321061-1c89f700-24ac-11ea-8fdd-f48dc4d37153.jpg)

**Comment by rkkr** [comment]
And now you can send that as a bug to OnePlus. It should either show the keyboard minimization button (as in Pixel), or hide the navigation bar.
