### ISSUE TITLE
Question: Addition of new layout 

### ISSUE THREAD

**Issue by M86xKC** [rkkr/simple-keyboard#155]
Can layouts be pulled from Gboard or any other proprietary app and added to simple keyboard? I mean if you have the layout would it be possible to add it to simple keyboard? Or it needs to be in AOSP keyboard from the beginning (google version)?

**Comment by rkkr** [comment]
Nope, GBoard uses a different XML format that is incompatible with AOSP format. This also violates copyright as Google doesn't license these layouts to be used in other apps.

**Comment by Wilker-a** [comment]
how and why are kb layouts licensed in the first place? o.O

**Comment by rkkr** [comment]
The layout is still code and it is licensed under Apache 2 in case of AOSP: https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/xml/kbd_hindi.xml .
If you would copy the layout files from GBoard, you would not have the license to do that.

Theoretically speaking, even the layouts can be licensed. For example one recently made a hexagonal keyboard. If you made another one, that would be a copyright violation.

**Comment by M86xKC** [comment]
I think you misunderstood the question!
Or I didn't do a good job of explaining :)
My question was: can we add new languages to simple keyboard? That are not in AOSP source?

The layout/language is not under proprietary license.

**Comment by rkkr** [comment]
The initial question was 
> Gboard or any other proprietary app
to which the anwser is no (due to incompatible format) and no (due to licensing, unless that app is open source).
For the question
> can we add new languages to simple keyboard?
the answer is yes. You just need to make them yourself or use licensed sources.

**Comment by M86xKC** [comment]
Thanks for the clarification!
Is there documentation on how to make one? Or what ?

**Comment by rkkr** [comment]
One layout is linked 4 posts back. It inherits other XML files, but it's really no rocket science to find how it all works.
