### ISSUE TITLE
Custom style - can't enable style

### ISSUE THREAD

**Issue by licaon-kter** [rkkr/simple-keyboard#16]
Steps:
* Settings
* Appearance & Layouts
* Customised input style
* New
* **English** / **Dvorak**
* Save
* (also the entry is white text on white background)
* try to Use
* Style can't be selected as it does not appear on the language list

**Comment by rkkr** [comment]
You have to enable the custom layout in System Settings - Simple Keyboard - Language

![image](https://user-images.githubusercontent.com/3480123/40878147-5c9b77c8-6695-11e8-9857-c31cac482c16.png)

**Comment by licaon-kter** [comment]
Please read my post and reopen, I've said: **English / Dvorak**

**Comment by rkkr** [comment]
Ok, for English and all others with (*) ending it doesn't work. Will take a look but can't promise anything as it probably is AOSP bug.

**Comment by Switch123456789** [comment]
For 2 years now I want to use this (pretty good) keyboard desperately, but it is a deal-breaker that I can't use quwertz-layout for English. Who can I pay to fix this? I appreciate every bit of work going into this project but I am confused this issue doesn't have higher priority.

**Comment by rkkr** [comment]
This bug should be in all AOSP based keyboards. If you'll find one that doesn't have this bug, I can merge their fix (assuming they provide the source code).

It is unlikelly that you'll find one. As far as I've dug into this two years ago, it looked that the Android OS it self can't have a subvariation of the language like English (X) (Y). Gboard doesn't use the system layout list and that might be the reason.

**Comment by Switch123456789** [comment]
The preinstalled keyboard on my phone is AOSP based (LineageOS 16) and it is capable of using those custom layouts.
![Screenshot_20200128-130121_Einstellungen](https://user-images.githubusercontent.com/25269380/73262512-9fe6e880-41ce-11ea-80a3-f21db23cec40.png)

**Comment by rkkr** [comment]
After diffing between the Lineage source and debugging I did find where this comes from. It turns out this subsubtype thing isn't supported by the OS (which is why I didn't even try to fix this), but AOSP Keyboard added a hack on top which was accidentally removed along with other hacks.

Fix will come in a few days as there's a lot of files that need to be touched.

**Comment by Switch123456789** [comment]
Glad to hear that, thanks a lot for your efforts!

**Comment by rkkr** [comment]
Fix should be pushed to Play Store beta version 3.18. Please test as it also includes some cleanups in that area.

**Comment by Switch123456789** [comment]
It's working! I am writing this reply using a custom layout for English (USA). Now I can use my favorite keyboard. Thanks, I really appreciate it! btw: I couldn't find any issues yet, everything seems fine to me :)
