### ISSUE TITLE
sharing with a hardware bluetooth keyboard breaks keyboard shortcuts for switching the language layout.

### ISSUE THREAD

**Issue by Klapautsiy** [rkkr/simple-keyboard#160]
Sharing with a Bluetooth hardware keyboard disables keyboard shortcuts to switch the language layout.

initial data:
Android 9, Samsung Galaxy M20, a combination of switching the default language keyboard layout: Ctrl + Space, Shift + Space.

what needs to be pressed to switch the layout in Simple Keyboard?

thanks.

**Comment by rkkr** [comment]
Your physical and virtual keyboard layouts should be seperated (different in physical and virtual keyboards). At least in Pixel it shows "search + space" to switch the layouts (no idea which key is search), but that should only switch the physical keyboard layout. And the virtual keyboard only provides a set of languages that operating system can invoke. So it's the operting that should make the layout switch. 

I'll test in the emulator, but I guess that it won't work the way you expect it to work.

**Comment by rkkr** [comment]
I checked the emulator and it's as I expected. You can set physical keyboard layouts in System -> Languages and Input -> Physical Keyboard. The shortcut to switch layouts is "CTRL + Spacebar". And these layouts have no relation to the Virtual Keyboards. Changing layout in either doesn't change the other and they can have different sets of layouts at the same time.

**Comment by Klapautsiy** [comment]
"CTRL + Spacebar" toggles the keyboard layout if Simple Keyboard is turned off.
![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%200.jpg)
![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%202.jpg)

if Simple Keyboard is turned on, the physical keyboard layout can be switched exclusively from Simple Keyboard.
![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%203.jpg)
![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%204.jpg)

"CTRL + Spacebar" does not work.

To switch layouts, you need to call the on-screen keyboard, switch the language in the on-screen keyboard and continue in the hardware keyboard.

> That will also not be added as such shortcut would conflict with physical keyboard layout change shortcut. And as I said before, virtual keyboard layouts are managed by the operating system.

I wrote above that this is not so:
Samsung's on-screen keyboard does not conflict with anything and is switched by a hardware keyboard.
the on-screen keyboard Simple Keyboard blocks the combination of "CTRL + Spacebar".
