### ISSUE TITLE
sharing with a hardware bluetooth keyboard breaks keyboard shortcuts for switching the language layout.

### ISSUE THREAD

**Issue by Klapautsiy** [rkkr/simple-keyboard#161]
I apologize for my persistence and desire to use Simple Keyboard and hardware keyboard at the same time.
I understand that the desire to use a hardware keyboard is abnormal, and even more so, it is abnormal to have more than one language - most need only one.
I do not ask to somehow change the Simple Keyboard code.
I ask for a free consultation:
- How can I switch the language layout of the hardware keyboard if Simple Keyboard is installed on the smartphone?
thanks.

this post is a continuation of this strange problem https://github.com/rkkr/simple-keyboard/issues/160

**Comment by rkkr** [comment]
Don't open new issues when they are closed. You can reply to closed issues if you have something to add.

Physical keyboard layout is changed with "ctrl + space". This is tested in emulator and on Pixel 3a. And it doesn't matter if Simple Keyboard is installed or opened. Virtual keyboard layout is not changed and can be different from physical keyboard layouts.

If it doesn't work on Samsung, you can call them. Then buy a Pixel.

**Comment by Klapautsiy** [comment]
> If it doesn't work on Samsung, you can call them.

Samsung's on-screen keyboard does not conflict with hardware keyboards.
I can’t have claims to Samsung.

> Then buy a Pixel.

I can buy an emulator and connect a keyboard to it. : D

> You can also test with GBoard, it should (not) work the same way.

GBoard doesn't work differently - you can install no more than one layout there.
if you have one layout, what problems can you have with switching layouts?
right - no problems with switching layouts.

**Comment by rkkr** [comment]
> Samsung's on-screen keyboard does not conflict with hardware keyboards. I can’t have claims to Samsung.

If layout switching only works with their keyboard. It' still their bug.

> GBoard doesn't work differently - you can install no more than one layout there.

GBoard does support multiple layouts.

**Comment by Klapautsiy** [comment]
See how this “doesn't work” in GBoard.
Shift + Space of the hardware keyboard calls up the GBoard on-screen keyboard and switches the layout of the GBoard on-screen keyboard.
it seems that everything works, but due to the fact that it is possible to install only one layout, it does not matter which layout will be visually displayed - printing will occur in the layout that is selected - see the figure below. only one layout.
![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%206.jpg)

what follows from this?
in GBoard it is possible to switch Shift + Space layouts with a hardware keyboard.
Simple Keyboard allows you to customize more than one keyboard layout.
![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%204.jpg)

If you combine these two annoying bugs, then I do not have to buy a Pixel.

**Comment by Klapautsiy** [comment]
> If layout switching only works with their keyboard, it' still their bug.
their problem is that Simple Keyboard does not work out Ctrl + Shift?

**Comment by rkkr** [comment]
GBoard does support multiple layouts. So do test the same with GBoard.
![image](https://user-images.githubusercontent.com/3480123/72685387-4efe3280-3af2-11ea-823b-116a023a21dc.png)

And layout switching of a physical keyboard is done with "ctrl + space", not "shift + space". And that will not change the layout of the virtual keyboard.

You're pasting so many unrelated stuff I don't even get what your problem is anymore.

**Comment by rkkr** [comment]
Now that I'm thinking all this can be put into "if you can't make it work on GBoard, then it's Samsung's bug". And that doesn't depend on how Samsung made their own keyboard and how it differs from GBoard. If a functionality can't work with an Android compliant keyboard (GBoard), then it's a bug.

**Comment by Klapautsiy** [comment]
> GBoard does support multiple layouts. So do test the same with GBoard.

on-screen keyboard GBoard.
hardware keyboard.
you type in the hardware keyboard in Ukrainian, you come across a technical term in English: how to type a term in English? - you need to press Ctrl + Space or Shift + Space
Ctrl + Space does not work at all.
Shift + Space brings up the GBoard on-screen keyboard, and visually you can observe the layout switching process.
but! input is possible only in Latin or otherwise, depending on the setting.
![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%206.jpg)

then there is nothing left to switch the layout from the on-screen keyboard with a finger in the screen or in another way, since the key combination switching the layout does not work.
I gave the Samsung on-screen keyboard as an example of a working solution that does not cause problems.

**Comment by Klapautsiy** [comment]
> Now that I'm thinking all this can be put into "if you can't make it work on GBoard, then it's Samsung's bug".

well.
Have you tried typing multilingual text on your hardware keyboard on your phone?
tell me the keyboard shortcut of the hardware keyboard with which you switch the layout.

**Comment by rkkr** [comment]
As I wrote before, yes I have tested switching between multiple hardware keyboard layouts in an emulator and a Pixel with an USB keyboard attached. It switch between physical keyboard layouts and I can type using two languages. Ctrl + space switches the layout.

And it doesn't matter what virtual keyboard is used and what layouts it has. I can have russian layout in gboard and type lithuanian in usb keyboard.

**Comment by Klapautsiy** [comment]
that, yes - we have these keyboards.
our aunt works at the keyboard factory.
OK. thanks.
accept my apologies for killing several hours of your time without reaching a result.

**Comment by Klapautsiy** [comment]
decided to see how it is implemented on the PC - all of a sudden, it turned out that:
- It is impossible to install different layouts on ten connected keyboards.
- switching layout on the hardware keyboard switches the layout on the on-screen keyboard.
- it is possible to customize keyboard shortcuts to switch layouts.

and, I found what works https://anysoftkeyboard.github.io/

![](https://raw.githubusercontent.com/Klapautsiy/titanium-bicycle-for-button/gh-pages/pictures/simple-keyboard_shortcuts/simple%20keyboard%20fix%207.jpg)

probably - I will not be able to install different layouts on three keyboards connected to the smartphone, as is possible on the Pixel.
but I can’t do this on PC either.
