### ISSUE TITLE
Add "Switch Keyboard" Option when long-pressing [ / ]

### ISSUE THREAD

**Issue by Glitchy-Tozier** [rkkr/simple-keyboard#162]
Currently, there is no easy way of switching keyboards while using Simple-Keyboard. (At least to my knowledge)

The user has to navigate all the way to the keyboard settings.

I'd like to suggest adding this as a third option on the dialogue that pops up when the user presses and holds the forward-slash-key.

**Comment by rkkr** [comment]
There as a long-press on "space" and Globe key beside it. GBoard uses the same switching methods.
