### ISSUE TITLE
Multiples of the " ¢ " -Symbol

### ISSUE THREAD

**Issue by Glitchy-Tozier** [rkkr/simple-keyboard#163]
On the special symbols keyboard, the one you get to by pressing the following keys [?123]  ->  [=\<] there is a duplicate of the "¢" symbol.

In the left side of the second row, those keys can be found: [ £ ]   [ ¥ ]   [ $ ]   [ ¢ ]. Only one of them has a pop-up, the $-key. If you press and hold this key for some reason, you will be able to select the ¢-symbol.

To my understanding, this is redundant as the ¢-key is right next to the §-key anyway.

**Comment by rkkr** [comment]
Do you have a UK layout? By default $ key is in the primary special chars window (where you probably have £ or Eur). Now when # and % keys are beside it, then it makes sense to have all these currencies there. And as keys have same long-press keys independently on where they are shown, this can't and won't be changed.
