### ISSUE TITLE
Frequently stops playing keytap sounds

### ISSUE THREAD

**Issue by brainard52** [rkkr/simple-keyboard#164]
I honestly don't know how to reproduce this other than "keep using it". I'm using a Pixel 4 XL on the latest public release of Android. I'll be in the middle of typing something, and the keyboard sounds just spontaneously stop.

**Comment by rkkr** [comment]
I'm on Pixel 3a XL and used a Nexus 5X before. Never happened. Vibration is disabled.

**Comment by rkkr** [comment]
Maybe you're enabling "Do Not Disturb" or have setup some rules in Digital Wellbeing?

**Comment by rkkr** [comment]
Closing as info not provided.
