### ISSUE TITLE
Request to add AMOLED Black Theme

### ISSUE THREAD

**Issue by desmonk** [rkkr/simple-keyboard#166]
This is my daily driver to type in peace. I just wish to have a pure black with/without border style keyboard that goes easy on eyes of night owls.

A really nice app!

**Comment by rkkr** [comment]
Just set #000000 background color in advanced settings

**Comment by desmonk** [comment]
I am really sorry for being this naive and I really thank you for helping me out. Is it possible to have minimal white borders on pure black theme as once the color is set to black, all keys are merged together (as they are in default theme) and becomes difficult to differentiate.

**Comment by rkkr** [comment]
What do you mean by "merged together"? There are bordered and borderless themes, and background color doesn't interfere with the border. Unless you're putting black background on a white theme, or the other way.

**Comment by desmonk** [comment]
All Black here with Keys Merged into each other:

![Black Design - Keys Merged - No Borders](https://user-images.githubusercontent.com/55331939/73608589-bfaa5200-45bc-11ea-993a-5c5d9c2c561d.jpg)

There is no border or space left here. And if we apply to black color to Material Black  with Borders themes then it becomes like this:

![Black Border Design](https://user-images.githubusercontent.com/55331939/73608626-3a736d00-45bd-11ea-8f9a-525638693a8a.jpg)

**Comment by rkkr** [comment]
The first picture doesn't differ from the original black theme. Borderless themes don't have borders. And there are no spaces between keys.

**Comment by desmonk** [comment]
I meant something like this with space, where we can retain minimal borders when it's pure black. As in the second picture with borders it only blacks out the background of keys.

![73608589-bfaa5200-45bc-11ea-993a-5c5d9c2c561d](https://user-images.githubusercontent.com/55331939/73608987-0a2dcd80-45c1-11ea-88e2-38e8a72a347c.jpg)
