### ISSUE TITLE
How do I change the layout on v3.18, now that the globe icon is gone?

### ISSUE THREAD

**Issue by pitsi** [rkkr/simple-keyboard#167]
Dear developer.

I got the upgrade to v3.18 yesterday and now I can not change the layout, because the globe icon that used to be on the left side of the spacebar is gone, as seen below.

![Screenshot_20200206-060207](https://user-images.githubusercontent.com/5880037/73907649-d6e48a80-48af-11ea-95c7-576c3d172c68.png)

So now I am stuck with the greek keyboard layout and the only way I see to change it is to go to long press comma > press the gear icon >  go to languages > disable "use system languages" and enable english. And the other way round for switching back to greek.
Disabling "use system languages" and selecting 2 or more languages, us english and greek for instance, makes the globe icon appear again and work like it used to, so I can use this for now.

Nokia 5, android 9, simple keyboard 3.18 and the option "hide language switch key" set to disabled.

**Comment by rkkr** [comment]
I assume you have multiple languages enabled in the phone settings?

**Comment by pitsi** [comment]
I only have greek in there (system > languages and input > languages). And I think I have not changed it since I got the phone. Shall I change it now?

**Comment by licaon-kter** [comment]
@pitsi the globe appears when you select more languages in the keyboard settings, else it doesn't need to appear for only one language.

**Comment by rkkr** [comment]
Well if you have only Greek enabled in system langauges and you set the keyboard to use only system languages how do you expect an english layout to be shown? :)

Jokes aside the globe icon isn't shown when two system languages are enabled, but I can't tell if it worked before. What might have happened is that you had English layout enabled in the keyboard settings and that disapeared. I did touch the attributes of Enflish keyboard.

**Comment by pitsi** [comment]
I see. However, it did appear with one language on system settings and it let me switch from greek to **querty** layout and vice versa. So maybe, I have lost the way to switch between qwerty and greek layout and not between english and greek...

**Comment by rkkr** [comment]
If you had an Alphabet QWERTY custom layout enabled, then Aplhabet placeholder is removed in 3.18 as it was identical US.

**Comment by pitsi** [comment]
I see now. Thank you for the info. I will use what I described above then.
