### ISSUE TITLE
Custom accent color

### ISSUE THREAD

**Issue by lokesh-krishna** [rkkr/simple-keyboard#169]
Could you please consider adding an option to also set the accent color (for the shift key)?  
Really appreciate you giving the community a solid and well-maintained keyboard.

**Comment by rkkr** [comment]
As all the resources are statically loaded to allow hardware accelerated rendering, there isn't an easy way to put an accent on top. And that way is incompatible with some Samsung phones. So unless someone comes up with a proper way to make this work, I won't consider this.

I also wouldn't want to add too many settings. People also ask for customizable button, font, popup and border colors, which I think is just too much.

**Comment by lokesh-krishna** [comment]
Just to clarify, I am talking about the color of the Shift key when it is touched. It is presently teal and I wanted to know if it could be changed.  
Could you consider changing the teal to the Pixel blue accent that is used in Gboard by default? I admit that that is a personal aesthetic choice so just wanted to put it out there for your consideration.

**Comment by rkkr** [comment]
That color is in the static file: https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/drawable-xxxhdpi/sym_keyboard_shift_locked_lxx_dark.png so it can't be made customizable easily.

I also don't see the blue shift key in GBoard, but it has many themes so I'm probably not looking at the same one. What I see is a white border/filled shift symbol. That could be replicated.

**Comment by lokesh-krishna** [comment]
Looking forward to it then :)
