### ISSUE TITLE
Add close button

### ISSUE THREAD

**Issue by sTolyaR** [rkkr/simple-keyboard#170]
Some applications work in Kiosk mode and it would be great to have optional button to hide keyboard. In bottom right corner for example.

**Comment by lkjh654** [comment]
I found this project when looking for a solution for the very same problem - a need for a close button in Kiosk mode. Any plans on implementing this feature? Can it be easily added on top of the existing codebase @rkkr ?

**Comment by rkkr** [comment]
Adding it is not hard. You can find in the history when arrow buttons were added and do the close instead. You'll just need to find an API for close, but I saw it some examples.

But I don't plan to add it as it will only be used by few people.

**Comment by magnus-ISU** [comment]
I just ran into a situation where not having this feature made an app (To-Don't) unusable (I had to switch keyboards).

My suggestion for it would be to make long-pressing the return button close the keyboard. It wouldn’t clutter the current UI and would solve these scenarios.

**Comment by JM480** [comment]
This issue should be closed if there are no plans to add this feature.
