### ISSUE TITLE
Russian layout change character from _ to -

### ISSUE THREAD

**Issue by bchtrue** [rkkr/simple-keyboard#171]
At the Russian layout there is "`_`" (hold key) char, but it must be "-" instead, because "`_`" not used too much instead of "-" char.

I guess it is mistake, because English layout print "-" at this position".

**Comment by rkkr** [comment]
"-" is on letter "Л"?

**Comment by bchtrue** [comment]
Thanks, found it. It's little confused, maybe because alternative symbols is too small
