### ISSUE TITLE
Add Functionality

### ISSUE THREAD

**Issue by Jigneshjagad** [rkkr/simple-keyboard#175]
@rkkr Can I implement translation, template, and put emoji keyboard functionality with the base of this keyboard?

**Comment by licaon-kter** [comment]
#13 ?

**Comment by rkkr** [comment]
https://github.com/rkkr/simple-keyboard/blob/master/LICENSE allows you to do exactly that. But I would recommend to start from LatinIME as adding this functionality back will not be trivial.

**Comment by Jigneshjagad** [comment]
@rkkr thank you

I am not experienced but i want to ask some basic about keyboard development can you give me your social id or email i want to ask you something ASOP.
Or i ask here you will reply?

**Comment by rkkr** [comment]
I don't have time nor will for coaching. You need to have coding skills to be able to develop it. And if you do have the skills, then you know how to debug and find out how things work. This project ain't complicated. You can also start from https://github.com/rkkr/tiny-keyboard which is totally trivial.

**Comment by Jigneshjagad** [comment]
@rkkr Thanks this motivates me a lot and you are a very good person. 🙏
