### ISSUE TITLE
Adding buttons to the top of the keyboard

### ISSUE THREAD

**Issue by Eichhof** [rkkr/simple-keyboard#177]
Hello everybody

First, congratulation to this amazing keyboard, I love it.

I would like to add two (small) buttons at the very top of the keyboard, one button on the left side and one on the rights side and catch button callbacks.

How can I do this?

**Comment by rkkr** [comment]
d9d88a237f68d9a15c691f9997933407e3b823df and 013840269892d98ffe49b0d1f29b09003e2ed7d5
