### ISSUE TITLE
[Feature] Select text similar to the backspace swipe

### ISSUE THREAD

**Issue by SebiderSushi** [rkkr/simple-keyboard#178]
It would be a very useful tool, if text selection were possible by the same scheme of the backspace swipe.

Since this sollides with existing functions, it might be best to add an option if implementing this. Using the option one could alternate between
A) backspace swipe for deletion (current behavior)
B) Text selection only by swiping either from the shift or enter key, possibility of accidentaly activating the wrong swipe
C) Text selection only by swiping either from the shift of backspace key, no deletions

Another intutive way to select text could be to make the spacebar swipe select text & move the text selection boundary while the shift key is held down. This would not interfere with anything but require two handed use for the feature.

**Comment by rkkr** [comment]
Space swipe now selects text if some text is already selected. You can long-press a word and right side selection will be moved.

**Comment by SebiderSushi** [comment]
Thanks for the hint.
