### ISSUE TITLE
Retrieving keyboard height

### ISSUE THREAD

**Issue by Eichhof** [rkkr/simple-keyboard#179]
Hi there

Is there a possibility to get the current keyboard height and width in pixels? Depending on the screen size and the settings the height differs.

**Comment by rkkr** [comment]
https://github.com/rkkr/simple-keyboard/blob/61f1fe32c8eddcedeb5ef058af62e8bc201850c1/app/src/main/java/rkr/simplekeyboard/inputmethod/latin/utils/ResourceUtils.java#L183

**Comment by Eichhof** [comment]
Thank you very much for the hint. Which method is called whenever the keyboard opens (that means pops up)? I would like to call getKeyboardHeight() in that method to store the keyboard height every time the keyboard pops up.

**Comment by Eichhof** [comment]
I found it. It is in the class KeyboardSwitcher.java.
