### ISSUE TITLE
Double tap space bar

### ISSUE THREAD

**Issue by Eichhof** [rkkr/simple-keyboard#181]
Hi there

I like the keyboard very much and almost everything is there. The only thing I miss is that when I double-tap the space bar, there is no dot (period) inserted followed by a space.

How can the keyboard be adapted to reflect this feature (does not need to be added to the settings but can be hardcoded)? I assume it should be very easy to mimic this behavior but I did not find a solution. Perhaps one solution could be to listen to space taps and then replace the event by "perios + space" if the time difference between two consecutive spacetab taps is below a threshold. But I don't know which method to adapt.

**Comment by rkkr** [comment]
This is available in AOSP LatinIME source

**Comment by Eichhof** [comment]
Thank you a lot. Do you know where it is located there? The AOSP LatinIME source is somewhat huge.
