### ISSUE TITLE
Add Japanese language from OpenWnn

### ISSUE THREAD

**Issue by voltrare** [rkkr/simple-keyboard#182]
Can we add Japanese Input (of Hiragana and Katakana ) option with this

https://f-droid.org/en/packages/jp.co.omronsoft.openwnn/
https://android.googlesource.com/platform/packages/inputmethods/OpenWnn

it is easier rather than using two separate apps

Sorry for any inconvenience

**Comment by rkkr** [comment]
That is a separate application, not LatinIME. Chances of same layouts working are slim.
