### ISSUE TITLE
Keyboard light and dark theme to follow the OS theme

### ISSUE THREAD

**Issue by wsid3** [rkkr/simple-keyboard#184]
Since Android 10, more and more apps start to support this feature, and I think it would be awesome if Simple Keyboard also had a 'System default' option that inherits the system's daynight theme.

**Comment by rkkr** [comment]
That is not as trivial as it sounds. Firstly there are two dark/light themes. Even if the first issue can be worked around by having two auto themes (that already sound complicated for a user). The custom background feature doesn't fit into this in any usable way.

An alternative could be "System Default" theme which strictly follows the theme parameters. The background would be strictly theme background (not the current default bluish) and keys would have border just like theme does (+ same colors).

I haven't yet figured out how this should work.

**Comment by rkkr** [comment]
You can give this a try: https://github.com/rkkr/simple-keyboard/releases/tag/72
