### ISSUE TITLE
Changing keyboard color while keyboard is open

### ISSUE THREAD

**Issue by Eichhof** [rkkr/simple-keyboard#187]
Hello

Is it possible to change the color of the keyboard (e.g. switch to dark theme) while the keyboard is open? If certain keys are pressed I would like to dynamically adapt the color or the theme of the keyboard in LatinIME class. I know how to listen to the key events I want but I don't know how to dynamically change the keyboard theme or color while the keyboard is open.

**Comment by rkkr** [comment]
Not possible. And if you'll hack it to force set, you'll have rendering issues. The keys are drawn on top of the background, so you'll have to redraw them.
