### ISSUE TITLE
app installing completed but no sees in my in android & no find out it

### ISSUE THREAD

**Issue by shihann14** [rkkr/simple-keyboard#19]
Project Information

>Repository:https://github.com/rkkr/simple-keyboard
Project Name:simple-keyboard
  Publisher:https://github.com/rkkr

Expected behavior: 

A user chooses this app then its download & install on his android device. then the user easy to use  & it is enjoying the app.

Actual behavior:

When the user downloads completed then he is want to be installed on his Android device. then the user sees that app open option is hidden. then the user he has no find out app it on his android device.

How to reproduce:

* Download the app.
* Installing completed.
* And note the bug.

>Browser/App version:2.7
Operating system: Android: 7.0

Recording of the bug: https://youtu.be/gXAWRmk9354

**Comment by licaon-kter** [comment]
Android Settings-> Language & Input -> Keyboards -> Activate Simple Keyboard -> Back -> Select default keyboard...
