### ISSUE TITLE
Suggestion : non-querty PC layouts

### ISSUE THREAD

**Issue by gabmiral** [rkkr/simple-keyboard#190]
As a French user who prefer PC-style layouts for keyboards, I would like to see the PC layout ported to other layouts (like AZERTY)

**Comment by rkkr** [comment]
Simple Keyboard settings -> Appearance & Layouts -> Custom input styles -> Add ?

**Comment by gabmiral** [comment]
No, I already tried and it creates a QWERTY keyboard

**Comment by rkkr** [comment]
I've just added an English (US) AZERTY layout and it appeared in the Languages list. And AZERTY layout was shown when English was selected.

**Comment by licaon-kter** [comment]
@gabmiral you need to ADD it and then activate it

**Comment by gabmiral** [comment]
I'm not talking about classic AZERTY keyboards, I'm talking about AZERTY in PC layout.

**Comment by rkkr** [comment]
Ok, so that's what you mean. PC is just a layout like AZERTY and QWERY (in the context of this app). So having a layout of a layout is not possible. Unless you would make a PC version of all the current layouts. But that is not gonna happen.

**Comment by licaon-kter** [comment]
Oh, right, you want a layout that does not exist: AZERTY PC because I guess AZERTY+Show Numbers Row ain't good enough?

**Comment by gabmiral** [comment]
> Oh, right, you want a layout that does not exist: AZERTY PC because I guess AZERTY+Show Numbers Row ain't good enough?

that's the whole point of a **suggestion**. And why would QWERTY PC exist if we can just add the number row to querty? because the PC layout has the layout of a physical keboard, with all in one page, instead of mobile virtual keyboards
