### ISSUE TITLE
PointerTracker non-visible issues

### ISSUE THREAD

**Issue by wittmane** [rkkr/simple-keyboard#195]
I've been digging through the code and I found a few potential issues in how key presses are handled. I don't think these actually cause any visible bugs currently, but it seems like it could cause issues in the future or just make slightly confusing workarounds necessary. I think these stem from the AOSP keyboard, and I'm not sure how identical this app is trying to be to it, so I don't want to just waste my time fixing it to get my change rejected, but I'd be happy to work on fixing it if these seem like reasonable changes.

1. `callListenerOnPressAndCheckKeyboardLayoutChange` and `callListenerOnRelease` in `PointerTracker` don't send the alt key code, but `callListenerOnCodeInput` does. This seems like strange behavior. This means that when typing and pressing a key with an alt code, `onPressKey` for the main code point gets called, `onCodeInput` for the alt code point gets called, and `onReleaseKey` for the main code point gets called.

2. When long pressing a key to select a key in the more keys keyboard `onReleaseKey` is never called. I expected it to get called once the more keys keyboard was shown. Since the more keys keyboard doens't trigger `onPressKey` or `onReleaseKey`, I could see some argument for `onReleaseKey` for the base key to not get called immediately, but I'd still expect it to be called after `onCodeInput` is called for the more keys keyboard key. It doesn't seem right that `onPressKey` could ever get called without the corresponding `onReleaseKey` being called later.

3. `onCodeInput` is called with the wrong code point for keys that change the keyboard layout. `onDownEventInternal` in `PointerTracker` checks `callListenerOnPressAndCheckKeyboardLayoutChange` and updates the tracked key (in `onDownKey`). I don't understand why that was done, but it obviously was an intentional thing (maybe it isn't necessary anymore or it only was for the AOSP keyboard because I don't see any benefit from it now). For example if `CODE_SWITCH_ALPHA_SYMBOL` was split into `CODE_SWITCH_TO_ALPHA` and `CODE_SWITCH_TO_SYMBOL`, when a key that would send `CODE_SWITCH_TO_SYMBOL` is pressed, `onPressKey` would be called for it, but `onCodeInput` and `onReleaseKey` would be called for `CODE_SWITCH_TO_ALPHA`. This doesn't seem like the appropriate behavior.

**Comment by rkkr** [comment]
All this is AOSP code. If you want changes, make a PR.

**Comment by wittmane** [comment]
Just for clarification, are you saying I should make a PR to this repository or the AOSP repository because you'll eventually pull in changes from there? If you're just talking about this repository, what's the significance of mentioning that this is AOSP code? Isn't this whole repository mostly a stripped down version of the AOSP keyboard?

**Comment by rkkr** [comment]
This IS a fork of AOSP with all the bugs and weird behavior that you noted. And as this is existing code with existing logic I don't intend to refactor this if in the end result this does work. What I wanted to say is that if you want this to be changed, you'll have to do that your self.
