### ISSUE TITLE
Constrain layout to only QWERTZ with umlauts

### ISSUE THREAD

**Issue by Eichhof** [rkkr/simple-keyboard#197]
Hello

I would like to constrain the layout of the keyboard to one layout only, namely QWERTZ with umlauts. I have already removed the settings to change the keyboard layout and language. But how can I set the QWERTZ layout with umlauts hardcoded?

Thank you very much for your help.

**Comment by rkkr** [comment]
https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/xml/method.xml
