### ISSUE TITLE
Removing all custom input styles

### ISSUE THREAD

**Issue by Eichhof** [rkkr/simple-keyboard#198]
Hello

I have changed the methods.xml (https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/xml/method.xml), so that only the following entry remains:

```
    <subtype android:icon="@drawable/ic_ime_switcher_dark"
            android:label="@string/subtype_generic"
            android:subtypeId="0x7acfd0aa"
            android:imeSubtypeLocale="de_CH"
            android:imeSubtypeMode="keyboard"
            android:imeSubtypeExtraValue="KeyboardLayoutSet=swiss"
            android:isAsciiCapable="true"
    />
```

I have removed all other entries. When the system language is German (Switzerland), then only the QWERTZ layout with umlauts is available, that's exactly what I want. But when I switch the system language to German (Germany) or Englisch (United States) then the layout is the QWERTY.

I would like to have the QWERTZ layout with umlauts (corresponding to German (Switzerland)) always independent of the system language setting.

I have found that the problem is that in the custom input styles there is German (QWERTY) and French (QWERTZ). How can I remove them in the code so that when the keyboard is installed no custom input styles exists?

Thank you so much for your help.

**Comment by rkkr** [comment]
Search "predefined custom input styles"

**Comment by Eichhof** [comment]
Thank you. But in the app code and this repo here I did not find anything related to predefined custom input styles. Could you please provide me a quick help where I can remove them for the language German (Swiss)? Thank you very much.

**Comment by Eichhof** [comment]
Found it. It is in values/predefined-subtypes.xml.
