### ISSUE TITLE
Change the Key output

### ISSUE THREAD

**Issue by diogo10** [rkkr/simple-keyboard#200]
Hi guys, thanks for this repository. It's great!
I have a questions regarding the outputText in Key class. I am not managing the output somehow.

  ```
  public final String getOutputText() {
       final OptionalAttributes attrs = mOptionalAttributes;
        return (attrs != null) ? attrs.mOutputText : null;
    }
```

Basically, the mOptionalAttributes is always null. Not sure how I can change it to output what I want. Did somebody manage to change the output for a specific Key?

**Comment by rkkr** [comment]
`mOptionalAttributes` is not always null, but `mOutputText` is always null so far. This is only used when key outputs multiple characters like `.com` (all of which I probably removed from the source code, search for `keyspec_popular_domain` in original LatinIME source code). To output multiple chars you just add multiple chars to the keySpec like `latin:keySpec="abcdefg"`.

The line which nulls the `mOutputText` when there is a single char is `return (StringUtils.codePointCount(label) == 1) ? null : label;`. This is most probably done for optimization.
