### ISSUE TITLE
[Request] android 4.x keyboard theme

### ISSUE THREAD

**Issue by Domiuns** [rkkr/simple-keyboard#202]
hi i love your app could you integrate this theme into your app? I can only write with this theme ..... it will be because I have used android 4 for more than 7 years 
![IMG_20200725_230522](https://user-images.githubusercontent.com/53193434/88466321-6405b500-cecb-11ea-97bb-fccddc97efb7.JPG)
Yes this photo is make on real device android 4
I hope my request will be granted, thanks for release this app.

**Comment by rkkr** [comment]
It was available in this app a while ago. You can find the version with this theme looking at release comments. I removed it as it was implemented differently and was hard to maintain and theme it.
