### ISSUE TITLE
not Useable With Talkback

### ISSUE THREAD

**Issue by davidbtc2009** [rkkr/simple-keyboard#204]
The keyboard is completely not useable with the Talkback screen reader for android

**Comment by JM480** [comment]
This issue should be closed in favor of #324 since there is more details in that issue.

**Comment by davidbtc2009** [comment]
> This issue should be closed in favor of #324 since there is more details in that issue.

#324 appears to already be closed with nothing having been done

**Comment by bmivzkrp** [comment]
I confirm. The problem still exists.
