### ISSUE TITLE
[Request] Support for new autofill method that integrates with keyboard

### ISSUE THREAD

**Issue by Moxville** [rkkr/simple-keyboard#205]
Hi,
I request the feature:
Android 11's new autofill method that integrates with keyboard

https://www.androidpolice.com/2020/08/10/android-11-will-make-password-autofill-much-better-thanks-to-keyboard-integration/
https://developer.android.com/preview/features/ime-autofill#configure-provider

Thanks for the superb keyboard app 👍

**Comment by rkkr** [comment]
Not likely to happen as this would require to bring back most of the auto-correct functionality.

**Comment by Moxville** [comment]
Thanks for your reply
