### ISSUE TITLE
[Feature Request] add Theme

### ISSUE THREAD

**Issue by zpcol** [rkkr/simple-keyboard#209]
Black AMOLED Theme high contras :)

**Comment by zpcol** [comment]
the menu can't be taped.. :(

**Comment by zpcol** [comment]
already open when i change it to "material dark" but the color hasn't changed

**Comment by rkkr** [comment]
Set it after changing the theme.

**Comment by zpcol** [comment]
can be changed when "material light" but the font color is less bright :(

**Comment by rkkr** [comment]
It works for dark themes the same way...
