### ISSUE TITLE
[Feature Request ] Allow to create own character list...

### ISSUE THREAD

**Issue by legkamran** [rkkr/simple-keyboard#211]
I cant find characters that I need ... Can you make personal character list section? And change button add near space button I am adding screen...
Use <> part as changing button...
![Screenshot_20200828-012118_WhatsAppBusiness_1](https://user-images.githubusercontent.com/29841945/91496358-0b13ad00-e8cd-11ea-8fc2-e7d7ce76d213.jpg)

**Comment by rkkr** [comment]
There are more characters than I can type with a computer keyboard so I doubt that more are needed. Custom layouts are also not planned.
