### ISSUE TITLE
Menu above keyboard

### ISSUE THREAD

**Issue by anggit97** [rkkr/simple-keyboard#212]
i have requirement to had a menu above the keyboard, how to add icon above keyboard, and direct it to apps when click that icon. 
note: i already show the icon above keyboard, but the action click wont respond.

**Comment by Seylox** [comment]
I've been trying to do the same. My solution is to extend the area of the view insets.

In LatinIME.java find
`public void onComputeInsets(final InputMethodService.Insets outInsets)`

and replace the line
`final View visibleKeyboardView = mKeyboardSwitcher.getVisibleKeyboardView();`
with
`final View visibleKeyboardView = ((View) mKeyboardSwitcher.getVisibleKeyboardView().getParent());`

Maybe there's a better solution, but this seems to work for me so far.

**Comment by anggit97** [comment]
thanks its, work!!
