### ISSUE TITLE
[Feature Request ] Disable app icon from drawer

### ISSUE THREAD

**Issue by Sabonk** [rkkr/simple-keyboard#213]
Thanks for the best keyboard,it will be great if we can disable app icon from drawer by default

**Comment by rkkr** [comment]
https://www.reddit.com/r/GooglePixel/comments/dkjdg3/pixel_launcher_shows_hidden_icons_3a_xl_android/

Google has started restricting ability to hide app icons because this is abused by malicious apps. Other manufacturers will probably follow. You should use an alternate launcher like Lawnchair.

**Comment by RickyM7** [comment]
@rkkr Is this really not possible to do?  Some apps I have are not shown in the app drawer, for example Vanced MicroG and Tachiyomi extensions.  It would be great if the app icon was hidden like these apps mentioned.

**Comment by rkkr** [comment]
That is currently only not possible in a Pixel and the default launcher. But as the reason for this step Google made is due to malicious apps hiding themselves, more phone makers will probably follow and Google might start flagging apps that hide icons in the Play Store. So it's likely to get impossible in couple years.

I really do recommend using https://play.google.com/store/apps/details?id=ch.deletescape.lawnchair.plah

**Comment by RickyM7** [comment]
Got it, thanks for the explanation.

**Comment by RickyM7** [comment]
One last talk about it. What do you think about a show/hide icon in launcher option (enabled by default), such as on OpenBoard?
Example (OpenBoard):
![IMG_20201028_082424](https://user-images.githubusercontent.com/24703825/97430693-07fe6280-18f8-11eb-86e9-8c745932aca4.jpg)

Note: If it's not possible, there's no problem.

**Comment by rkkr** [comment]
That's the one that doesn't work in Pixel Launcher.

**Comment by RickyM7** [comment]
I understand. Now one off topic matter. I finished translating the app to Brazilian Portuguese on Crowdin, please take a look when you can.

**Comment by rkkr** [comment]
I have recently moved to a new city and still setting up in the new house. My workstation is packed in a box and I'm on 4G internet :) Will get to it eventually...

**Comment by RickyM7** [comment]
Oh, I didn't know that, sorry, and thank you for your work.
