### ISSUE TITLE
swipe-typing

### ISSUE THREAD

**Issue by maitra** [rkkr/simple-keyboard#216]
I really like this app but really miss swipe-typing. Wonder why it will "never have" it...

**Comment by rkkr** [comment]
#90 This requires dictionaries and a spell checker which take too much space.

**Comment by maitra** [comment]
Would be nice to have a plugin or an extended version, if possible.

**Comment by bagajohny** [comment]
Swipe typing is very handy when typing with one hand. I hope you reconsider it.

**Comment by ASAJFM** [comment]
I also adore swipe typing, so much so that I can't go back to the conventional method! Please find a way to include it ! :-)
