### ISSUE TITLE
Word suggestions

### ISSUE THREAD

**Issue by rugk** [rkkr/simple-keyboard#22]
Please add this line where you can get suggestions/corrections for words.

**Comment by rkkr** [comment]
Removal of suggestions (dictionaries) is what allowed to reduce app size to <1mb. I'll not adding them back if it increases app size.

**Comment by rugk** [comment]
Can't the dictionaries be downloaded by the user inside of the app/after installation? Then also only the one they need can be downloaded…

**Comment by rkkr** [comment]
Network access permission in a keyboard will not be accepted by all privacy freaks. The spell checker itself is also written in C++, which requires to build app for all CPUs. At this point you can just use GBoard.

Android system has some kind of dictionary built in, but couldn't find any info about it.

**Comment by PanderMusubi** [comment]
Perhaps add this to the README.md

**Comment by PhieF** [comment]
Wouldn't it be possible to provide it from an external app ?

For example:
your app checks when starting if a lib exists in its data director (/sdcard/android/data/package)

this lib could be added as a plugin by an external app, downloaded from fdroid or somewhere else

**Comment by sazarkin** [comment]
Hey guys, does anybody found solution for this?
I think ability to use existing dictionary from Sd card is very nice. Or even simple user filled dictionary will do.
I have 10-15 words I always make typos on, it is very annoying.

**Comment by sazarkin** [comment]
Maybe we can even reuse Firefox spell dictionaries https://developer.mozilla.org/en-US/docs/Mozilla/Creating_a_spell_check_dictionary_add-on

**Comment by PanderMusubi** [comment]
Depends very much on what you need. The dictionaries in Firefox, LibreOffice, etc. are all Hunspell dictionaries consisting of a .dic file and a .aff file. To reverse engineer a flat word list from these two files in not possible anymore. Is was possible a few years back. For flat word lists, it is better to use dedicated packages for those. Here is an overview for Ubuntu/Debian https://github.com/nuspell/nuspell/wiki/Ubuntu-word-list-packages

I'm one of the [Nuspell](https://nuspell.github.io/) developers and maintainer of the Dutch word list, and have researched this quite a lot. Note to properly give credit to any dictionary or word list used.
