### ISSUE TITLE
How to change key label and key code at run time?

### ISSUE THREAD

**Issue by harryngh** [rkkr/simple-keyboard#222]
Thank you for creating a very good custom Android keyboard. Would you please advise me how to change key label and key code at run time? I want to have the ability to change font for characters on the keyboard by replacing the character with its similar Unicode character, so I need to change the key label & key code when users choose.

**Comment by rkkr** [comment]
That is not possible with current structure. If the change is done in settings (when keyboard is not visible), you can add two keys and swap which is visible. That should not be possible with a visible keyboard as it requires to redraw all the keys.
