### ISSUE TITLE
BUG. the navigation bar is white. after updating to version 4.0

### ISSUE THREAD

**Issue by cpuuntery** [rkkr/simple-keyboard#227]
Version 4.0 the navigation bar is white. Enabling the matching colour option to make the navigation bar colour the same as the keyboard.

[![screen.png](https://i.postimg.cc/286ZbYNs/screen.png)](https://postimg.cc/nMyzg6z2)

**Version 3.23 the navigation bar is black**. Enabling the matching colour option to make the navigation bar colour the same as the keyboard.

I want the navigation bar to be black and I don't want it to be the same colour as the keyboard. So now I am using version 3.23. I think you can reproduce this bug if you use the android studio emulator because my phone use near stock android 9 API 28
if you want I Can send you a (Logcat)

**Comment by rkkr** [comment]
Sorry but I don't really understand what you did and what you expected. Also there are no nav bar color changes in 4.0.

**Comment by rkkr** [comment]
Tested in android 9 emulator and the results are:
"Use matching navigation bar" == false
![Screenshot_1607177999](https://user-images.githubusercontent.com/3480123/101245499-fd649380-3715-11eb-8abd-e5de0b2cb844.png)
"Use matching navigation bar" == true
![Screenshot_1607178014](https://user-images.githubusercontent.com/3480123/101245503-05243800-3716-11eb-925a-2a00b139bf9a.png)

I see the same in my Android 11 Pixel. I suspect that you are using a Samsung, however I still can't tell how 3.23 would work any differently. The only thing that could cause this would be Android SDK 11. Another thing to note is that your screenshot is in a lockscreen. Support for lock screen input was only added in version 4.0. Check in Chrome for example.

**Comment by cpuuntery** [comment]
@rkkr 
Thank you very much for your reply. And sorry if I made things confusing for you. I was just trying to explain the difference in behaviour between versions.
 **I just want the navigation bar to be black.**
And I tried using chrome. It is the same thing. The navigation bar is white in 4.0 and black in 3.23. And I don't understand what you said about the lock screen support. Even an old version like 3.17 I can still use it to enter my password. Maybe you mean 
[Direct Boot](https://developer.android.com/training/articles/direct-boot)
And I Am using Nokia 5.1 plus. And if you google Nokia, you will find that they use near stock android

**Comment by rkkr** [comment]
Nokias only look stock, but under the hood it's just another pile of chinese crap.

**Comment by cpuuntery** [comment]
@rkkr 
Aside from the pre-installed evenwell bloatware. I didn't find anything different from stock android. And I am a computer science student. I am not your average tech Joe. I installed arch Linux and compiled Gentoo from source. So please think of me differently

**Comment by rkkr** [comment]
I'm not trying to offend you, I'm trying to offend Nokia :) I have my own reasons for it. Read the history in https://dontkillmyapp.com/nokia .

As you're a computer sciance student, you can pull the source code, build it, revert the changes one by one and find exactly which change broke it. I can't really do that without a Nokia as this only doesn't work there.

**Comment by cpuuntery** [comment]
@rkkr 
I did not feel offended at all I just felt frustrated. Because [your comment](https://github.com/rkkr/simple-keyboard/issues/227#issuecomment-739314090) did not give me any useful insight about the problem. And about your last comment. Didn't you said that you were able to reproduce the issue with your pixel running android 11. And Android Studio is around 1 GB and my internet is not so fast. So how about I send you a verbose logcat. And if that would not help identify the bug. Then I will just keep using the old version. Because I had 0 issues with the old version. And I don't need or want any new features. I just need a lightweight keyboard to input text no more and no less. If you could not identify the bug. I will just close this issue and use the old version

**Comment by rkkr** [comment]
Look at the screenshots. Same result in Andoid 9 and 11 emulators and my Pixel, so no, I haven't been able to reproduce the white nav bar.

**Comment by cpuuntery** [comment]
@rkkr 
thank you for your effort. and for at least trying. i will just use the old version
