### ISSUE TITLE
[Feature Request] Option to turn Back Space into Delete key

### ISSUE THREAD

**Issue by fe60** [rkkr/simple-keyboard#228]
The option to move the cursor using the swiping feature is really helpful. But very often I miss the feature to delete a (couple of) character(s) on the right of the cursor. That would be much easier than moving the cursor and using Backspace afterwards. I miss the Delete key.

Instead of adding a Delete key, **I would like to have the option to change the direction of Backspace**.

This could be triggered by pressing the Shift key.
To visualize the changed direction, the Backspace icon can simply be turned by 180 degrees.
To avoid confusion this behavior should be configurable (new switch in Advanced preferences).
The direction of "Delete swipe" should be changed as well (swiping will still be done to the left, while selection goes to the right).

![Screenshot_20201218-113558_Conversations](https://user-images.githubusercontent.com/31078918/102606247-bff50280-4126-11eb-889f-7d04d56dd8e8.png)

**Comment by rkkr** [comment]
Using a "backspace" operation at the beginning of the statement is a more common scenario than "wanting to delete next character". This can't be controlled by shift. This also can't be controlled by delete long-press (like enter key).

I had an idea to allow right swipe on a delete key. The problem with that is that there is very little space and it is very close to the edge of the screen where touch will be swept away from the screen, which then commits the delete operation unexpectedly.

A workaround for that could be allowing space swipe while delete key is pressed, but that is unintuitive and quite hard to time properly to not trigger the delete long-press. Also current app logic doesn't work with multiple touch points.

This is a no go until a usable workflow is figured out.

**Comment by rkkr** [comment]
Actually **even thou that was not intended**, but delete + space swipe kind of works. The way to reproduce:

1. Swipe Delete left to select at least one character (this puts you into select+delete mode)
2. Keep holding Delete
3. Swipe Space right/left to move the right side of selection (keep holding Space)
4. Swipe Delete left/right to move left side of selection
5. Releasing Space or Delete commits the delete operation

However this is way more complicated than to just select the next char and click Delete.

This is a side effect of allowing space swipe to control the selection (long-press to select, then space swipe to move right side selection).

**Comment by goyalyashpal** [comment]
my idea is to rather have a separate key like replacing where the globe key currently resides.

the globe key should be able to be put in system bottom tray alongside "change keyb" button (yes, yet another idea lol)


<img src="https://github.com/rkkr/simple-keyboard/assets/19423063/0496d937-bd64-43b6-89ae-ff8d816a439f" width=250px/>
