### ISSUE TITLE
App can not be Installed

### ISSUE THREAD

**Issue by rizwankhan003** [rkkr/simple-keyboard#23]
#### Expected behavior
I should be able to install the app after downloading the apk file.

#### Actual behavior
After downloading the apk and trying to install it show message "app not installed"

#### How to reproduce
* Download the apk file from releases page.
* Try to package install the app.
* Note the bug
---
* Browser: simple-keyboard V2.8
* Operating system: Android version 7.0
* Device: HUAWEI Mate 10 lite

#### Recording Of The Bug
https://www.youtube.com/watch?v=QDRvbvyCgTc

**Comment by licaon-kter** [comment]
You can't upgrade the app installed from F-Droid with the one from Github (different signatures). 

Uninstall first...then reinstall. Or wait for F-Droid to update to 2.8. 

/Close as invalid
