### ISSUE TITLE
[Request] Separated keyboard on tablet?

### ISSUE THREAD

**Issue by AndhikaWB** [rkkr/simple-keyboard#24]
Great and simple keyboard. However, could you make it possible to separate the keyboard to left and right side on a large tablet? (with empty middle or just a space key on the middle).
It's hard to reach some keys on the keyboard using my thumbs on a large tablet because it's located on the middle of the keyboard, especially on landscape orientation. EDIT: Added a screenshot of AI Tablet Keyboard as an example.

![screen-9](https://user-images.githubusercontent.com/17119394/40981336-e1e300f6-6904-11e8-8861-8970f5aad33f.jpg)

**Comment by rkkr** [comment]
The way it done in the screenshot (with two floating windows) is not possible. AOSP keyboard had a split functionality where a blank space was left in the middle, but that only worked in a few languages and only only QWERT layout, so I had it removed. I use smaller window height in the keyboard, that helps a bit.

**Comment by AndhikaWB** [comment]
I'm not forcing you to do it but.. Will you bring back the feature? I think most people use QWERTY layout so that's acceptable (for me).

You can make it as an optional setting so people can choose between the original and split keyboard layout (with a warning message that it only support QWERTY).

**Comment by AndhikaWB** [comment]
Oh, actually I'm not asking for the floating keyboard feature, just can't find a perfect example for the picture.
