### ISSUE TITLE
Suggestion for management of recent emojies

### ISSUE THREAD

**Issue by Hogerys** [rkkr/simple-keyboard#246]
If you go into the emoji menu and inside that the recent ones, when you select an emoji the list automatically refreshes so its really hard to use that same emoji multiple times. It would be better if the list would only refresh when closed.

**Comment by licaon-kter** [comment]
What version has emojis exactly?

**Comment by Hogerys** [comment]
Open board has emojis. Because its based on this thing I assumed it has too.

**Comment by rkkr** [comment]
OpenBoard is most probably made from LatinIME.
