### ISSUE TITLE
[ Feature Request ] Turkish-Q layout support please

### ISSUE THREAD

**Issue by ndr48291** [rkkr/simple-keyboard#247]
It is most used layout in Turkey.

Thanks

**Comment by ndr48291** [comment]
v5.1 comes with turkish f layout. not turkish q :(

**Comment by rkkr** [comment]
@paledega ?

**Comment by ndr48291** [comment]
https://github.com/rkkr/simple-keyboard/issues/86

**Comment by rkkr** [comment]
Oh, so it's all fine. I thought that the layout was misnamed. Turkish F was added, if you want Turkish Q, make a PR.

**Comment by ndr48291** [comment]
I am not programmer. Sorry. I just raised a ticket for Feature Request, If you can add TR-Q layout in next version, that would be great. Thanks for your hard working.

**Comment by HanefiAcar** [comment]
I created xml files for Turkish-Q layout and uploaded them in the link below. If you please, you can add them in your next update.
https://github.com/HanefiAcar/Turkish-Q

**Comment by rkkr** [comment]
@HanefiAcar make a PR into this repository

**Comment by ndr48291** [comment]
Thanks PR: 297 When next release will be pushed @rkkr ?
