### ISSUE TITLE
Icon in "task view" is not shown properly

### ISSUE THREAD

**Issue by micwoj92** [rkkr/simple-keyboard#248]
Here the screenshot. In left corner above the app you can see that it is not shown properly, F-Droid for comparison. Please change title if necessary, I have no idea how else should I call it.

![Screenshot_20210213_133958_com huawei android launcher](https://user-images.githubusercontent.com/45581170/107850566-980edc00-6e03-11eb-8b99-f12aa62083ba.jpg)

**Comment by rkkr** [comment]
![Screenshot_1613396333](https://user-images.githubusercontent.com/3480123/107953552-f672c080-6fa3-11eb-8889-3238263b8212.png)

Looks just fine. What phone are you using?

**Comment by micwoj92** [comment]
Huawei P smart 2018 FIG-LX1, Android 9 with EMUI 9.1.0

**Comment by micwoj92** [comment]
I think it has do to with EMUI, when changing size of icon on default launcher sometimes the icon was "zoomed in" like this and sometimes fine. I just noticed some apps have this issue and some not. I see no visible pattern. I will try to make a bit more comprehensive list of apps on next weekend and check on the Internet, maybe it is a common issue. Another app that I reguraly use is

**Comment by micwoj92** [comment]
Out of ~330 apps updated in last month on F-Droid I've tested 174 and got the same bug in 3 of them. Opened bug reports on their repos and I wanted to test more but then the bug stopped appearing...

**Comment by micwoj92** [comment]
https://gitlab.com/Nulide/ShiftCal/-/commit/4b52685c840f11461a50254234538eef3184442d
