### ISSUE TITLE
Want to add some view on the top of the keyboard.

### ISSUE THREAD

**Issue by leena12345** [rkkr/simple-keyboard#25]
Want to add some view on the top of the keyboard.

**Comment by rkkr** [comment]
More details? View = background image?

**Comment by leena12345** [comment]
No,I have added one button on the top of the keyboard in main_keyboard_frame file as below:
 <RelativeLayout
        android:layout_width="match_parent"
        android:layout_alignParentBottom="true"
        android:layout_height="wrap_content">
        <Button
            android:id="@+id/tv"
            android:layout_height="wrap_content"
            android:layout_width="match_parent"
            android:paddingTop="30dp"
            android:paddingBottom="20dp"
            android:layout_above="@+id/keyboard_view"
            android:text="Hello World" />

        <rkr.simplekeyboard.inputmethod.keyboard.MainKeyboardView
            android:id="@+id/keyboard_view"
            android:layoutDirection="ltr"
            android:layout_width="match_parent"
            android:layout_alignParentBottom="true"
            android:layout_height="wrap_content" />
    </RelativeLayout>
It is showing properly, But when I open this keyboard in any third party application then this extra added button will hide another application's bottom view..Please help me how can I fix it.

**Comment by rkkr** [comment]
Keyboard height is fixed. If you want to add another row, you have to reduce the size of all the rows or somehow override the keyboard height. That is what the number row does.
