### ISSUE TITLE
There is latin letter "S" in Serbian cyrillic keyborad!

### ISSUE THREAD

**Issue by privateuserx54** [rkkr/simple-keyboard#251]
Serbian cyrillic keyboard (Српска АЗБУКА) have 30 letters: АБВГДЂЕЖЗИЈКЛЉМНЊОПРСТЋУФХЦЧЏШ not 31! Error is with latin letter "S" in Serbian cyrillic layout. Because of this typing on this keyboard is harder than typing on Gboard. Please remove latin letter "S" from Serbian cyrillic keyboard as soon as possible! 
![Latin letter S Serbian cyrillic keyboard](https://user-images.githubusercontent.com/79103233/107974890-8a01bc80-6fb7-11eb-93c6-7e21228abb38.jpg)

**Comment by soshial** [comment]
No need to panic. Actually, it is not **Latin** letter S, but a **Cyrillic** letter  S.

[According to Wikipedia](https://en.wikipedia.org/wiki/Dze#Usage), this letter is included into Serbian keyboard layout in Windows.

**Comment by rkkr** [comment]
GBoard doesn't have S in their Serbian layout. Windows keyboards might have included it just because there is a fixed number of keys. I'll probably remove it.

**Comment by rkkr** [comment]
59ddca67ad714d3e2760202167cb5fee50c5103f , but the change was bigger than I expected because Serbian layout is shared with Macedonian. To have different key counts they need to be split into separate keyboards, which also results in +10KB in size...
