### ISSUE TITLE
Wrong Slovene layout

### ISSUE THREAD

**Issue by pixpocker** [rkkr/simple-keyboard#252]
In the Slovene (Slovenščina) layout, the characters "z" and "y" should be swapped (see the Croatian layout). Additionally, the default long press selection of certain characters should be different: holding the "z" should select "ž" (U+017E), "s" should select "š" (U+0161), and "c" should select "č" (U+010D). These characters are used far more often than the currently assigned defaults.

**Comment by rkkr** [comment]
Layout is changed in 61da901f94a90b6cc1f1d234177db35a60bdea0b .
