### ISSUE TITLE
Function suggestions

### ISSUE THREAD

**Issue by Pantyhose-X** [rkkr/simple-keyboard#253]
* 1.Unlimited number of clipboard manager
* 2.Hope to support Google Text-to-Speech Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.Applied to language learning. Pronunciation correction
* example，https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213

**Comment by rkkr** [comment]
1. Duplicate of #95 
2. Not going to happen
