### ISSUE TITLE
Can I get access to EditText setText method while using custom keyboard?

### ISSUE THREAD

**Issue by khemrajsharma** [rkkr/simple-keyboard#256]
Please help regarding this issue.

https://stackoverflow.com/questions/66363399/can-i-get-access-to-edittext-settext-method-while-using-custom-keyboard

**Comment by rkkr** [comment]
It won't be easy to add into Simple Keyboard. All the "store in cache and commit on space click" logic is removed along with with spell checking. When text ("gm") is committed and sent to the input application, there is no easy way back to change it to something else. You could simulate backspace being clicked twice and then commit some other text, but that's a horrible hack.

You would need to pull back code from year 2017: dc61abb74008b1ecaf14b0fcfb8823803a2c1a76
Look at `onStartBatchInput` and code related to it. That's the area where you would add such logic.
