### ISSUE TITLE
Draw behind navigation bar like ASK

### ISSUE THREAD

**Issue by n-ce** [rkkr/simple-keyboard#257]
ASK 
![Screenshot_20210305-090347](https://user-images.githubusercontent.com/69345507/110064024-49b18500-7d92-11eb-835b-f326246ae7fd.png)
Simple Keyboard
![Screenshot_20210305-090734](https://user-images.githubusercontent.com/69345507/110064044-5b932800-7d92-11eb-8941-f205b23dcbe8.png)

**Comment by rkkr** [comment]
This setting is called "Use matching navigation bar color". Available from Android 10.
