### ISSUE TITLE
Restore position of ¿ and ¡

### ISSUE THREAD

**Issue by jorgman1** [rkkr/simple-keyboard#258]
Since the last update, it is quite anoying to use this punctuation marks, because one needs to change first to the symbols tab. Before, they appeared when hovering on the ".". That was much faster.

**Comment by rkkr** [comment]
What language are you using? "¿ and ¡" were never available in long-press "." for English language.

**Comment by jorgman1** [comment]
Spanish

**Comment by rkkr** [comment]
Yep, that was a mess-up. This sometimes happens when indexes are changed in cache. Should be fixed: b37c5edce7767d4a2d18c1afcc5ef0335bb81bae .

**Comment by jorgman1** [comment]
Thanks! That was quick :)
