### ISSUE TITLE
Restore old Persian layout

### ISSUE THREAD

**Issue by arhayati** [rkkr/simple-keyboard#260]
The Persian layout is changed. This is the new layout: 
![20210306_202041](https://user-images.githubusercontent.com/64958513/110214541-503b1c00-7eba-11eb-8852-3235ce17fb57.jpg)
![Screenshot_20210306-202022_Firefox](https://user-images.githubusercontent.com/64958513/110214580-795bac80-7eba-11eb-887a-04c6e9e7e20a.jpg)

And this is the old layout:
![20210306_202344](https://user-images.githubusercontent.com/64958513/110214545-56c99380-7eba-11eb-9e95-3716c7bdd9b3.jpg)
![20210306_202358](https://user-images.githubusercontent.com/64958513/110214550-58935700-7eba-11eb-89ec-6b91d0a79e8e.jpg)

**Comment by rkkr** [comment]
Check on 4.7 version. Should be fixed.
