### ISSUE TITLE
[Enhancement] Improve Settings Screens

### ISSUE THREAD

**Issue by wittmane** [rkkr/simple-keyboard#263]
I think there are some improvements that can be made to the settings screens. I'm working on implementing it, but I figure it would be useful to have some discussion over it before I make the PR.

The primary and most significant change is for how custom keyboard layouts are enabled. I think the current method is slow and tedious, and I have an idea of how to improve it. Similar to Gboard's settings, we could add a settings page listing the used languages that would lead to an individual language settings page where the different layouts could be toggled on or off. Since Simple Keyboard uses multiple subtypes, the user would still need to go to the system's subtype settings page to actually enable it. This seems somewhat like redundant work and makes it less smooth compared to Gboard, but it isn't really any degradation from the current functionality. When creating the subtypes in the settings page, we can pop up a button at the bottom of the screen to allow the user to jump to the system subtype settings, which should work as a reminder that the subtype isn't fully enabled, but it won't be a popup to allow setting multiple layouts before going to enable all of them. We can also add an indicator on the main language page for languages with a subtype created but not enabled.

I've created a prototype of this that you can check out [https://github.com/wittmane/simple-keyboard/tree/subtype_settings](https://github.com/wittmane/simple-keyboard/tree/subtype_settings).

The main languages settings page:
![Settings_Languages](https://user-images.githubusercontent.com/16480765/111856568-9f8d3d80-88f9-11eb-96fc-b28afb14460d.png)

Language specific settings pages:
![Settings_English](https://user-images.githubusercontent.com/16480765/111856574-a916a580-88f9-11eb-9573-03cfd9f17526.png)

![Settings_Hindi](https://user-images.githubusercontent.com/16480765/111856580-af0c8680-88f9-11eb-84d2-996c0a7def19.png)

I came up with a few scenarios and counted the number of click/scroll actions that are necessary to complete the workflow to see how much this improves things.

- single language speaker trying a new layout: 13 -> 7
- bilingual speaker with default layouts: 6 -> 7
- bilingual speaker trying an alternate layout in second language: 15 -> 11
- bilingual speaker using an alternate layout for both: 23 -> 14
- single language speaker using an alternate layout trying a new layout: 22 -> 9

The only one that wasn't an improvement was when no custom layout was used, and it only increased one click because the button to launch the system setting is one setting screen deeper.

If you have any suggestions on how to make this more intuitive, I'd be happy to hear it. This is the best I came up with, mostly limited by forcing the user to go to the system setting page, but I don't think we can get around this unless we remove the multiple subtypes and just manage it virtually, similar to Gboard, but I personally don't like that, and I don't really want to make that big of a change here.

One specific thing I'd like feedback on is what name we should display for the keyboard layouts. Currently, I have it just match what is shown in the system settings page, but that looks somewhat weird with the repeated listing of the name of the language when everything on the page is for that language. Also, it's somewhat odd to show the names of the alternate layouts but not show the name of the default one (ie: for English, mention things like qwertz, but not qwerty). If I just simplify to list the name of the subtype, we'll need to do something for the languages using non-generic layouts. For most we could just list the name of the language, which won't seem too repetitive since most have just one, but for things like Hindi and Hindi (Compact), we could probably just use something like "Hindi" and "Compact". I think that's a better approach, but that will probably require messing with strings to make sure things are still translated properly, so I'd like to verify that is what we want before I do the work.

The other change is just some general reordering of settings to be in more intuitive locations. (I could split this into a separate PR if you prefer, but since I'm messing with settings, it makes sense to me to do it together.)

My proposed new ordering:

- Languages
    - Enable languages and layouts
    - \<enabled languages\>
        - \<keyboard layouts\>
        - Input styles still need to be enabled (conditionally)
- Preferences
    - Auto-capitalization
    - Show separate number row
    - Hide special characters
    - Hide language switch key
    - Space swipe cursor move
    - Delete swipe
- Key press
    - Vibrate on keypress
    - Keypress vibration duration
    - Sound on keypress
    - Keypress sound volume
    - Popup on keypress
    - Key long press delay
- Appearance
    - Theme
        - \<options\>
    - Set custom keyboard color
    - Use matching navigation bar color
    - Keyboard height

I think my main issue is with the "advanced" grouping. A number of settings currently there don't seem like advanced settings, such as showing the separate number row or swiping for cursor movement or deleting. Also, I think it's awkward to keep related settings far apart (eg: keypress vibration duration and generally enabling keypress vibration). I don't see a benefit in keeping these apart. If I decide to enable vibration, but I want it at the lowest setting, I have to jump between multiple pages, and trying to obscure the ability to change the vibration duration doesn't seem valuable.

**Comment by rkkr** [comment]
Looks good from the descrption. You can make a PR so checking the code is easier.

**Comment by wittmane** [comment]
@rkkr I came up with a new idea for how we could manage subtypes. Instead of managing virtual subtypes, we could remove all of the subtypes from method.xml and build them all in settings like what is done for the generic ascii compatible layouts. Users would still need to go to the system subtype settings screen, but it will only be populated with what the users wants to use (only a few items), so they shouldn't need to go searching for what they need to enable (the user should enable everything in the list). I'll admit it's still a bit annoying to need to enable them in the system, but this would allow the subtypes to still be listed in the popup when changing the active keyboard. I think this benefit outweighs the slight annoyance of somewhat duplicative work since that only needs to be done once to set up the app. Also, if there is only one layout enabled per language and all of the used languages are enabled in the system, they shouldn't even need to go to the system settings screen since the "use system languages" option in the system settings screen is the default. I should be able to only prompt the user to go to the system settings when it's actually necessary.

Does this seem like a reasonable solution, or do you think it would be better to just manage the subtypes entirely virtually and get rid of the system subtype settings screen?

**Comment by rkkr** [comment]
But the average person who only wants to enable another language, he now has to make 2 actions: enable language in settings and enable language in system. I think this is worst than what we currently have.
