### ISSUE TITLE
System Default on Android 10 Who Using Dark Theme is Not Black

### ISSUE THREAD

**Issue by etden** [rkkr/simple-keyboard#264]
Any idea why the keyboard color just turns grey when using dark mode on Android 10. I'll try to force dark settings on Developer Mode but the color still greys. Thank you.

**Comment by rkkr** [comment]
"Grey" is the Material Dark background color. This color is set by OS. If you want to set yout own color, just use dark theme and set custom background in advanced settings.
Or wait for Android 12 where themes should be customizable.

**Comment by etden** [comment]
That's awesome!. Sorry for being thorough.
