### ISSUE TITLE
Keyb mode auto changes on pressing space

### ISSUE THREAD

**Issue by yashpalgoyal1304** [rkkr/simple-keyboard#265]
### Steps:
<kbd>?123</kbd> > type anything from there > press <kbd>⌞space⌟</kbd>

### Reality:
The keyboard switches back to alphabet <kbd>ABC</kbd> mode automatically

### Suggestion:
The keyboard should stay in the number-symbol <kbd>?123</kbd> mode

### Details
- The layout/keyboard mode (like alphabet/number/symbol ) should NOT change from number-symbol to alphabet automatically on pressing space bar.
- I know that it was/is how most other keyboards work, but it is suuuper frustrating to me as i usually have to enter things (numbers and symbols) from that mode with spaces in between. 
- i think this is not a fancy thing
- The suggested behaviour is found in https://github.com/florisboard/florisboard (i am running v0.3.5)

**Comment by rkkr** [comment]
Switching back to `ABC` is the default behavior across the keyboards. Working differently will cause confusion. Also "entering single number" is probably the more common use case, so switching back is helpful.

**Comment by yashpalgoyal1304** [comment]
hey hey, closing without asking for any further input?? wow, that's kinda strange

**Comment by yashpalgoyal1304** [comment]
One way to implement this can be by taking inspiration from shift key. When double tapped (in quick succession obv) - the shift key stays in caps mode (i.e. say - it becomes persistent). It is indicated by the change in shift key's bg color (in this keyb) or by showing an underline under shift key (in other keyb)

Similar thing can be done for <kbd>?123</kbd> key - double tapping it makes it persistent. This will cover both cases in harmony.

**Comment by rkkr** [comment]
Sticky shift key is for a common known functionality of Caps Lock. You'll know how this will work without thinking.
Sticky `?123` is possible, but it will cause confusion. Shift state is reset after one letter. Special chars is reset after one word. You won't know that this is possible unless you accidentally double clicked it. And then you won't understand what this lock means, as `?123` doesn't reset after one letter is clicked.

The behavior of keyboard will not differ from "common functionality across keyboards". Otherwise majority of users think it's a bug, even if it's an improvement over other keyboards.

**Comment by yashpalgoyal1304** [comment]
well, it still wont affect/conflict with the common usage and the added functionality will be available for those who know and want it. That's what all the power user's software do.

**Comment by yashpalgoyal1304** [comment]
ohh, and my final persuasion clause will be - the simple keyb is otherwise totally suffice for me; i like it (there are some other bugs/quirks still, but those are all bearable/things agreed upon)

Currently i face this problem of autoswitching in simple - do manual switch back 2-3 times. got frustrated and switch to above said keyb, and switch back to simple - all due to lack of this thing in simple. sok it will be super nice to have this li'l added functionality too.

**Comment by rkkr** [comment]
What is the input application that you're writing all these numbers in?

**Comment by yashpalgoyal1304** [comment]
say for the purpose of noting things like **timestamps**, or dealing with **syntax stuff** like markdown/katex etc.  
The applications being [telegram](https://apkpure.com/p/org.telegram.messenger), hoverboard, [markor markdown editor](https://f-droid.org/packages/net.gsantner.markor), or github/[gitlab](https://gitlab.com/inkscape/inbox/-/issues) in browser at times.

**Comment by goyalyashpal** [comment]
hey @rkkr can u close this as "not planned" ?
