### ISSUE TITLE
[Feature request]  Independently adjustable portrait and landscape height

### ISSUE THREAD

**Issue by fenyvessy** [rkkr/simple-keyboard#266]
I use simple keyboard a lot in Termux with ssh, where sometimes portrait mode is better because of the many visible line in the terminal, sometimes landscape is better because of the wider lines. So far, I used Hacker's keyboard, where there is two ways to do this: on the one hand, it is possible to adjust the portrait and landscape keyboard height separately in the settings, and on the other hand, I could adjust the keyboard height with the volume buttons on the fly. Are you planning any similar solution that can not only be used to adjust height globally?
In connection with this, it would also be useful for me if the separate number row could be set to always off / portrait only / landscape only / always on. In portrait mode it would rather be there because it is more convenient type IP addresses, but in landscape mode it would be better if I could turn it off, because the extra 4-5 lines that would still fit in the terminal would be worth a lot more.
Thx.

**Comment by rkkr** [comment]
Dup #146
