### ISSUE TITLE
request: emoji group different skin tones

### ISSUE THREAD

**Issue by tbenett** [rkkr/simple-keyboard#271]
Having all different skin tones of an emoji displayed, make the experience of finding one so difficult and longer than needed.

Almost one row is taken by one "group"

 ![Screenshot_20210425-101754](https://user-images.githubusercontent.com/3235855/115986231-8b4ef700-a5af-11eb-9433-14f463c8238b.jpg)

Would be great to have them grouped together.

**Comment by licaon-kter** [comment]
Did you confuse the keyboard app? This one, last time I checked, did not have emojis, on purpose.

Maybe OpenBoard or Floris?

**Comment by tbenett** [comment]
Yes Openboard. Sry
