### ISSUE TITLE
Delete swipe should consider surrogate pairs as a single character

### ISSUE THREAD

**Issue by digitalheir** [rkkr/simple-keyboard#276]
`LatinIME.onMoveDeletePointer` counts how many 'steps' it should delete, translating to Java chars currently. Some glyphs, such as emoji, are represented in Java as 2 chars. It happens sometimes that delete 'lands' in the middle of these chars. Also the cursor moves twice as slow through emoji, impacting experience.

For example, try input:

😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀😀

It is a matter of time before one of these `\uD83D\uDE00` becomes `\uD83D`.

Specifically the line:

```
final int start = mInputLogic.mConnection.getExpectedSelectionStart() + steps;
```

I believe should be more along the lines of

```
final int start = mInputLogic.mConnection.getExpectedSelectionStart() + countBackCharacters(steps);
```

~~Making use of `RichInputConnection.getTextBeforeCursor`.~~ Although I don't quite know what's the best way to get the cached text before the cursor.

The `handleBackspaceEvent` method already handles surrogate pairs correctly:

```
final int lengthToDelete = Character.isSupplementaryCodePoint(codePointBeforeCursor) ? 2 : 1;
```

I would like to make a pull request myself, but I'm a bit mystified by how to get the text before cursor.

**Comment by rkkr** [comment]
`RichInputConnection.getTextBeforeCursor` and `RichInputConnection.getTextAfterCursor` are the ones to get the text before/after cursor. And you already found how char pairs are detected, so it really shouldn't be hard.

All you have to do is:

1. Add two functions in `RichInputConnection` for "before/after index to char count"
2. Run thru expected char count and ++ if `isSupplementaryCodePoint`
  a. Out-of-range limiter should be moved here from `RichInputConnection.setSelection`
3. Call this function in `onMovePointer` and `onMoveDeletePointer`
