### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by karnotcycle** [rkkr/simple-keyboard#279]
1. spell check, or at-least integration of system default spell check and correct.
2. AMOLED dark theme
3. emoji key, or at-least emoji key on long-press of enter key as in openboard

Apart from the above, the app is perfect. If these are implemented, it will be even great. Looking forward to see these included. Thank you.

**Comment by rkkr** [comment]
1. Dup #22 
2. Set dark theme and custom color #000000
3. Dup #13
