### ISSUE TITLE
Add on F-Droid

### ISSUE THREAD

**Issue by M2ck** [rkkr/simple-keyboard#3]
Please add your app on F-Droid store.
https://f-droid.org/contribute/

**Comment by am2012** [comment]
Yes please

**Comment by BrainBlasted** [comment]
@rkkr, could you please explain why you closed this issue? Having this on F-Droid could bring more contributions and users. I'm pretty sure it also fits their submission criteria.

**Comment by rkkr** [comment]
Not willing to maintain multiple distribution platforms.

**Comment by BrainBlasted** [comment]
I don't think you have to do much maintaining at all. All you have to 
do is push a tag on github, and F-Droid automates the building and 
distribution IIRC.

**Comment by luckycouple** [comment]
Please, take a second thought about publishing your app in F-Droid. It is an excellent app.
Thank you

**Comment by rkkr** [comment]
I don't intend to maintain it. But it's all open source. If you want- there is no one stopping you from adding it there.

**Comment by IzzySoft** [comment]
Wow, thanks! Find it [here](https://apt.izzysoft.de/fdroid/index/apk/rkr.simplekeyboard.inputmethod) for now. I'm pretty sure it will be picked up at F-Droid soon as well.

**Comment by Kasijjuf** [comment]
https://f-droid.org/app/rkr.simplekeyboard.inputmethod

Found this issue after finding Simple Keyboard on F-Droid. I do believe this issue can now be considered fully resolved.
