### ISSUE TITLE
Rebase to LineageOS keyboard?

### ISSUE THREAD

**Issue by Eddi2015** [rkkr/simple-keyboard#30]
Some guys (including me) wanted swype support and word suggestions. LineageOS' keyboard is able to do this, so I thought you could make a second app with Lineage keyboard or even replace this one. Personally I don't mind a bigger app size and/or network permission do downloading dictionaries. Please consider doing this :)

**Comment by rkkr** [comment]
AOSP keyboard (the one this is forked from) also has dictionaries and swype. They were removed to achieve the <1MB size. If you don't mind the size and network access, just use GBoard.

**Comment by Eddi2015** [comment]
Well I'd like to have word suggestions, but I don't like the google tracking shit (I mean 150 mb for a keyboard!?) So a keyboard similiar to this, but with word suggestions would be nice. I'm sure this won't be 150 mb. Anyway if you don't like to "bloat" this app w/ word suggestions please create a fork :)

**Comment by aldrinjenson** [comment]
Hi @rkkr , could you please suggest any other app for the same other than GBoard.. something which is FOSS.
Currently I'm using OpenBoard, very similar to GBoard, but the swype feature in not yet there. Some suggestions would be much appreciated. Thanks
