### ISSUE TITLE
[Feature Request] Blur or transparent effect 

### ISSUE THREAD

**Issue by bolbolfolfol** [rkkr/simple-keyboard#301]
Hi
Thank you so much for this wonderfull app
i wonder if you can add option to enable blur or adjustable trasparent effect when using simple keyboard and thank you so much !

**Comment by rkkr** [comment]
Transparency won't work on majority of apps as they get resized to the area above the keyboard leaving the keyboard background blank (if I made it transparent, it would just be black). I assume by blur your also mean transparency + blur.

I won't do any hacks that would try to overflow the applications to bypass this resizing as it would introduce bugs like not being able to reach the edit field at the bottom, as hey, it's below the keyboard and you can't scroll more.

**Comment by bolbolfolfol** [comment]
blur is effect like this

https://www.xda-developers.com/files/2014/07/03.png

**Comment by bolbolfolfol** [comment]
blur is like this

https://www.xda-developers.com/files/2014/07/03.png
