### ISSUE TITLE
advanced settings gone?

### ISSUE THREAD

**Issue by ristein** [rkkr/simple-keyboard#302]
I can't find the advanced settings anymore.
Are they gone?
![Screenshot_20210717-191232_Simple_Keyboard](https://user-images.githubusercontent.com/55446611/126044695-35b6ea30-bf06-4aa0-8ed3-47b3b4652a3e.png)

**Comment by rkkr** [comment]
Yes, the settings are distributed in their categories.

**Comment by ristein** [comment]
ok, sorry, thanks
