### ISSUE TITLE
[Enhancement] Fresh icons

### ISSUE THREAD

**Issue by mutedbird** [rkkr/simple-keyboard#311]
Hey @rkkr
I redesigned the icon for the application, hope you like it. Ready-made version and sources in the archive 
![web_hi_res_512](https://user-images.githubusercontent.com/89584155/130958088-d117219c-7995-415d-a4ee-e69862fe8374.png)
[ic_launcher.zip](https://github.com/rkkr/simple-keyboard/files/7059463/ic_launcher.zip)

**Comment by wittmane** [comment]
I prefer v4, but I think that a shade of gray for the keys somewhere in between the two might be even better. Other than that, I think the design looks good.

One other thing to consider is whether this should be an adaptive icon. It looks like you have this as a fixed rounded square icon, but I think the current standard for Android icons is to be able to match the system shape.

**Comment by rkkr** [comment]
I wasn't eager to add adaptive icons as that requires including two sets of icons: normal for Android 7- and adaptive for Android 8+. This takes up more space. I can check how much exactly.

**Comment by rkkr** [comment]
Adaptive icons are +15kB, so maybe it's not too bad...

**Comment by rkkr** [comment]
Included in https://github.com/rkkr/simple-keyboard/releases/tag/89
