### ISSUE TITLE
enable some quickly function 

### ISSUE THREAD

**Issue by xi7** [rkkr/simple-keyboard#316]
![Screenshot_2021-10-03-19-44-58](https://user-images.githubusercontent.com/67331785/135774002-a02cf4e6-c6f9-4bdd-a0ac-7edffa66c3bd.png)

add space bar slide up/down show some function, very useful.

**Comment by rkkr** [comment]
The app doesn't have a top bar, so there is no place to put them in, nor a mechanism to invoke and close that top bar.
