### ISSUE TITLE
Can you make it so the modified characters in Latvian are the default long-press option? Thank You!

### ISSUE THREAD

**Issue by ghost** [rkkr/simple-keyboard#319]
https://en.m.wikipedia.org/wiki/Latvian_language#Standard_orthography

The modified ones are next to the normal ones in the tables here.

Currently, the keyboard uses symbols instead of mod characters in the long-press defaults. ex. k -> "(" and not "ķ" currently.

Thank You!

**Comment by soshial** [comment]
This was fixed in 1be5b5ad4d86a0bff2bfae18d4ecd7cc2e730cdf, @rkkr.
