### ISSUE TITLE
[Feature Request] Add Simplified Chinese Characters as Language

### ISSUE THREAD

**Issue by hubortje** [rkkr/simple-keyboard#322]
Hello there,

I know that there has been a [similar feature request for Pīnyīn,](https://github.com/rkkr/simple-keyboard/issues/208) and a sufficient answer why this isn't possible.
Is the response valid for simplified chinese characters aswell or would this be a possible feature?

Thank you and best regards.

**Comment by rkkr** [comment]
Same applies.
