### ISSUE TITLE
[v5.5 update bug] space swipe cursor move

### ISSUE THREAD

**Issue by disdaogitacc** [rkkr/simple-keyboard#323]
the bug has affected RTL languages(persian in my case). space swipe moves the cursor to the opposite direction.

for example:
**Hello**(space swipe left, cursor moves to the left)

**سلام**( space swipe left, it moves the cursor to the right)

thank you

**Comment by rkkr** [comment]
Thanks for testing. b4c5e6de4e6d54605f4a0494b5cf010377c310c5
