### ISSUE TITLE
Key press highlight issue

### ISSUE THREAD

**Issue by licaon-kter** [rkkr/simple-keyboard#327]
5.5
![](https://i.imgur.com/S4D3hm4.png)

5.6
![](https://i.imgur.com/V1Wg6ds.png)

Can this be customized or reverted to 5.5's muted one?

**Comment by rkkr** [comment]
Haven't noticed this as popup covers it by default. You should theoretically see no differences yet. Will fix, I'm currently rewriting System Theme to be able to add Android 12 dynamic theming.

**Comment by licaon-kter** [comment]
I'm on Android 11, no popup.

**Comment by rkkr** [comment]
Colors got mixed up in all the migrations: 89a0ea5f374aa018efa0e3b217b164ade18fb7b2 .
This was material dark theme. System themes now have slightly different icons.
