### ISSUE TITLE
Blank space below keyboard

### ISSUE THREAD

**Issue by tcgmoo** [rkkr/simple-keyboard#329]
Android version: 12
App version: 5.8

There is a blank space below the keyboard. Sometimes its a plain white bar and other times its transparent and allows seeing the content below.
![Screenshot_20220119-170952~2](https://user-images.githubusercontent.com/96886076/150099719-da3416a0-646a-4ddc-a8f9-6f7ed61fc7ed.png)
![Screenshot_20220119-171548~2](https://user-images.githubusercontent.com/96886076/150100559-b9fb14cc-2e66-46c8-87c6-d07a15caf9f8.png)

It seems to be a problem with the 'Use matching navigation bar color' setting.

**Comment by tcgmoo** [comment]
I forgot to mention, I'm using the System Default theme

**Comment by rkkr** [comment]
Should fix it: 14def9520f320c528f011f17b4394c762f6781f9 . For dark themes this setting doesn't change anything as it matches anyway.
