### ISSUE TITLE
Latest Version crashes for me

### ISSUE THREAD

**Issue by smaier-at** [rkkr/simple-keyboard#330]
First, let me say I love your app! No fancy features, just does what it should, usually...

But this leads me to my problem:
After the latest Update I got soft-locked out of my phone, because Simple Keyboard keeps crashing and I couldn't enter my password... ("Unfortunately, Simple Keyboard has stopped.")

I tried to reboot my phone, and also reinstall the app, but the problem persists. Unfortunately I have no idea if and how I can provide more information...

Br

**Comment by licaon-kter** [comment]
Device? Android version?

**Comment by smaier-at** [comment]
HTC One M8 with custom ROM running Android 6

**Comment by rkkr** [comment]
And the app version that crashes + version that worked?

**Comment by smaier-at** [comment]
currently installed (and crashing) is version 5.8 updated via f-droid
previously installed most likely 5.7 (but not 100% sure, is there a way to look that up?)

**Comment by smaier-at** [comment]
Yeah, I just uninstalled 5.8 and installed 5.7 --> it's working

**Comment by rkkr** [comment]
Found it, a totally stupid mistake.

**Comment by rkkr** [comment]
1ae840150d6a349709b4e275bd78c6e8483679b5
