### ISSUE TITLE
another app with the same name?

### ISSUE THREAD

**Issue by bLu02th** [rkkr/simple-keyboard#335]
https://github.com/SimpleMobileTools/Simple-Keyboard

Seems like the Simple Mobile Tools developer created their own keyboard with the same name. Will there be any changes to the name to help specify which app is which?

Just asking, not a prio, thanks :D

**Comment by rkkr** [comment]
Well @tibbi probably won't change his naming scheme. And my app is at 1M+ installs so wouldn't want to change it and this name and my apps is available since 2017.

I wonder if publishing of another Simple Keyboard has anything to do with #333 ?

**Comment by licaon-kter** [comment]
That's like a conspiracy theory :)

**Comment by tibbi** [comment]
not really, app names are not unique... There are like a million apps with the same name

**Comment by bLu02th** [comment]
Thanks for checking, and still gonna use your Simple Keyboard. 👍 

Gonna close this ticket for now, but feel free to comment or to reopen it anytime. Have a great day! And thanks for maintaining this app too 😄
