### ISSUE TITLE
Screen Navigation

### ISSUE THREAD

**Issue by dineshkandan** [rkkr/simple-keyboard#337]
I have created my own custom activity and layout . i have added button in keyboard to navigate to my activity .
How to navigate to my activity from keyboard and need set data once my custom activity closed

**Comment by rkkr** [comment]
Read the Android docs. Starting an Activity is just starting it. You can catch the click event same way as Settings key is handled. To get back what what was selected there you'll need some kind of callback. None if this is specific to a keyboard.
