### ISSUE TITLE
Copycat/Clone on Google Play

### ISSUE THREAD

**Issue by Poussinou** [rkkr/simple-keyboard#339]
Hi @rkkr 

Is this a copycat of your app below?

https://play.google.com/store/apps/details?id=com.zaibiapps.easykeyboard

It has the same Play Store description at least, and it looks suspicious (internet permissions and stuff)...

**Comment by rkkr** [comment]
Looks like it is a fork. You will find other forks too in play store, some even have larger install counts. This one looks like abandoned.

However creating clones is allowed by Apache license. This keyboard is also a fork of LayinIME.
