### ISSUE TITLE
add multi-language version?

### ISSUE THREAD

**Issue by MaximilianFans** [rkkr/simple-keyboard#342]
Hope that we can have a multi-language version apk or at least can support French, German and Spanish

**Comment by rkkr** [comment]
Meaning multiple languages shown at once?

**Comment by MaximilianFans** [comment]
> 
No. Cause I'd like to type in German but failed for both changing the system language of my phone and choosing German in the keyboard setting. The keyboard just didn't show the German alphabet. I've choose the latest version apk. So I wonder if it can support multi-language.

**Comment by rkkr** [comment]
System language is only picked up at first start, changing the phone language afterwards doesn't change the layout list.

To set the custom layouts just go to Settings -> System -> Languages and Input -> On-screen keyboard -> Simple Keyboard -> Languages -> "+".

Or long-press "," within a keyboard.
