### ISSUE TITLE
System Default Black

### ISSUE THREAD

**Issue by JM480** [rkkr/simple-keyboard#351]
Can you add an option for the system default and system default border themes to be black when dark mode is active? It could be a setting under appearance when a system default theme is used rather than being separate themes.

**Comment by rkkr** [comment]
They are black when dark mode is active, that's the point of them is to look the same as the system.

What device and Android are you on?

**Comment by JM480** [comment]
Moto G7 Play running LineageOS 18.1 which is based on Android 11. For me the keyboard looks dark grey instead of black and it also looks the same on my tablet running Android 10.

**Comment by rkkr** [comment]
"Dark grey" is the default dark theme for Android <12. If Lineage has modified the values for `Theme.Material` to make it "pure black" then this modified style should load in V5.5. In later versions I had to modify how styles are applied to support Android 12 dynamic theming. Please test if it works differently.

But most probably Lineage has made a separate theme and applies it on system only. Then apps don't get these changes.

**Comment by rkkr** [comment]
Check v5.5, it may or may not work there. I won't add settings to override system themes as it messes up the dynamic changes.

You may just set a dark theme and set a black background.

**Comment by JM480** [comment]
The system default dark in v.5.5 is darker but it isn't black.

**Comment by JM480** [comment]
Could the System Default dark theme be made darker for Android 11 and below? I think it would look better if the dark theme was darker.
