### ISSUE TITLE
Back button does not delete highlighted URL from address bar

### ISSUE THREAD

**Issue by jcperil** [rkkr/simple-keyboard#353]
**Describe the bug**
Pressing back with Simple Keyboard on a highlighted URL in address bar does not erase the URL.

**To Reproduce**
1. Make Simple Keyboard as your default keyboard.
2. Open [https://github.com/rkkr/simple-keyboard](https://github.com/rkkr/simple-keyboard) in a browser.
3. Click on the address bar. The URL gets highlighted and your default keyboard shows up.
4. Press the back button. No action. URL stays highlighted.

**Expected behavior**
URL is erased from the address bar.

**Device specs**
 - Device model: M2101K6P
 - Android version: 12
 - Simple Keyboard version: 5.9 (F-Droid)

**Additional context**
[Indic Keyboard](https://gitlab.com/indicproject/indic-keyboard)  shows expected behaviour.
Attachment: 
![indic](https://user-images.githubusercontent.com/89805719/178119756-0e7bf31d-aae6-4954-9fc6-9070884f7336.gif)

Simple Keyboard doesn't.
Attachment: 
![simple](https://user-images.githubusercontent.com/89805719/178119747-630940b3-924e-4e60-8196-97546b19d76e.gif)

**Comment by rkkr** [comment]
From the gif I see that you are using Brave browser. I'll check, but that is most probably a bug in Brave side.

**Comment by jcperil** [comment]
That's why I illustrated Indic Keyboard where it works fine. Are you certainly sure that it is a bug in brave browser? I will open an issue with brave browser if that's the case.

**Comment by rkkr** [comment]
Something is wrong with the browser on address bar click:
1. `isInputViewShown()` returns false
2. `getTextBeforeCursor()`returns null

I haven't yet checked how the original LatinIME keyboard behaves as most of the APK are not working in emulator.

**Comment by jcperil** [comment]
This is to clarify that by Indic keyboard, I mean https://gitlab.com/indicproject/indic-keyboard, not the one by google.
