### ISSUE TITLE
can simple keyboard provide hardware layouts?

### ISSUE THREAD

**Issue by yashpalgoyal1304** [rkkr/simple-keyboard#354]
* on connecting a physical keyboard to an android phone (running android 11), 
* In screen of `Keyboard & input method : Physical Keyboard` > Clicking on the device ... 
* ... to open `Physical keybioards` screen > Clicking the device again and a "Choose keyboard layout" popup appears
* ... which contains a button of "Set up keyboard layouts"

Going under there, various layouts for the physical keyboard are shown, and under them is written the name of the providing application. so, like;
* Android Keyboard (provides majority of the layouts)
* Gboard
* Lithuanian Layouts by ju...

This last one : [Lithuanian Layouts - Ext. Keyboards] i installed on my own via fdroid search with [hardware keyboard layout], and tried the layout provided by it, and it works.

[Lithuanian Layouts - Ext. Keyboards]: https://f-droid.org/packages/name.juodumas.ext_kbd_lithuanian
[hardware keyboard layout]: https://search.f-droid.org/?q=hardware+keyboard

So, i am wondering if u'd be interested in providing the layouts for the languages for which it doesn't exist in the default "Android keyboard"

**Comment by yashpalgoyal1304** [comment]
Annotated screenshot of the choose keyboard layout popup:

<img src="https://user-images.githubusercontent.com/19423063/185872076-c7bc6593-9462-4f3b-8093-69b04c24b191.png" height=300px>

**Comment by rkkr** [comment]
The answer will probably be "not to be a part of this application".

Physical keyboard layouts are stored differently and are different from Virtual layouts. So reusing any layouts currently inside the Simple Keyboard for a physical keyboard should not be technically possible.

A separate set of layouts could be bundled, but that inflates the size and is actually not related to the app. So if it ever happens, it would probably be a separate application, which already exists.

**Comment by yashpalgoyal1304** [comment]
> which already exists.

which one? i was only able to find these two on f-droid : one for lithuanian, and other one for bulgarian.

**Comment by yashpalgoyal1304** [comment]
hey, also, can it be done that the keypresses of the h/w keyboard be passed to some ime (input method editor) i.e. soft keyboard and processed further there??

like say, 
* i want to type in transliterate mode, and there exist some halfway decent transliterate ime-s already. 
* so, if i could somehow take the h/w keypresses and pipe them to that ime, then i would be able to directly transliterate 
* .... by using existing stuff rather than having to reinvent the wheel.

**Comment by rkkr** [comment]
Soft keyboard will probably not have access to physical keyboard events. AOSP keyboard even had code to prevent it from showing up if a physical keyboard is present.
