### ISSUE TITLE
Enter button has no enter or next sign

### ISSUE THREAD

**Issue by manfred-mueller** [rkkr/simple-keyboard#355]
After first start the 'enter' button either shows nothing or > or ->.
Is there any chance to change the button to always show the ⏎ symbol?

Thanks for your great little app!

**Comment by rkkr** [comment]
I have never seen this before. Which app does this happen in?

Also ">" is a valid Enter key case. This is used in forms where you can switch to next input field. You can run this app to see all the possible cases: https://github.com/rkkr/ime-tester

**Comment by manfred-mueller** [comment]
Thanks for your very speedy answer - much appreciated!
I have tested both simplekeyboard and aosp keyboard:
This sign gets shown with 'actionNone' with aosp and google keyboard
whereas there is no sign in simplekeyboard for 'actionNone'.

**Comment by rkkr** [comment]
What phone + OS version and Theme are you using?

**Comment by manfred-mueller** [comment]
I'm using an Allnet tablet with rk3399 and Android10 running my kiosk app.
simple-keyboard is configured with material-light theme.
![screenshot](https://user-images.githubusercontent.com/65389254/185892216-0a84bd8c-bbc7-4679-81d8-7193302e4c64.png)

**Comment by rkkr** [comment]
![image](https://user-images.githubusercontent.com/3480123/185974096-dbc2d46a-b429-4255-b5ed-f20cad54f654.png)

This is 10.1" emulator with Android 10 and first start after a force close of keyboard. White theme uses the same raster images and icon loading as AOSP keyboard so I have no idea why AOSP keyboard would work differently nor what is happening here.

If that only happens for the first load then this is likely some race condition or rendering optimization issue.

**Comment by rkkr** [comment]
Try a "System Default" theme. It uses vector icons which is more likely to have bugs but it's worth trying at this point.
