### ISSUE TITLE
click

### ISSUE THREAD

**Issue by cc6522992** [rkkr/simple-keyboard#360]
Add toolbar click event does not respond?

**Comment by rkkr** [comment]
There is no "add toolbar" button in the keyboard.

**Comment by cc6522992** [comment]
> 

I added a toolbar to the keyboard layout and put buttons in it, but there is no response when I click it

**Comment by rkkr** [comment]
If you modified the source code to include a toolbar then it's a bug you made :)

**Comment by cc6522992** [comment]
> 如果您修改了源代码以包含工具栏，那么这是您制造的错误:)

I just added a line above MainKeyboardView in the main_keyboard_frame file

**Comment by cc6522992** [comment]
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_gravity="bottom"
    android:orientation="vertical">

    
    <com.balilar.inputmethod.latin.suggestions.SuggestionStripView
        android:id="@+id/suggestion_strip_view"
        android:layout_width="match_parent"
        android:layout_height="40dp"
        android:background="@color/white"
        android:clickable="true"
        android:gravity="center_vertical"
        android:layoutDirection="ltr" />

    <com.balilar.inputmethod.keyboard.MainKeyboardView
        android:id="@+id/keyboard_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layoutDirection="ltr" />

</LinearLayout>
