### ISSUE TITLE
Add layout

### ISSUE THREAD

**Issue by cc6522992** [rkkr/simple-keyboard#361]
Hello, I want to add the layout of the Chinese keyboard in it, where should I add it?

**Comment by rkkr** [comment]
All the layouts are in https://github.com/rkkr/simple-keyboard/tree/master/app/src/main/res/xml

However you won't have much luck adding it as this is a fork of LatinIME where clicking a single key prints the single specified character. There is no mechanism of "combining characters into a single symbol".

**Comment by rkkr** [comment]
Register support for new language in https://github.com/rkkr/simple-keyboard/blob/24a5f6ff8f54885d39a5c76b22efb12a7c1df301/app/src/main/java/rkr/simplekeyboard/inputmethod/latin/utils/SubtypeLocaleUtils.java#L388 

and add the layout https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/xml/kbd_qwerty.xml

**Comment by cc6522992** [comment]
> 所有者

thanks
