### ISSUE TITLE
about key

### ISSUE THREAD

**Issue by cc6522992** [rkkr/simple-keyboard#363]
Hello, why does my special symbol key not have the switching function of the special symbol key after I use keySpec to set it to another text, but go directly to the screen? is there any solution

**Comment by rkkr** [comment]
https://github.com/rkkr/simple-keyboard/blob/2956432657ec26ca40635b3d6cc79cf7e5740498/app/src/main/java/rkr/simplekeyboard/inputmethod/latin/RichInputConnection.java#L471

You need to intercept your special KeyCode.

**Comment by cc6522992** [comment]
> 
I changed the shifi key position wen
