### ISSUE TITLE
style

### ISSUE THREAD

**Issue by cc6522992** [rkkr/simple-keyboard#365]
Can you set the image background for the separate key and the long-pressed preview window?

**Comment by rkkr** [comment]
Space key is an example of single key having different background: https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/drawable/btn_keyboard_spacebar_lxx_dark.xml

Preview window is defined in https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/drawable/keyboard_popup_panel_background_lxx_dark.xml and having two versions of it will probably be complicated. If you want the keys inside it to have icons, then it's the same as with all the action keys.
