### ISSUE TITLE
How to switch to kbd_phone layout

### ISSUE THREAD

**Issue by cc6522992** [rkkr/simple-keyboard#367]
How to switch to kbd_phone layout？

**Comment by rkkr** [comment]
It's only shown for `android:inputType="phone"` input type. You can test this in https://github.com/rkkr/ime-tester .

**Comment by cc6522992** [comment]
> 它仅针对`android:inputType="phone"`输入类型显示。您可以在https://github.com/rkkr/ime-tester中进行测试。

No, switch to kbd_phone from the function keys at the bottom, such as 123 number keys

**Comment by cc6522992** [comment]
> 在 key 上放一个断点`?123`，看看它是如何工作的。您将在那里找到配置的布局。
I can call setKeyboard in the code, but can I set it in the keyboard layout xml?

**Comment by rkkr** [comment]
Nope, you need a special key code + handler in service.
