### ISSUE TITLE
keyboard

### ISSUE THREAD

**Issue by cc6522992** [rkkr/simple-keyboard#368]
Why can't I switch symbolsShifted or other mode keyboards after setting the inputType property of EditText to number?

**Comment by rkkr** [comment]
Cause that text field only accepts numbers and so only numbers layout is shown?

**Comment by cc6522992** [comment]
> 因为该文本字段只接受数字，所以只显示数字布局？

I set android:inputType="number" to test, but some other keyboards seem to be switchable. I customized a nine-key and then I want to switch to symbolsShifted, but I can't switch.

**Comment by rkkr** [comment]
Just adding the layout switch button won't work. As I remember only supported layout options are loaded for an input field, in this case "number type" only supports the "number layout", so there is no other layout to switch to.

You should be able to find that in debugger.

**Comment by cc6522992** [comment]
> 

Can you tell me where is that code where "Number Type" only supports "Number Layout"? I'll try to modify it

**Comment by rkkr** [comment]
Also please stop filling issues for your own project support. https://github.com/rkkr/simple-keyboard/discussions/categories/q-a is a better place.

**Comment by cc6522992** [comment]
> 



> 也请停止为您自己的项目支持填写问题。[https://github.com/rkkr/simple-keyboard/discussions/categories/qa](https://github.com/rkkr/simple-keyboard/discussions/categories/q-a)是一个更好的地方。

ok thanks
