### ISSUE TITLE
make it fast ^_^

### ISSUE THREAD

**Issue by xi7** [rkkr/simple-keyboard#372]
https://user-images.githubusercontent.com/67331785/196405546-452227a8-5a78-41cd-8e24-f16d3ef0abe6.mp4

replace slow hold key to swipe up key

and A X C V = select all - cut - copy - past   .... using swipe down.

**Comment by rkkr** [comment]
There is more than one character in the long-press menu so it won't work as shown. As of now you can swipe thru the keys and it just moves thru the keys (which isn't very useful).

**Comment by xi7** [comment]
you can keep hold but swipe up will show what is on the key.

**Comment by xi7** [comment]
moves thru the keys is unnecessary

**Comment by xi7** [comment]
plz decrease the horizontal/vertical `gap`  - file fractions.xml  to 1.0%p also landscape.

**Comment by xi7** [comment]
https://user-images.githubusercontent.com/67331785/196745029-720550b9-5632-49df-b634-079842d43620.mp4
