### ISSUE TITLE
Trojan ?

### ISSUE THREAD

**Issue by mariush444** [rkkr/simple-keyboard#378]
Starting with version 96 the virustotal.com (foritnet) reports that apk contains trojan.

[virustotal](https://www.virustotal.com/gui/file/7f739bf5230f96451718d316e38fdd077cea2705fd1a14a7add52411da3cdfec)

[fortinet](https://www.fortiguard.com/search?q=Android%2FGeneric.S.566031%21tr)

**Comment by licaon-kter** [comment]
Do report this false positive to Fortinet then. Generic description feels like FUD, meh

**Comment by rkkr** [comment]
This isn't a first time. Majority of key loggers are probably made out of LatinIME forks. Both my local and FDroid builds are flagged so it's not like both were hacked simultaneously.

Malware is found in the `classes.dex` file so it's the Java code being flagged. Here are the changes that supposedly caused it: https://github.com/rkkr/simple-keyboard/compare/95...96 . Permissions are not changed, so any bundled malware would be useless.

**Comment by mariush444** [comment]
I contacted with Fortinet. The response is below.

```
Dear Customer,

Thank you for bringing this issue to our attention.
We have noted a False Positive detection on the file with SHA256:<7f739bf5230f96451718d316e38fdd077cea2705fd1a14a7add52411da3cdfec>.
The signature "<Android/Generic.S.566031!tr>" will be disabled, and changes will be reflected in the next Virus Signature update.

We sincerely regret any inconvenience this might have caused you. 
Please rest assured that we take pride in the quality of our service and product, and rare instances like this occur due to the complexity of file structures.
We're sorry for any inconveniences this may have caused and please let us know if you are still receiving alerts after the update.
If you have further concerns, please do send us a mail and we will immediately assist you.

Regards,
AV Lab - Ruize Ma

To submit a suspicious file to Fortinet: 
fortiguard.com/faq/onlinescanner || submitvirus@fortinet.com
```
