### ISSUE TITLE
how to use the additional number row per default

### ISSUE THREAD

**Issue by slodown** [rkkr/simple-keyboard#379]
Hello,
any idea how to enable the number row as default.
Where to change and how to rebuild the APK?
For my purpose also a SEND INTENT command would be enough.
Would appreciate any help.
Best regards
Slo

**Comment by rkkr** [comment]
https://github.com/rkkr/simple-keyboard/blob/5025d9a0a0d42cb2218e7726aef3ec3a7be9f880/app/src/main/java/rkr/simplekeyboard/inputmethod/latin/settings/Settings.java#L150

This shouldn't be so hard to find. May need to also update the UI to show default value but that is also not hard to find.
