### ISSUE TITLE
use as system app

### ISSUE THREAD

**Issue by bolbolfolfol** [rkkr/simple-keyboard#388]
Hi
i tried puting the apk folder in all app folders
system/app
system/priv-app
product/app
product/priv-app

but i can't enable it in language settings
i think it need a permission xml
any idea ?
and thank you

**Comment by rkkr** [comment]
What do you want to achieve with that?

**Comment by bolbolfolfol** [comment]
> What do you want to achieve with that?

remove the default aosp keyboard and use simple keyboard as default

**Comment by rkkr** [comment]
If you don't have a system level encryption (where password is requested before phone boots) you don't need to have a "system keyboard". And if you have a system level encryption you can just leave the system keyboard disabled.

**Comment by rkkr** [comment]
So just install from play store (or directly apk as a user app), enable it and then just remove the system one. I don't see why this shouldn't work.
