### ISSUE TITLE
Add New Row

### ISSUE THREAD

**Issue by shelar264** [rkkr/simple-keyboard#391]
i am trying to add new row in keyboard like attached image (like attach image 2) Translate, GIF, etc. But last row is hiding inside the navigation bar. (as image 1) please help me out.

![1](https://user-images.githubusercontent.com/126065184/220585340-36b8149c-ece8-4cf5-8082-aabf68b356a3.jpeg)
![2](https://user-images.githubusercontent.com/126065184/220585346-927013b8-62e4-4c7a-8e45-8817b2b64163.jpeg)

**Comment by rkkr** [comment]
You have to recalculate the keyboard and row heights to fit them into the area. Look at the code that adds the number row.
