### ISSUE TITLE
Backspace key doesn't work in numeric field

### ISSUE THREAD

**Issue by crashlyrics** [rkkr/simple-keyboard#396]
Backspace key doesn't work in the numeric field of my online bank account when I want to fill in (and e.g. correct) an amount for a transaction. There's also no comma available as decimal separator :(

**Comment by rkkr** [comment]
Write a bug for your bank for backspace.

As for seperators all number fields have both "," and ".", so it's weird.

**Comment by crashlyrics** [comment]
With Simple Keyboard from Tibo Kaputa it works. This one also allows to use comma OR dot with no problem. Just wanted to let you know cause your keyboard has some other good features I like.

**Comment by crashlyrics** [comment]
Great! Works now, thank you!
