### ISSUE TITLE
What makes this keyboard stand out from AOSP?

### ISSUE THREAD

**Issue by RockyTV** [rkkr/simple-keyboard#40]
What features does this keyboard have that separate it from AOSP? It looks like the standard AOSP with a few design tweaks, nothing else.

**Comment by licaon-kter** [comment]
Where does one get that AOSP keyboard? Link please...

**Comment by rkkr** [comment]
No one claims that it is anything more than a fork of AOSP. I have linked the original LatinIME repo in the readme and given my source, thou I'm not obliged to do that under Apache license.

The features that are added are custom height, custom background, special characters, number row, transparent buttons, space swipe and most importantly size of 820KB (compared to ~24MB), which required removal of many features that were originally in AOSP. All that is described in play store listing.
