### ISSUE TITLE
Button icon change based on state ( Help needed )

### ISSUE THREAD

**Issue by vivasvan1** [rkkr/simple-keyboard#406]
Hi there @rkkr,

I am working on a fork of simple-keyboard. 

I want to display button icon based on some state but I am not able to see switching icon can be implemented.

I am trying to do it in MoreKeysKeyboardView but the icon doesn't seem to update at all.

For example:

When state is fried and baked: show icon A
When state is fried and not baked: show icon B
When state is not fried and baked: show icon C
When state is not fried and not baked: show icon D

How do i switch the icon based on some state? And what file is the relevant code in?

I am stuck on this from few days. Appreciate it if you could guide me.

P.S. : https://stackoverflow.com/questions/4336060/how-to-add-a-custom-button-state

**Comment by rkkr** [comment]
Shift key is probably the best example. This could be your starting point: https://github.com/search?q=repo%3Arkkr%2Fsimple-keyboard+shift_key_shifted&type=code

**Comment by vivasvan1** [comment]
Context:

I am working on adding chatgpt to the keyboard so user can run any query without leaving the app.

I want to update the same button/key to shown GENERATING and LOGIN. 


![IMG_20230612_012518.jpg](https://github.com/rkkr/simple-keyboard/assets/21074796/e73015dc-7125-45b9-bf13-399af1b451d8)

**Comment by vivasvan1** [comment]
> Shift key is probably the best example. This could be your starting point: https://github.com/search?q=repo%3Arkkr%2Fsimple-keyboard+shift_key_shifted&type=code

ok looking into this

**Comment by rkkr** [comment]
If you're adding a widget on top then I think you should just add a frame above the keyboard frame in https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/layout/main_keyboard_frame.xml . Then use default android UI elements to make you UI. The keys are drawn on-the-fly, so it's better to just leave the keys there. The word suggestion bar in LatinIME is a separate frame: https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/master/java/res/layout/main_keyboard_frame.xml

**Comment by vivasvan1** [comment]
Sorry for the idiot question. I am new to android.

So if i implement as new Frame like you suggest. Where can i write my code for onClick of that button?

Thanks

**Comment by vivasvan1** [comment]
I have already got the key thing working but i would like to take your suggesion and implement it as you recommend.
