### ISSUE TITLE
about Swipe Navigation

### ISSUE THREAD

**Issue by Laicure** [rkkr/simple-keyboard#41]
Thanks for the swipe navigation, loved it!

But there's a bit of inconvenience regarding the swipe activation.
- it activates so fast that the whitespace forgots to trigger itself making itnotproducespaces. (prominent if you type fast)
- also, there is a playstore suggestion to have a toggle to just leave the left/right buttons as is or use the swipe navigation

Also, if u have a google play app for donation (not via paypal please), I would love to donate for your great work, thanks!

**Comment by rkkr** [comment]
I'll tweak the sensetivity a bit in the next release. The space is not inserted only if the pointer was moved, so it can't just not add spaces. The option to disable swipe will be added.

The navigation buttons are not coming back. It was too much of a hack and took too much space in the screen. In some languages there wasn't even space for them.

**Comment by Laicure** [comment]
point 1: yes I'll wait for that, thank you! ;)

point 2: oh I see, no worries here ;)

I'll close this one now :D

**Comment by Laicure** [comment]
Hello again!

Thanks for the quick resolution regarding the initial swipe delay.

Anyway, the initial delay seems fast and the swipe still triggers fast.
What about making it use the "Key long press delay" instead?
The user configurable delay is better than making it hard-coded, right?

**Comment by Laicure** [comment]
Oh, I didn't know those (only using English).
/hmm let me rethink that part.
I thought you have added a swipe delay.
It is just bothering it triggers a _tab_ like function when the cursor is at the end of the line (end of typing).

**Comment by rkkr** [comment]
If it steps out of the edit field, then it's a totally unrelated issue. Arrow keys did the same. There are two methods to change cursor position:
1. Asking an application to return the current cursor index, and then asking an application to set the new index. This prevents pointer jumping out of the focused field as only index would be changed. This works well on applications that use standard Edit field. Anything custom (snapchat, word, facebook, pretty much anything that can have a non character) doesn't work as apps can't properly handle indexes and swiping in them makes the pointer jump randomly. The first beta version used this.
2. Simulating left/right arrows. Navigation buttons used this. All custom apps seem to handle this properly, except when they think that you have a physical keyboard and tried to move between UI elements using arrows.

I haven't found a third option.

**Comment by Laicure** [comment]
Ah, I see,
1 app that I know that doesn't feed on the swipe navigation is Skype's text field.
I am using Firefox, Chrome, and even Samsung Browser when I encountered the _stepping out of text field_ thing.

It only jumps out when the cursor reaches the end of a text field's string (and you keep on swiping to the right) and nothing else.

If it can't be somehow be amended by any means, I'll just not bother with it ;)
Thanks for the quick responses! 😁 
We can close or just keep open this one.
