### ISSUE TITLE
Feature request: Add forward slash as a long press option for M

### ISSUE THREAD

**Issue by reportingissue** [rkkr/simple-keyboard#418]
Currently, the alternate for M in the english qwerty layout contains the question mark (?). On US qwerty keyboards, shift+/ is the question mark. It would be great to have the slash as a long press on the M key as well.

There are multiple use cases to having the slash accessible on the main keyboard:
- typing http urls and endpoints
- describing mutually exclusive but similar options ("we can go to a pub/bar/coffeeshop")

In fact, I would argue that the forward slash is more used than the pipe and backward slash on a day to day, but I am comfortable where those are currently.

edit: I just notice that it does exist in the severely overloaded period (.) long press. If it is not desired to put it as an alternate to the (M) key, re-ordering the period long press panel to have the forward slash closer would be nice, as it is the only character that does not have a dedicated main key on the qwerty layout.

Thank you for the consideration

**Comment by rkkr** [comment]
Just long-press "."?

**Comment by reportingissue** [comment]
> Just long-press "."?

Yes that is what I shall do, there is only the inconvenience that for some reason it has all the other characters. The "." is at the right, while "/" is all the way to the left making the swipe gesture a bit long.

I actually don't mind it that much anymore (this issue can be closed), but I think that either the long press character list for "." should be reordered so that "/" will be at least in the right half of the screen or some characters should be removed from said list, because they are available as long presses on the other characters. I poked a bit in the code and I think that the first option might be easier because it seems like you are compositing layouts together ("xml_qwerty0", "xml_qwerty1", etc...), although I haven't found the place where the "." long presses are defined yet.
