### ISSUE TITLE
Documentation for creating new layout

### ISSUE THREAD

**Issue by MiskolcziRichard** [rkkr/simple-keyboard#425]
I want to have an Old Hungarian Script keyboard. Since literally nobody uses this layout, I would be mad to ask somebody to create it for me. So I decided to just create it, and contribute to the project with it.
One small problem: I have no idea how to achieve this. I am open to learning the process, but there seems to be insufficient documentation that could lead me in the right path.

I would really appreciate a documentation about creating a new layout.

**Comment by rkkr** [comment]
Just use existing code or PRs as example: https://github.com/rkkr/simple-keyboard/pull/362 . However it's not likelly for a contribution that "literally nobody uses" to be accepted. But you're welcome to have a fork.
