### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by tz-shuhag** [rkkr/simple-keyboard#427]
Can add add 3 more basic features of an keyboard namely - Emoji (Not Gif) & Text prediction and Clipboard ?

I know that would definetly make it a bit heavier app but in this era these features are must have for any keyboard app.

I would be delighted to have these features. Hoping you will do something. You did a great job man.

**Comment by nairu777** [comment]
The About says it probrably wont ever going to have this

**Comment by uli-on** [comment]
@tz-shuhag, have you considered using OpenBoard?
https://github.com/dslul/openboard

**Comment by tz-shuhag** [comment]
> @tz-shuhag, have you considered using OpenBoard?
> https://github.com/dslul/openboard

Yes bro , I am alrwady using it and it performs great for me .

**Comment by rkkr** [comment]
First two not happening, third doesn't have space in UI and all are duplicates.
