### ISSUE TITLE
InputMethodService Api VS LatinIME. - (Q&A)

### ISSUE THREAD

**Issue by degits** [rkkr/simple-keyboard#428]
This keyboard is created by cloning the whole AOSP keyboard project (LatinIME).
What is the reason for creating a keyboard from scratch (like this) instead of extending InputMethodService as explained in Android dev docs?

Are there any advantages of using LatinIME over InputMethodService API?

**Comment by rkkr** [comment]
LatinIME is extending InputMethodService:
https://github.com/rkkr/simple-keyboard/blob/8fb4c33e1abab55c8d21d7e349fb9f97db40cebb/app/src/main/java/rkr/simplekeyboard/inputmethod/latin/LatinIME.java#L76
.

If you followed the tutorial from Android dev docs and implemented a full
fledged keyboard, you could arrive at a similar code as just cloning
LatinIME. Majority of open source keyboards are forks of LatinIME just
because it's easier to modify an existing app than start from scratch.

**Comment by degits** [comment]
Thanks Raimondas,

However, some of the open-source keyboards have a small amount of code related to keyboard implementation when compared to LatinIME.
Ex: 
Simple keyboard by Tibbi. 
- https://github.com/SimpleMobileTools/Simple-Keyboard
- **Extending class of InputMethodService (called SimpleKeyboardIME) + KeyboardView** (called MyKeyboardView) and its XML layouts.
- Working without issues.
- Easy to customize the source code

I can fully understand the above keyboard (Tibbi's) source code but it's very hard to understand the LatinIME source code (or your keyboard). Even I can't figure out some parts of it. That's why I tried to make my own custom keyboard based on the above keyboard implementation.

Is the above keyboard (tibbi's), not a full-fledged keyboard? or It missed some fundamental implementations.

**Comment by rkkr** [comment]
I also have https://github.com/rkkr/tiny-keyboard

Most of the code in LatinIME is there for a reason. LatinIME has loads more functionality than those minimal (SimpleMobileTools included) implementations. I won't argue that it's coded in a clear way, I've been cleaning it up for a long time now. If you'd dig thru the rest of AOSP code it's the same spaghetti mess. You can complain to Google about that.

Also if SimpleMobileTools uses [KeyboardView](https://developer.android.com/reference/android/inputmethodservice/KeyboardView), I have bad news for him: `This class was deprecated in API level 29.` Google says keyboards must implement ALL the rendering and events logic in their own code, meaning LatinIME quantity.
