### ISSUE TITLE
Compile w/ Proguard

### ISSUE THREAD

**Issue by Eddi2015** [rkkr/simple-keyboard#43]
I'm not sure if you're already doing this, but the apk size can be reduced even more by compiling it with proguard (https://sourceforge.net/projects/proguard/) Thanks in advance.

**Comment by rkkr** [comment]
Enabled at: 
https://github.com/rkkr/simple-keyboard/blob/bc1ccf25c7278387b116e63e13057d6ae6b4e4e5/app/build.gradle#L15
