### ISSUE TITLE
Заметки \ Notes

### ISSUE THREAD

**Issue by al8a7** [rkkr/simple-keyboard#433]
Добавьте возможность создавать заметки. Телефон почти всегда под рукой, было бы круто создавать заметки на экране блокировке. \ Add the ability to create notes. The phone is almost always at hand, it would be cool to create notes on the lock screen.

**Comment by rkkr** [comment]
Not happening. You need a note app that provides a lockscreen widget. Any keybaord would be able to type into it. However lockscreen widgets are deprecated a long time ago. Only other option is notifications, but that is still a note app feature.
