### ISSUE TITLE
Show euro sign € as keyspec currency doesn't work

### ISSUE THREAD

**Issue by soshial** [rkkr/simple-keyboard#435]
GBoard shows Euro € in layouts with European languages as a default currency. This doesn't work in Simple Keyboard.

The XML settings `res/xml/key_styles_currency.xml` also don't fix this.

<img width="946" alt="Screenshot 2024-01-16 at 11 15 10" src="https://github.com/rkkr/simple-keyboard/assets/100644/b6cbb090-bf2b-403e-8387-c01e15662476">

**Comment by rkkr** [comment]
Well it's working as designed. This XML is for "key style" so it's only used in "?123" layout and "additional row" as a currency "key" (not "key hint"). € is properly shown there for these languages. As this layout is generic for all languages, this currency key style was created.

These XMLs are probably not reusable as they define a whole key, you can't put them in a `keyHintLabel` property. I'd say it's not even worth trying to reuse them as € `keyHintLabel` can just be put in the language specific `rowkeys_2.xml`.
