### ISSUE TITLE
Active development

### ISSUE THREAD

**Issue by mjdNjhNJ** [rkkr/simple-keyboard#439]
Is this project still under the active development or should we move to an alternative?

Latest release and merged PR is from Octrober last year.

**Comment by rkkr** [comment]
It's not abandoned. I upgrade SDKs (with support for new Android versions) and implement any new Play Store requirements so it can be called "maintained".

I also accept PRs with features that fit and are properly implemented. I'm not actively adding new features as it's "feature complete" from my point of view.
