### ISSUE TITLE
[App-request] Simple Launcher

### ISSUE THREAD

**Issue by Eddi2015** [rkkr/simple-keyboard#44]
Please compile the Aosp Launcher (or trebuchet is even better; Catapult is outdated) for F-Droid. I'd like to use that Launcher on Android 4.4.2. Thanks in advance :)

**Comment by rkkr** [comment]
Not even related to current application

**Comment by Eddi2015** [comment]
I know that but as I said that's a request. I couldn't find any other way of contacting you.
