### ISSUE TITLE
Add compatibility with remote tv

### ISSUE THREAD

**Issue by akrram0** [rkkr/simple-keyboard#442]
I have an old smart tv (android 4) and I love that keyboard is lightweight and fonction perfectly, but I can't control it using remote tv, can you add compatibility with remote tv

**Comment by rkkr** [comment]
Not going to happen. You can't even install it newer Google TVs. Also unassisted inputs don't fit well into such limited input capabilities so "simple keyboards" are not very usable with a remote.
