### ISSUE TITLE
Hide the open settings button on the locked screen

### ISSUE THREAD

**Issue by Artem13327** [rkkr/simple-keyboard#445]

**Comment by rkkr** [comment]
Should be added in 89e89c4922b05ac2e5573f13a65461675e89a52b and available for testing in https://github.com/rkkr/simple-keyboard/releases/tag/103 .

Interestingly LatinIME originally uses https://developer.android.com/reference/android/os/UserManager#isUserUnlocked(android.os.UserHandle) which only disables the settings key on the first unlock during boot. https://developer.android.com/reference/android/app/KeyguardManager#isKeyguardLocked() seems to work better.
