### ISSUE TITLE
Frequently Asked Question (FAQ) Proposal 

### ISSUE THREAD

**Issue by olayhemy** [rkkr/simple-keyboard#45]
Hello there, I'd like to contribute to your awesome project by writing a Frequent Asked Questions for users self-service. Would love to hear from you, thanks.

**Comment by licaon-kter** [comment]
What's the deal exactly? What do you gain form this?

Ref: https://github.com/brarcher/video-transcoder/issues/117

**Comment by olayhemy** [comment]
Hey! I’m writing FAQ for that project at the moment. I wish to write for yours too if you want. You can just tell me if you don’t need it then I will close the issue. Thanks

**Comment by rkkr** [comment]
Play store description and Readme.md should be sufficient.
