### ISSUE TITLE
Link to translation platform directly in-app

### ISSUE THREAD

**Issue by Cwpute** [rkkr/simple-keyboard#454]
So that future contributors know translating the app is a possibility, and how to do it.
It could be included in the suggested About page #131 so as to not cluter the main menu.

**Comment by rkkr** [comment]
I'd rather put the source code link. I'd prefer that people not knowing how to do it wouldn't even know about it. Some translations are bad enough already.

**Comment by Cwpute** [comment]
Strange way of thinking.
How should competent translators know they can help, if you don't ask for it, and if you don't provide ways for them to do it easily ? We are not all familiar with Github, we are not all developers, some of us don't even know what a repository is ! Providing a single link to the repository will only help developers, not translators.

Plus, a bad translation is a translation nonetheless, and it drives competent people to contribute better translations 😉

Le 1 juillet 2024 08:48:45 GMT+02:00, Raimondas Rimkus ***@***.***> a écrit :
