### ISSUE TITLE
Any way to thank dev by pay/donate??

### ISSUE THREAD

**Issue by geesquer4u** [rkkr/simple-keyboard#465]
Thank you. I was using your keyboard for an year. Now I want to try indic keyboard from fdroid. But before leaving, I want to say thanks & seeing if anyway to do a donation/payment.

Also kindly make the setting to hide the app icon from drawer. Gboard can do it but google says other apps should not do that! Atleast in fdroid version give the option so non-pixel many users can use it

**Comment by rkkr** [comment]
Donation link removed when this started happening: https://www.reddit.com/r/programming/comments/p3qysj/opensource_app_removed_from_the_google_play_store/

For hiding icon just use a custom launcher like https://github.com/lawnchairlauncher/lawnchair

**Comment by rkkr** [comment]
Never had such issues.

**Comment by geesquer4u** [comment]
Mine is vivo phone with latest hardware. It actually not works well in any third party launcher. The recent/open/minimized apps bringing gesture or "square button" at bottom is not giving smooth animations. Its feeling like dropping to 20hz smoothness (that much hang).
