### ISSUE TITLE
Please add the option to enable clipboard in this wonderful keyboard.

### ISSUE THREAD

**Issue by RedstoHack** [rkkr/simple-keyboard#466]
Please add the ability to work with the clipboard to this wonderful keyboard. The clipboard is very important for many users. Its icon could be placed to the right or left of the top panel, and so that this panel can be disabled
in the settings.

This keyboard is at a very high level, but it can be raised even higher :)

**Comment by HanzoDev1375** [comment]
and add number line to lang farsi/:

**Comment by LtqxWYEG** [comment]
I second this notion! *lifts hammer* "Bam! Bam! Bam!"

**Comment by RedstoHack** [comment]
rkkr, please add a menu to work with the clipboard. I think if you do this, it will be one of the best keyboard updates! Since there are a lot of users who have asked for it

**Comment by rkkr** [comment]
#338 as noted in there isn't a good place for it in UI.

**Comment by LtqxWYEG** [comment]
> rkkr, please add a menu to work with the clipboard. I think if you do this, it will be one of the best keyboard updates! Since there are a lot of users who have asked for it

Three isn't quite a lot. :D

But hey, thanks rkkr! You're the best!

**Comment by LtqxWYEG** [comment]
> #338 as noted in there isn't a good place for it in UI.

Just three entries under the comma would be enough, really. No need to see them all the time.
If you put "paste" as the first option chosen after a long press, then it would also fix my current issue with accidentially opening the options menu. (Because it's new more than anything, but hey.)

**Comment by RedstoHack** [comment]
rkkr,

If a suitable location is found, will you add a clipboard menu?
