### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by HanzoDev1375** [rkkr/simple-keyboard#467]
hi can you using androidx and google material?

**Comment by rkkr** [comment]
1. Bringing in any google dependency bloats the app size. Even adding an appcompat and not referencing any dependency adds ~2MBs (should be 0MBs as minifyer excludes all unused code and resources).
2. The keys layout itself (not settings) are rendered directly into canvas using bitmaps and vectors (LatinIME probably did this to improve performance). UI libs are not usable.

**Comment by rkkr** [comment]
If you're talking about Settings then yes as it doesn't play nice with Android 15 edge-to-edge. I didn't rush changing it cause I want to see how LineageOS or someone else will solve this.

**Comment by HanzoDev1375** [comment]
> If you're talking about Settings then yes as it doesn't play nice with Android 15 edge-to-edge. I didn't rush changing it cause I want to see how LineageOS or someone else will solve this.

To fix the edge to edge bye problem, get help from androidx or at least activity because you are using prefence activity that's why it doesn't work
dont using #PreferenceActivity using #Activity

**Comment by rkkr** [comment]
It's not as simple as just renaming `PreferenceActivity` to `Activity` :) . You need to define your own view, action bar and navigation between screens cause it's a plain Activity.  All that would still use the deprecated `PreferenceFragment` so it would still be a hack that may break on next release.

And an AndroidX Preference lib would at least double the app size just for the settings page look. So to now invent something I'll wait to see how LineageOS will handle all this.

**Comment by HanzoDev1375** [comment]
now my mobile is poco x5 and the app view is good but the speed is drastically slow

The size of the program does not matter at all, it is important to operate fast and smooth. I know a lot of keyboards that have a size of 140 MB, but they have high speed.


see image

`
![Screenshot_2024-09-16-14-50-36-193_com itsaky androidide](https://github.com/user-attachments/assets/cd0caab9-6c75-4664-b41d-3cc2976a3645)
`

**Comment by rkkr** [comment]
Preference screen has 0 impact on keyboard view and performance. AndroidX Preferences can't be faster than native PreferenceActivity.

If your complaint is performance then there are two aspects:
1. Cold start time and cold start frequency. App size has great impact on this especially in scenarios with memory pressure like games. 
2. Responsiveness of key inputs. If you click a key and the app you're typing into freezes there's not much a keyboard can do. The other side of this aspect is if this also freezes the keyboard. In case of LatimIME it will also freeze the input keyboard as it waits for pointer index and surrounding text updates to sync shift key and delete capabilities. Closed source keyboards probably do something smarter. Rewriting this part would end up in a complete app rewrite as this as this is just one of many crappy implementations within AOSP. I have no intention of doing that.
