### ISSUE TITLE
[Request] emoji keyboard layout

### ISSUE THREAD

**Issue by idekovets** [rkkr/simple-keyboard#47]
Need emoji keyboard layout like on Ubuntu Touch or Sailfish OS. (No button).

Sample: https://openrepos.net/sites/default/files/packages/1221/screenshot-emojikeyboardset1page1.jpg

Best regards.

**Comment by idekovets** [comment]
That not duplicate: button allways visible on keyboard, keyboard layout i can disable if needed.0:21, 14 августа 2018 г., "Licaon_Kter" <notifications@github.com>:/close as duplicate of #13

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail

**Comment by rkkr** [comment]
The duplicate part is "Emojis were removed intentionally and I don't plan to add them back".

**Comment by idekovets** [comment]
Thanks, i understand.8:12, 14 августа 2018 г., Raimondas <notifications@github.com>:The duplicate part is "Emojis were removed intentionally and I don't plan to add them back".

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

Отправлено из мобильной Яндекс.Почты: http://m.ya.ru/ymail
