### ISSUE TITLE
Android 15 - Keyboard is displayed under the navigation bar 

### ISSUE THREAD

**Issue by massager1617** [rkkr/simple-keyboard#471]
![Screenshot_20241017-232813](https://github.com/user-attachments/assets/26b80ba3-1448-4db1-9924-44724d809995)

Some time after a reboot the keyboard starts getting rendered below the navigation bar(comma and space bar getting obstructed as per the screenshot attached).
The problem seems to go away temporarely after a restart but reappears after a few minutes. 

Running versions 5.20 from Fdroid on a Pixel 8 with Android 15.

**Comment by rkkr** [comment]
This being "after a few minutes" is going to be fun. My pixel isn't getting 15 and this doesn't seem to happen in emulator. Care to test and idea? If this isn't it then it's an Android bug that will need to be worked around.
[app-release.zip](https://github.com/user-attachments/files/17428568/app-release.zip)

**Comment by massager1617** [comment]
Increasing the bottom offset in "appearence" to 15 dp or higher in my case seems to bring the keyboard layout above the navigation bar making the keyboard usable again.

**Comment by rkkr** [comment]
That would still shift the keyboard up and down randomly so it's not a proper workaround. Try out the attached apk. You'll need to reinstall as it's signed with play store cert.

**Comment by massager1617** [comment]
The bug happens with the Play Store apk too. After enabling it for 40 or so minutes, when I tried to input a search query in Brave browser the bug reappeared.
I have been trying to find a consistent method of replicating it but no luck so far.
Disabling and enabling the app again temporarely fixes the issue.

**Comment by massager1617** [comment]
https://github.com/user-attachments/assets/6523119d-b443-4952-b3c5-c8b30ac88219

Finally found a way to consistently reproduce this. It seems to happen when entering landscape mode in video players (newpipe, youtube web) by pressing the full screen button or by rotating the screen.

Steps to reproduce(as in video attached):
1. Confirm the keyboard is displaying properly
2. Switch to a video player(tested in newpipe and youtube web interface in brave browser)
3. Go full screen by tapping the button or by rotating the screen
4. Quit fullscreen or switch apps(bug still happens wheter you switch apps or you exit fullscreen first)
5. Confirm that the keyboard is displayed under nav bar

Simply rotating the screen outside a video player does not trigger the bug. In my testing there must be a video that goes full screen.
Could not reproduce with Gboard.

**Comment by rkkr** [comment]
This reproduces in youtube app in emulator. The issue is that when screen is rotated the View is recreated, but the View callback to set navbar height is not reinvoked, hence the 0 padding. Sounds like and Android bug. The workaround is to simply persist the last known navbar height between Views. Try the attached apk.

[app-release.zip](https://github.com/user-attachments/files/17439050/app-release.zip)

**Comment by massager1617** [comment]
The fix is working flawlessly! Thank you so much for your time and work!

**Comment by rkkr** [comment]
2382af925fc398f10152ba83f4516b02ad69c6d1 is in 5.21
