### ISSUE TITLE
Negative keyboard bottom offset issue

### ISSUE THREAD

**Issue by mctest389** [rkkr/simple-keyboard#473]
The keyboard regularly "slides down", as if the bottom offset was set to a negative value, despite it being consistently set to 0.
It then overlaps with the system UI buttons, such as the one for switching the keyboard.
<img src="https://github.com/user-attachments/assets/7ae6c64f-7554-4081-bcfb-daf2cbbbbf97" width=25% height=25%>
The issue can be temporarily fixed by switching to a different keyboard and back to this one, however it starts to occur again after a while.
For reference, this is what the keyboard looks like when working correctly:
<img src="https://github.com/user-attachments/assets/0d080891-e413-4fc1-af29-f4e9e1114757" width=25% height=25%>
I'm using the latest version of Graphene OS (Android 15) and version 5.20 of Simple Keyboard. Any ideas on what might be causing this?

**Comment by rkkr** [comment]
#471
