### ISSUE TITLE
Input stopped working after the last update

### ISSUE THREAD

**Issue by VadosG** [rkkr/simple-keyboard#482]
After updating to version 5.22 input stopped working, tested on two ZTE phones with Android 13.

https://github.com/user-attachments/assets/e4f55f39-4912-414a-ab8b-63191c7707d7

**Comment by rkkr** [comment]
Logs would be good as videos don't help. Input logic wasn't changed in that version so it's also strange.

**Comment by VadosG** [comment]
Found it! It appears after **disabling** the first option:

![Screenshot_20241218_193150](https://github.com/user-attachments/assets/503f0720-bc8b-4b81-a3fc-594f68e0a57d)

**Comment by rkkr** [comment]
That is in scope of last changes and did reproduce locally in Pixel.

**Comment by rkkr** [comment]
4898a23c6574a3efd927b7e27d2adc7168c6a9d0 seems to fix. Connection handling is really weird and was set by the capitalizer logic. You can try this: [app-release.zip](https://github.com/user-attachments/files/18187154/app-release.zip)

**Comment by VadosG** [comment]
Fixed

**Comment by TheRealOne78** [comment]
@rkkr please add the new version on F-Droid

**Comment by rkkr** [comment]
F-droid is automagic. It will eventually pick up.
