### ISSUE TITLE
Question: "Attention" - Popup?

### ISSUE THREAD

**Issue by 0pLuS0** [rkkr/simple-keyboard#54]
Hello,

So I'm looking at this as an Open Source project, and trying to understand why you have the popup message about data collection?

This is not the thing someone should be seeing coming from an Open Source Project that respects privacy, because a simple app, without any backdoor in it, can't collect data, so therefore, what's the point of the message, my comments are rhetorical.

So now, you're scaring newbies, and this isn't what you want to be doing.

So you might want to delete this message in your next release.

Also please explain, why you put this there in the first place?

Thanks

![simple](https://user-images.githubusercontent.com/36190223/46270616-f63f0b00-c537-11e8-92a5-eb36ed3a7b02.jpg)

**Comment by licaon-kter** [comment]
Isn't this a standard message you get with ANY keyboard?

**Comment by 0pLuS0** [comment]
Yeah my stupidity I see it happens for all...

Hey I don't go around that often playing with these... LOL
