### ISSUE TITLE
Layout is not changing

### ISSUE THREAD

**Issue by BananchickPasha** [rkkr/simple-keyboard#60]
![photo_2018-10-22_22-23-57](https://user-images.githubusercontent.com/17815520/47313995-12226200-d649-11e8-992c-276b72182d29.jpg)

**Comment by licaon-kter** [comment]
Seeing the same too. Non latin languages (arabic، russian etc) end up as qwerty

**Comment by rkkr** [comment]
Fixed in 2.19.
