### ISSUE TITLE
html tel input force close

### ISSUE THREAD

**Issue by JonnyTech** [rkkr/simple-keyboard#61]
Browse to a page with a html `tel` input. Press the button labelled `*#`. Simple keyboard crashes every time. Page with example input: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_input_type_tel

**Comment by rkkr** [comment]
Fix pushed

**Comment by licaon-kter** [comment]
Pushed where? 

Fyi F-Droid already built version 45

**Comment by rkkr** [comment]
Play store, will push a commit today in the evening :)

**Comment by JonnyTech** [comment]
Confirmed working from F-droid (v3.1), thank you very much.
