### ISSUE TITLE
The "x" character changed to some weird version of "j" after today's upgrade to v3.1

### ISSUE THREAD

**Issue by pitsi** [rkkr/simple-keyboard#62]
Dear developer.

As seen on the screenshot below, the "x" character on the qwerty layout has changed to a weird "j+^" one on the qwerty layout of the keyboard after today's upgrade to v3.1

![screenshot_20181026-210143](https://user-images.githubusercontent.com/5880037/47584513-64be8f80-d963-11e8-8341-5d8a37731d86.png)

Nokia 5, android 8.1, simple keyboard 3.1 and plain qwerty keyboard layout

**Comment by pitsi** [comment]
Just wanted to add that the "x" appears as usual when the english (uk or us) layout is selected, so I will stick to that for now.

**Comment by rkkr** [comment]
Layout cache got misaligned. Should be fixed in https://github.com/rkkr/simple-keyboard/commit/53cba0a2f1a736bf8c1d352848f041135c8a1b4a

**Comment by pitsi** [comment]
Thank you for the quick response, the fix and the instant release of a new version at the play store :)
