### ISSUE TITLE
Still can't emulate GBoard Bordered layout because keys are not tall enough

### ISSUE THREAD

**Issue by Riotous** [rkkr/simple-keyboard#63]
Hi, I've been trying to emulate the look of GBoard's bordered key layout using Simple Keyboard and unfortunately, even your new Material Bordered layouts can't emulate it. The closest I've gotten is to change the keyboard height to 90% but the problem is that the keys themselves are not tall enough to achieve the look of GBoard Bordered.

Would it be possible to add a new setting called "Key Height" (as opposed to Keyboard Height) that only changes the height of the individual keys no matter how tall or short the entire keyboard is?

Or perhaps, more simply, add a 5th layout that perfectly matches the GBoard bordered layout at 100% keyboard height?

Here's what GBoard Bordered layout looks like at default settings. I think many people would love if you followed this exact layout. If you don't want to do this, just let me know and I'll close this issue. Hope you consider it. 

![47248944-f73ebc00-d3c2-11e8-9e2b-a5cf3c2e13a5](https://user-images.githubusercontent.com/42202207/47590798-497f6000-d922-11e8-8370-29ff71399268.png)

**Comment by rkkr** [comment]
I don't have an intention to make an exact copy of gboard. The new border themes were mostly made to have consistency with material themes.
