### ISSUE TITLE
Use current resolution rather than default resolution

### ISSUE THREAD

**Issue by josephg5** [rkkr/simple-keyboard#64]
I can only see the left side of simple-keyboard… the right side is outside the screen and can't be seen. Other keyboards like Hacker's Keyboard and Multiling O Keyboard look and work just fine.

Could it be because I changed resolution?
```
$ adb shell wm size
Physical size: 480x800
$ adb shell wm density
Physical density: 240
Override density: 200
```
Update: simple-keyboard seems to use device default density, rather than current density setting.

**Comment by rkkr** [comment]
Same as #89 but with less details.
