### ISSUE TITLE
FR: Add spell check

### ISSUE THREAD

**Issue by mimi89999** [rkkr/simple-keyboard#67]

**Comment by rkkr** [comment]
Takes too much space

**Comment by licaon-kter** [comment]
UI wise or code wise?

**Comment by rkkr** [comment]
Apk size wise.

**Comment by jwsp1** [comment]
As much as I like Simple Keyboard, but this is the number 1 thing that hinders me (and my friends) from using the app for daily usage. Making just too many typos that are not being fixed by a spell check functionality. With every update I hope that this has been added.
Other keyboards require you to download optional language packs for the languages you want spell check. This way, the app size is still acceptable. :)

**Comment by Wilker-a** [comment]
isn't the keyboard having nothing other than the keyboard itself, the point of this project?

a fork of the keyboard with the spellcheck (preferably not connecting to closed source outside services) would be a solution if that's still a problem...

**Comment by jwsp1** [comment]
Yes, that's true, it's called "simple keyboard", but for a lot of people, spell check became something normal nowadays. Most people got used to standard Android keyboard or SwiftKey, so they miss this not-existing functionality of simple keyboard a lot.

Maybe the dev can start a poll to get feedback if users like this kind of spell check. I would also pay for this functionality.

**Comment by rkkr** [comment]
Even if everyone will vote that they want a spell-checker, the default LatinIME implementation which includes the dictionaries for most common languages takes ~20MB. I will not increase the keyboard size 40x.

There is an alternate approach to use the spell checker provided by the android system. An overly simplified sample: https://code.tutsplus.com/tutorials/an-introduction-to-androids-spelling-checker-framework--cms-23754 . But as LatinIME wasn't built with that in mind, incorporating it will be a huge refactoring task. Even if you searched in GitHub for SpellCheckerSessionListener you won't find many usages. I haven't found any keyboard source that uses it.

If someone manages to implement it in <1MB and no Network permission, make a PR.

**Comment by jwsp1** [comment]
I do understand that some people have no space on their phones and want apps <1mb. Network permission is a no-go, indeed. 
So what about giving the possibility to download the spell check language pack as a separate app? The main keyboard app would stay ~1mb and is linked to language pack app which is ~20mb. 
So people who really want spell check can download this separate app for their specific language(s) and people who don't have enough space can keep using the 1mb main app.

AnySoft Keyboard (Fdroid) and Hackers Keyboard (Fdroid) are working this way, but your layout is 1000x better than theirs :)

**Comment by desmonk** [comment]
Any chance of having this feature?

As writing more and more lines have become very common in this day and age. Just suggesting here that a second app with such offline only features might do wonders

**Comment by foss-friendly** [comment]
An absolute must! No network permission is needed if a separate dictionary pack can be downloaded and installed. That way the app stays <1mb and this vital feature for heavy everyday usage gets added for those who need it. I still can't fully switch to this keyboard simply beacuse in my daily workflow I type in 4 languages and definitely the spellchecker saves my probably hundreds of typos...
BTW... thumbs-up for your decision to nuke GIF, Emoji, Swipe writing and etc. crapware...

**Comment by quyleanh** [comment]
Come here in 2021 and wait for spell checker. Others are no need.

**Comment by licaon-kter** [comment]
@quyleanh use OpenBoard then

**Comment by quyleanh** [comment]
@licaon-kter OpenBoard does not support Vietnamese. In other hand, its UI is not stock like Simple Keyboard.

**Comment by Justauser0** [comment]
Spell Checker in 2023

**Comment by Animesh3193** [comment]
Mm,

**Comment by CardealRusso** [comment]
this is a must have
