### ISSUE TITLE
An X is being randomly inserted as first character

### ISSUE THREAD

**Issue by Zero3K** [rkkr/simple-keyboard#7]
It will randomly replace the first character of a word I type with an X (such as Thanks becoming Xhanks) even though I didn't press the shift key followed by an x. I am using it on Android 5.1.

**Comment by rkkr** [comment]
Never reproduced this issue. Please provide more details if you want a fix.

**Comment by Zero3K** [comment]
Is there any way to debug it?

**Comment by rkkr** [comment]
The source is available. You can make a local debug build, attach debugger and then you can do anything.

**Comment by bySabi** [comment]
@rkkr Can you deep on this? ... I can not get it to work.

Thanks

**Comment by bySabi** [comment]
@rkkr sorry. I don't explain me very well, my fault.

I don't have any issue with `simple-keyboard` is just that I need extend it with overlays view for support "two cursors mouse arrows" and I was trying to figure out the code flow. 

I guess that setting the proper debug settings is the first step. 

You are completely right, I need Android development basics :-D. 
I know how debug a common App with default Activity, but I don't get it with `simple-keyboard`

**Comment by bySabi** [comment]
It seems I got it, run and "attach debugger" flow.

Thanks anyway
