### ISSUE TITLE
custom keyboard color not working

### ISSUE THREAD

**Issue by sqdesign** [rkkr/simple-keyboard#70]
![screenshot_20181107-191852](https://user-images.githubusercontent.com/33090628/48151638-12199780-e2c2-11e8-99f3-443b0fa30239.png)
![screenshot_20181107-190252](https://user-images.githubusercontent.com/33090628/48150856-1fce1d80-e2c0-11e8-9a67-37e8d7d03abd.png)
![screenshot_20181107-190305](https://user-images.githubusercontent.com/33090628/48150865-26f52b80-e2c0-11e8-9705-cb25114ef5b9.png)

Did I pressed OK Seriously? Can't change color on any theme.
Layout standard english.
(Android 7.1.2 oneplus3 resurrectionremix nougat build final)

**Comment by licaon-kter** [comment]
Works here, care to detail, what style? Layout? Did you press OK after messing with the colour sliders?

**Comment by rkkr** [comment]
Screenshot or it didn't happen.

**Comment by rkkr** [comment]
You have custom theming based on how all UI elements have black background. That is probably what overrides it.

**Comment by sqdesign** [comment]
No, not overridden...
