### ISSUE TITLE
Feature request: taller bottom row

### ISSUE THREAD

**Issue by baccyflap** [rkkr/simple-keyboard#73]
I've got a fairly large phone, and I keep hitting the v and c buttons rather than the space bar as the bottom bit of the screen is a bit of a reach. It would be great if there were an option to make the bottom row taller independent of the rest of the keyboard, or possibly to introduce whitespace under the keyboard à la iPhone X.

**Comment by licaon-kter** [comment]
Seeing/doing the same too...
