### ISSUE TITLE
utilise top row for specal characters when numbers are shown

### ISSUE THREAD

**Issue by jakejoh** [rkkr/simple-keyboard#74]
It would be very handy to have additional special characters shown on the "qwerty"-row when the number-row is permanently enabled.

**Comment by licaon-kter** [comment]
What type? Which ones?

**Comment by rkkr** [comment]
Number row is half size, so special characters won't fit in there. If it were made full size, then keyboard height is too small to fit them all. The special characters that are shown on keys should be enough.

**Comment by jakejoh** [comment]
I specifically mean the top letter row (qwertyuiop in English layout), not the number row. Sorry for the confusion.
Characters like [ and ] are quite useful (especially for markdown syntax).

An example for having this could be Gboard (but I think others have it as well).
![screenshot_nova_launcher_20181120-140610 2](https://user-images.githubusercontent.com/25611892/49603260-12718500-f98b-11e8-98bf-3493bf716b04.png)

**Comment by rkkr** [comment]
Ok, having different special characters in top character row is logical.

**Comment by Wilker-a** [comment]
i think it would be nice to also have the symbols at the number row equivalent to a regular physical keyboard even though they aren't shown by default (and maybe also add a visual option for the number rows to have the same height as the regular keys)

**Comment by bimlas** [comment]
Because  `.` contains the special characters, what do you think about let it customizable: for example I could select `[ `,`] `and bacthick characters to be available from `.`.

**Comment by jorgman1** [comment]
I agree that this could be useful. For example in European countries put an € as a special character at the "e".

**Comment by Wilker-a** [comment]
it would be nice if every key was customizable, from the secondary/special characters for each key, to even the primary keys and actions to then save the layouts on a file or gather from a template... i think it would help with implementing new layouts, too.
