### ISSUE TITLE
how to add a new language?

### ISSUE THREAD

**Issue by Translator5** [rkkr/simple-keyboard#75]
How to add a new language?
I've did the layout, strings and dictionary - but without replacing a existing language, i can not add a custom language.
How to make a custom language appear in the language-choosing list?

I'm doing it for personal and public use - so it should be not just a workaround method ...

**Comment by rkkr** [comment]
In method.xml

**Comment by Translator5** [comment]
Why could the app instantly crash on opening the keyboard?
I formally created a bit varied copy of east slavic script, but it crashes.
[GitLab](https://gitlab.com/Translator5/simple-keyboard/tree/master)

**Comment by rkkr** [comment]
"sla" is an invalid locale. You can find locales list here: https://www.oracle.com/technetwork/java/javase/java8locales-2095355.html . You also have duplicate `android:subtypeId="0x8e333b94"`. As language list is controlled by the OS and keyboard only provides layouts for it, you won't have an easy way to hack in two layouts for a single Slovenian language.
