### ISSUE TITLE
Feature request: Add emoji suport

### ISSUE THREAD

**Issue by lucaskedrines** [rkkr/simple-keyboard#77]
The only thing this amazing keyboard needs is emoji support

**Comment by 0pLuS0** [comment]
Emoji support and text correction would make this really great!

I could live without emjoi, but they do make it nice at times...

No spell checking, that is a complete no no, most people can't even spell! LOL

Oh well using AnySoftKeyboard at that bloated 6.4MB LOL...

**Comment by 0pLuS0** [comment]
Emoji support and text correction would make this really great!

I could live without emjoi, but they do make it nice at times...

Now Spell Checker, this is a Must Have!
