### ISSUE TITLE
Estonian keyboard layout buggy

### ISSUE THREAD

**Issue by ervinoro** [rkkr/simple-keyboard#78]
System language "Estonian (Estonia)" keyboard layout is simply nordic layout, which is not correct, it is missing the letter "õ". Default Gboard places the letter "õ" in Estonian layout as the last key in third row.

Custom input styles with Estonian language are regular English layouts and don't contain any of the special keys ("ü", "ö". "ä", "õ").

|   |  |
| ------------- | ------------- |
| "Expected" Estonian layout (Gboard) | ![screenshot_20190106-192935](https://user-images.githubusercontent.com/14315476/50739493-f7906b80-11e9-11e9-8a4c-734e6436d97a.png)  |
| Simple Keyboard "Estonian (Estonia)" | ![screenshot_20190106-184247](https://user-images.githubusercontent.com/14315476/50739492-f2cbb780-11e9-11e9-8bee-5e2e7f588548.png)  |
| Simple Keyboard custom input style "Estonian (Estonia) (QWERTY)" | ![screenshot_20190106-184354](https://user-images.githubusercontent.com/14315476/50739495-fa8b5c00-11e9-11e9-9130-b028f5de22cd.png)  |

**Comment by rkkr** [comment]
This is a fork of AOSP keyboard, not GBoard. õ is not shown in AOSP keyboard, so it's not shown here also. In AOSP keyboard you can find õ by long-pressing ö.
