### ISSUE TITLE
please add configurable gap below keyboard

### ISSUE THREAD

**Issue by goldalworming** [rkkr/simple-keyboard#8]
hi, could I suggest feature configureble space below space so the keyboard not too below

![image](https://user-images.githubusercontent.com/440256/34112405-09c9afb6-e43f-11e7-843f-927c99e2fc5b.png)
I don't like navigation bar but it very usefull when typing with keyboard because it add several pixel gap below space and easier to type.
so the feature could set how high the keyboard gap. just like iphone x keyboard gap, I think it's more natural

![image](https://user-images.githubusercontent.com/440256/34112565-8bc48e6e-e43f-11e7-8a29-011492470418.png)

**Comment by mdrv** [comment]
Is this feature actually implemented? I find it not comfortable to type on smartphones with almost lack of bottom bezel (which is what manufacturers are trying to achieve these days); the only way to make it less painful is to increase the height, but that’s not raising all keys (the third and last row is still positioned too low).

**Comment by mdrv** [comment]
@rkkr Here’s what I envisioned. The first image shows the keyboard at 75% height and the third one at 100% height. The issues with both of those are that the first one doesn’t put the keyboard in optimal position (too low) and the third one forces your fingers to move further compared to the first one. The second image (representing the mock-up/idea) retains the height of the first one while raising all the keys to the optimal position. This way, your fingers also won’t travel as much as the third one suggests.

<p>
<img src="https://user-images.githubusercontent.com/100693152/173991827-c34a5623-49cd-4a7e-870f-6abb7c35f547.png" width="30%" height="30%">
<img src="https://user-images.githubusercontent.com/100693152/173991833-b6a57d3a-318e-476d-8492-0354ddb173b7.png" width="30%" height="30%">
<img src="https://user-images.githubusercontent.com/100693152/173991836-98c67fdb-3cc3-4f3c-ba21-1cb45dd960bf.png" width="30%" height="30%">
</p>

**Comment by goldalworming** [comment]
maybe he don't want to implement it
