### ISSUE TITLE
Full-stop not working in landscape mode

### ISSUE THREAD

**Issue by JonnyTech** [rkkr/simple-keyboard#80]
Since upgrading to version 3.5 from F-droid, the bottom row full-stop (period) is not working in landscape orientation.

**Comment by licaon-kter** [comment]
Works for me.

What  device? Android version? Apps tested?

**Comment by JonnyTech** [comment]
Nokia 3 phone, Android 8.0, several apps (fennec browser, k9 email, unote notepad), keyboard at 90% and 100% height. Downgrading to older version works correctly.

**Comment by JonnyTech** [comment]
I shall try play store version later today.

Language is English UK. Theme is material dark.

No character is shown and keypad does not highlight.

**Comment by rkkr** [comment]
Try rotating your phone to the other side. It wouldn't be a first time of a faulty touch panel.

As for the button size, they take the whole space of the keyboard. Even if you set the boarder theme and click outside the button border, you'll still click a button. There is literally 0 pixels that aren't mapped to a key. Key width of 10% is defined in [row_qwerty4.xml](https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/xml/row_qwerty4.xml). Key height of 25% is defined in [themes-common.xml](https://github.com/rkkr/simple-keyboard/blob/master/app/src/main/res/values/themes-common.xml).

There have also been no changes to the layout logic for a long time. What changed recently is click animation is removed (not likely to break a single key) and space/backspace swipe is added ("." is next to the space key). If your panel registers a click on space key before "." is being clicked, then this will count as a cursor move. You can try to disable swipe functionality.

And as my bet is on a faulty touch panel, you should enable "Show taps" in developer settings and confirm that clicks are registered properly by the OS in the first place.

**Comment by JonnyTech** [comment]
> Try rotating your phone to the other side. It wouldn't be a first time of a faulty touch panel.

Yikes, I have a faulty panel! Thanks for your time. Sorry for the noise.
