### ISSUE TITLE
Gestures [feature request]

### ISSUE THREAD

**Issue by machiav3lli** [rkkr/simple-keyboard#81]
It would be great if you can add to the moving the cursor gesture (with wiping over the space bar), the ability to select the elements through the same gesture but then on the higher part of the keyboard(something like chrooma's implementation of the gesture).
Other gesture that would be great to implement is "wipe down to hide keyboard".
Thanks for your work.

**Comment by licaon-kter** [comment]
You already have "swipe over spacebar to move cursor"

**Comment by machiav3lli** [comment]
@licaon-kter yeah, but they could be combined in an intuitive way, as I said, something like chrooma's implementation.

**Comment by rkkr** [comment]
Will not include gestures over letter keys.
