### ISSUE TITLE
Feature request: Change keyboard layout for Ukraine

### ISSUE THREAD

**Issue by TestUser013** [rkkr/simple-keyboard#82]
Hello Raimondas Rimkus,
In Ukraine we have standard layout keyboard with the `Ї` letter near the `х` letter. Here is  example https://keyshorts.com/products/ukrainian-bilingual-keyboard-sticker
https://i.imgur.com/Lzr5mzj.png

At the moment, in Simple Keyboard Ukrainian layout we can enter the `Ї` letter with long press the `і` letter  and shift from the `#` character. Is there any  possibility to change keyboard layout our language for Ukrainian language and move the `Ї` letter from the `і` letter to the `х` letter?

**Comment by rkkr** [comment]
Will not change language specific layouts. You can make PR if you want to.

**Comment by TestUser013** [comment]
Hello @rkkr ,
Thank you. Could you please advice what is "PR"and are there any guide about layout customizing?

**Comment by licaon-kter** [comment]
@TestUser013 PR is Pull Request, as you fix the layout yourself and then ask for those to be merged here.
