### ISSUE TITLE
[Request] Key borders and Turkish Q

### ISSUE THREAD

**Issue by cbatub** [rkkr/simple-keyboard#84]
Hello, is it possible for you to add key borders just like in gboard as an option to be toggled? Also i would like to use turkish q layout with special turkish characters are on layout? Just like in screenshot. Keep up the good work man, thank you for saving us from feeding the data hoarders.

![screenshot_20190211-182445_gboard](https://user-images.githubusercontent.com/23391494/52581197-6c2e7980-2e2a-11e9-97fe-a68ba87637ba.png)

**Comment by rkkr** [comment]
Select "Material Light Border" theme

**Comment by cbatub** [comment]
So no chance for Turkish Q?
