### ISSUE TITLE
Simple Keyboard Doesn't Show With OnePlus Facelock

### ISSUE THREAD

**Issue by 0pLuS0** [rkkr/simple-keyboard#85]
Hello,

OxygenOS 5.1.7 - Oreo 8.1.0, I converted the ROM into a microG rom, and replaced the google keyboard with simple keyboard.

I was testing the OnePlus Facelock and rebooted the phone, when I came back to the screen I was presented with a password screen, maybe you are familar with the OP Facelock, you set it up also with a pin, pattern or password. Since I was at the password screen to type in the pass, Simple Keyboard would not appear.

I rebooted into TWRP removed Simple Keyboard and pushed LineageOS' AOSP keyboard LatinIME to /system/app, then I rebooted and the AOSP keyboard worked at the password screen.

OxygenOS is a Google ROM, but I assumed any keyboard is going to work with all functions on the phone, and since OxygenOS is a google ROM, I assumed that maybe the AOSP keyboard might of had issues too, but it didn't.

Hopefully this is something you can look into without a logcat? I really want to have Simple Keyboard installed as the only keyboard on the ROM, but now because of this issue I've disabled Face Lock, which doesn't seem like a great way to resolve this issue.

I just don't get why AOSP keyboard would work and Simple Keyboard wouldn't... hmm

Thanks

**Comment by licaon-kter** [comment]
This is expected, saw it on many devices, for lockscreen or bootup it will use the system keyboard, so keep that installed, but toggled off in settings-input.

Not sure if making SimpleKeyboard a system app helps though.

/close as invalid?

**Comment by 0pLuS0** [comment]
Well I'm trying to make a ROM with just simple keyboard only. Also SimpleKeyboard is a system app in the ROM.

I took at logcat this time and the login screen maybe it will help to solve/fix this, I really only want SimpleKeyboard.... wahhhhhh LOL

[logcat.txt](https://github.com/rkkr/simple-keyboard/files/2863903/logcat.txt)

Thanks

**Comment by 0pLuS0** [comment]
Well I'm trying to make a ROM with just simple keyboard only. Also SimpleKeyboard is a system app in the ROM.

I took a logcat this time at the login screen maybe it will help to solve/fix this, I really only want SimpleKeyboard.... wahhhhhh LOL

This is a microG ROM, so forget me using Gboard and I don't want the AOSP keyboard it's bloat and the Mic for the voice to text doesn't work either, and I just really don't want it...

[logcat.txt](https://github.com/rkkr/simple-keyboard/files/2863903/logcat.txt)

Thanks

**Comment by 0pLuS0** [comment]
Well I'm trying to make a ROM with just simple keyboard only. 

SimpleKeyboard is a system app in the ROM, so this is my System Keyboard... hmm

I built the ROM in SuperR's Kitchen and put it in; /system/app/SimpleKeyboard

I took a logcat this time at the login screen maybe it will help to solve/fix this, I really only want SimpleKeyboard.... wahhhhhh LOL

This is a microG ROM, so forget me using Gboard and I don't want the AOSP keyboard it's bloat and the Mic for the voice to text doesn't work either, and I just really don't want it...

[logcat.txt](https://github.com/rkkr/simple-keyboard/files/2863903/logcat.txt)

Thanks

**Comment by 0pLuS0** [comment]
Well I'm trying to make a ROM with just SimpleKeyboard only. 

SimpleKeyboard is a system app in the ROM, so this is my System Keyboard... hmm

I built the ROM in SuperR's Kitchen and put it in; /system/app/SimpleKeyboard

Gboard and ASOP are in;

/system/app/LatinImeGoogle
/system/app/LatinIme
/Well I'm trying to make a ROM with just simple keyboard only. 

I took a logcat this time at the login screen maybe it will help to solve/fix this, I really only want SimpleKeyboard.... wahhhhhh LOL

This is a microG ROM, so forget me using Gboard and I don't want the AOSP keyboard it's bloat and the Mic for the voice to text doesn't work either, and I just really don't want it...

[logcat.txt](https://github.com/rkkr/simple-keyboard/files/2863903/logcat.txt)

Thanks

**Comment by 0pLuS0** [comment]
Well I'm trying to make a ROM with just SimpleKeyboard only. 

SimpleKeyboard is a system app in the ROM, so this is my System Keyboard... hmm

I built the ROM in SuperR's Kitchen and put it in; /system/app/SimpleKeyboard

Gboard and ASOP are in;

/system/app/LatinImeGoogle
/system/app/LatinIme

Well I'm trying to make a ROM with just simple keyboard only. 

I took a logcat this time at the login screen maybe it will help to solve/fix this, I really only want SimpleKeyboard.... wahhhhhh LOL

This is a microG ROM, so forget me using Gboard and I don't want the AOSP keyboard it's bloat and the Mic for the voice to text doesn't work either, and I just really don't want it...

[logcat.txt](https://github.com/rkkr/simple-keyboard/files/2863903/logcat.txt)

Thanks

**Comment by 0pLuS0** [comment]
Well I'm trying to make a ROM with just SimpleKeyboard only. 

SimpleKeyboard is a system app in the ROM, so this is my System Keyboard... hmm

I built the ROM in SuperR's Kitchen and put it in; /system/app/SimpleKeyboard

Gboard and ASOP are in;

/system/app/LatinImeGoogle
/system/app/LatinIme

I took a logcat this time at the login screen maybe it will help to solve/fix this, I really only want SimpleKeyboard.... wahhhhhh LOL

This is a microG ROM, so forget me using Gboard and I don't want the AOSP keyboard it's bloat and the Mic for the voice to text doesn't work either, and I just really don't want it...

[logcat.txt](https://github.com/rkkr/simple-keyboard/files/2863903/logcat.txt)

Thanks

**Comment by rkkr** [comment]
That's the log where it fails:
```
02-13 22:08:52.099  1194  1194 W InputMethodUtils: Found no fallback locale. imis=[]
02-13 22:08:52.099  1194  1194 W InputMethodUtils: No software keyboard is found. imis=[] systemLocale=en_US fallbackLocale=null
02-13 22:08:52.099  1194  1194 W InputMethodManagerService: Default IME is uninstalled. Choose new default IME.
02-13 22:08:52.099  1194  1194 W InputMethodUtils: Found no fallback locale. imis=[]
02-13 22:08:52.099  1194  1194 W InputMethodUtils: No software keyboard is found. imis=[] systemLocale=en_US fallbackLocale=null
02-13 22:08:52.099  1194  1194 I InputMethodManagerService: No default found
02-13 22:08:52.100  1194  1194 W InputMethodManagerService: Unknown input method from prefs: rkr.simplekeyboard.inputmethod/.latin.LatinIME
02-13 22:08:52.100  1194  1194 W InputMethodManagerService: java.lang.IllegalArgumentException: Unknown id: rkr.simplekeyboard.inputmethod/.latin.LatinIME
02-13 22:08:52.100  1194  1194 W InputMethodManagerService: 	at com.android.server.InputMethodManagerService.setInputMethodLocked(InputMethodManagerService.java:2433)
02-13 22:08:52.100  1194  1194 W InputMethodManagerService: 	at com.android.server.InputMethodManagerService.updateInputMethodsFromSettingsLocked(InputMethodManagerService.java:2380)
```

And link to OS code: https://android.googlesource.com/platform/frameworks/base/+/0e2d281/services/java/com/android/server/InputMethodManagerService.java .

It is really strange how it fails. It has a settings value that an input method is enabled, but it fails to find it.  
@0pLuS0 - encryption is disabled I assume?
I have tested simple keyboard with GBoard installed, disabled and system encrypted. SimpleKeyboard installed as user application. What happened was GBoard was shown at boot to enter the password (expected), then the phone boots in unlocked state. It then properly shows SimpleKeyboard for the password input when phone is locked.

SimpleKeyboard is a clone of AOSP keyboard. So either the way it is installed to the system is wrong (not likelly), or there is something screwed up in OxygenOS (likelly).
What is changed from AOSP is that I removed all the deprecated APIs. One is the `AsciiCapable` flag removal. Keyboard builder API is also updated. It might be that OS still depends on those deprecated APIs (some are deprecated since Android ~4).

**Comment by 0pLuS0** [comment]
@rkkr this is your typical ROM from a manufacture with Encryption on it, I have not removed it.

If I screwed something up, then I would of assumed the AOSP keyboard would not work either, so since AOSP works, not sure how I screwed this up...

When I get some time, I can install OxygenOS, boot it into TWRP and remove Gboard and then push Simple Keyboard to /system/app, restart, enable Face Lock and reboot and see if happens in OxygenOS and report back.

Thanks

**Comment by rkkr** [comment]
...as I told, it's not likelly you screwed it up.

**Comment by 0pLuS0** [comment]
> ...as I told, it's not likelly you screwed it up.

Hey I try.... LOL

**Comment by VolatileDream** [comment]
It looks like Simple Keyboard is lacking support for Direct Boot Mode, which would allow it to function before the first unlock. [Instructions for support.](https://developer.android.com/training/articles/direct-boot) It should be relatively simple to support, but the change may cause problems with upgrading users and handling configuration files.

You can see the configuration in the [AOSP manifest](https://android.googlesource.com/platform/packages/inputmethods/LatinIME/+/refs/heads/master/java/AndroidManifest.xml#61).

**Comment by rkkr** [comment]
I tried it already here: https://github.com/rkkr/simple-keyboard/tree/secure_boot_support

The catch is that global direct boot flag only works for system apps. Installed apps need to switch contexts programatically and there are too many places where this swirch would need to be added. The code in linked branch force closes.

**Comment by rkkr** [comment]
This seems to work: daae07b1a0a545ad8a1b918166b7302a449a2185 . Will push after more testing on my own device.
