### ISSUE TITLE
Turkish Q layout?

### ISSUE THREAD

**Issue by cbatub** [rkkr/simple-keyboard#86]
![52581197-6c2e7980-2e2a-11e9-97fe-a68ba87637ba](https://user-images.githubusercontent.com/23391494/53035194-2a7a8000-3475-11e9-9a1c-7bfa01780471.png)
Hello, is it possible for you to add turkish q layout with special turkish characters? Just like in screenshot. Keep up the good work man, thank you for saving us from feeding the data hoarders.

**Comment by rkkr** [comment]
Turkish layout is available with with the special g,u and s letters in the long-press menu. I'm not planning to change language specific layouts.
