### ISSUE TITLE
Swipe delete should be reversible

### ISSUE THREAD

**Issue by ChristianKurz** [rkkr/simple-keyboard#87]
While swipe deleting, its easy to delete too many symbols. It would be nice to be able to swipe backwards, and have the deleted symbols reappear.
The delete buffer could be discarded once the finger is lifted.

Edit: Perhaps it would be easier and more userfriendly to select the characters while swipe deleting. The selected text would then be deleted on finger release.

**Comment by Archeix7** [comment]
It would be a very nice feature.
