### ISSUE TITLE
[Request] Please add your app in this list of good opensource android apps

### ISSUE THREAD

**Issue by pitsi** [rkkr/simple-keyboard#88]
Hello.
A couple of days ago, I was searching for a simple calendar app and I came accross this list here.
https://github.com/CHEF-KOCH/Android-Privacy-Data-Protection-Tools-Mega-Thread#keyboard

I think your app deserves to be in there. I would have made a request at that github repo and ask it's maintainer to include it, but I can not open an issue there, thus I thought you could ask for a pull request.

Thank you :)

**Comment by Pablohn26** [comment]
[Done](https://github.com/CHEF-KOCH/Android-Privacy-Data-Protection-Tools-Mega-Thread/pull/3) (waiting for merge)
