### ISSUE TITLE
Move arrow keys to navigation bar

### ISSUE THREAD

**Issue by fizzwhiz** [rkkr/simple-keyboard#9]
If it's possible, move the arrow keys to the navigation bar as in CyanogenMod.

**Comment by fizzwhiz** [comment]
Also, use chevrons instead of arrows.

**Comment by rkkr** [comment]
There is already an app for that (I used it myself): https://forum.xda-developers.com/android/apps-games/app-custom-navigation-bar-customize-t3590967 . But it only works on some of Android 7+ devices and requires ADB configuration. Not what I would like include. The CyanogenMod keyboard is built into the system, so it's not what could be done by an external application.

Arrows can be changes.
