### ISSUE TITLE
Swipe typing

### ISSUE THREAD

**Issue by dineshdb** [rkkr/simple-keyboard#90]
We, a team of college students, are trying to implement swipe typing for the Nepali language as our final year major project. This project seems to be a good base for our project. We want to add support for swipe/gestures. Can you please provide some guidelines to where to start so that we can narrow down our search. Specifically, how can we add gesture detection over swiped letters?

We are pretty good at programming and have a basic understanding of Android Programming. Thank you.

Found #21 but the issue does not contain any info on how to get started.

**Comment by rkkr** [comment]
Swipe support is built into AOSP keyboard: https://android.googlesource.com/platform/packages/inputmethods/LatinIME/ . I have removed it to reduce the keyboard size as swipe requires dictionaries to register the correct letters. You can just fork AOSP and add Nepali dictionaries and swipe should just work. AOSP should be a better base.

Unless you really want to implement all this logic yourself, which will be a huge task. You are free to fork if you want to. Apache license allows you to do what ever you want with this.

**Comment by dineshdb** [comment]
Thanks. We will look into AOSP. I like what you are doing here.
