### ISSUE TITLE
Feature Request: Add ability to customize the color of the RETURN key

### ISSUE THREAD

**Issue by mananapr** [rkkr/simple-keyboard#92]
It would be great if we could also change the color of the ENTER/RETURN/SEND key apart from the background color of the keyboard.

I use a substartum theme and the pastel green color sticks out like a sore thumb.

**Comment by Wilker-a** [comment]
aditionally, i would like it if we made it so we can choose a custom palette (in rgb and hsv) for every aspect of the keyboard, from the background to the characters, to the background and transparency of the keys (and treating the enter key differently from the shift&backspace keys), and then save and maybe share or import the palette in plain text

**Comment by rkkr** [comment]
It is not likely to happen as these elements are drawn from static files to allow hardware acceleration. I have once tried to set a custom colour at runtime (available in an old version), but this doesn't render in Samsung phones.

If someone manages to implement this, make a PR.

**Comment by mananapr** [comment]
That's sad to hear
>I have once tried to set a custom colour at runtime (available in an old version)

Can you tell me what version is this and if it is available on f-droid?
Anyway, thanks for the great keyboard

**Comment by rkkr** [comment]
It was added in commit 52e01fd0b1aa22c8e61ec7c02beae2d277d61435 and reverted in the next one. The only version that had it was 1.7 and it's a very old one before it was even added to F-Droid.

**Comment by rkkr** [comment]
Closing as no color is used now
