### ISSUE TITLE
Question about translating Simple Keyboard

### ISSUE THREAD

**Issue by FTno** [rkkr/simple-keyboard#96]
I just made some translations at Crowdin for Simple Keyboard, but to my surprise only the last 7 strings in the language file were present at the Crowdin translation page. 
All the other strings in the language file here at GitHub are already translated, but there are some not so good translations so I wanted to improve those.

Why is not the complete language file at Crowdin so earlier translations can be improved/corrected?

**Comment by licaon-kter** [comment]
Did you select "show all" or only "untranslated"?

**Comment by FTno** [comment]
Checked it now and 'All, Untranslated First (Default)' was the setting ('Show all' was the same as no string is currently untranslated).

**Comment by licaon-kter** [comment]
Right, the rest are IIRC from AOSP directly.

@FTno Which language? Which strings do you want?

**Comment by FTno** [comment]
I expected that the content of the language files (strings.xml) here at GitHub in this folder 'simple-keyboard/app/src/main/res', would be at Crowdin.

I wanted to improve about 6-7 strings especially these 3:
```
 <string name="popup_on_keypress">Popup on keypress</string>
 <string name="settings_screen_appearance">Appearance &amp; Layouts</string>
 <string name="custom_input_styles_title">Custom input styles</string>
```


My translation is to norwegian (nb).

**Comment by rkkr** [comment]
There are multiple reasons why original AOSP strings are not available in Crowdin.

1. The import of current resources doesn't work as multiple language formats are used (-xx and -xx-rXX). Crowdin only allows one format per project.
2. Some strings have special attributes (`xliff:g`), which can't be supported by Crowdin. They get corrupted on import/export.
3. Translated texts need to be below fixed length. If you "improve" the text by making it more descriptive (and longer), it may not render properly in some screen. I don't have resources to test all that. I also don't have resources to proof-read what you translated, maybe what you suggest is worst than the current one.

For all these reasons, only the new texts are available in Cwording. I copy them manually to git when changes are made. If you really want to change existing texts, you can change them directly in source and make a PR. The only requirement is that they can't be longer than the English/current version.

**Comment by FTno** [comment]
Thanks for the answer to my question.
