### ISSUE TITLE
Suggest new features, namely Word Suggestions, and one-handed keyboard on the Simple Keyboard V3.6 application

### ISSUE THREAD

**Issue by ammarraisafti** [rkkr/simple-keyboard#97]
# Introduction
Simple Keyboard is an open source application designed to be simple and efficient. Made for those who need a keyboard and no more. This application has a very small file size, so its performance is better when used together, this application runs well on almost all android devices.

**Repository**
https://github.com/rkkr/simple-keyboard

# Components
The components (Features) I want to suggest is:
- Word Suggestions
- One-handed keyboard

# Proposal description
Overall, this application has a good function. You can type easily and quickly using this application. Regardless of how easy this application is used, the user experience is also quite fun. However, so that this application is more interesting to use and increase in number of users, I want to suggest two new features to developers. I hope this suggestion becomes an additional idea to developers, and I hope developers can implement the features I recommend.

To make this application a favorite for users, all you have to think about is the user experience and a very good impression. To improve user experience, developers should provide unique features that are useful to users. To find out what users want, user feedback is needed. This is so that development is carried out in connection with what the application user wants.

**1. Word Suggestions**
The first feature I recommend is a very important feature in my opinion. I recommend this feature because I want to get new sensations, and ease when typing using this application. That is to get word suggestions when typing. This will certainly be very interesting for users.

_The following is a choice of word suggestions to be provided._
1. want the typos to be corrected automatically. 
2. want the letters to be changed to capital letters and given an accent. 
3. Never want any words or letters to be changed. 
4. do not need help when writing, even if it is advice.

So I think, the developer must consider my first suggestion. The "Word Suggestion" feature is very useful for users who want to get word suggestions when typing. If the Simple Keyboard application can add features that I recommend, this will certainly improve application users. Because it can provide convenience for users when typing. We recommend that the developer add this feature in the application settings section.

**2. One-handed keyboard**
One-handed keyboard is a very cool feature to add, because this feature will provide a very interesting sensation and provide convenience when typing. 

Operating a keyboard using one hand is a very pleasant thing, and worth trying. The choice of moving the keyboard to the left and right side must be provided, also the option to use it back to full display mode.

The developer should add this feature in the application settings section, and place it in preference options. And give users access to activate it.

# Mockups / Examples
Below I will show examples of locations or illustrations if the features I recommend are implemented by the Developer.

**1. Word Suggestions**
![images (1)-picsay.jpeg](https://cdn.steemitimages.com/DQmVhyMUWPcJ7KNFW4fxEJSv9XNUMWu9JJA5AgWjN3hJ2UQ/images%20(1)-picsay.jpeg)

**2. One-handed keyboard**
![images (1)-picsay.jpeg](https://cdn.steemitimages.com/DQmUjD9thmDdiiXHLrqzYET29tB8JfVqjeiKgTh1qpHUK64/images%20(1)-picsay.jpeg)

![images (1)-picsay.jpeg](https://cdn.steemitimages.com/DQmXqjUzwTBndpsTpw82nRcTc395jcRwdd6U6DMMh33XKLP/images%20(1)-picsay.jpeg)

# Benefit
**1. Word Suggestions**
After the developer adds the Word Suggestion feature, users will get word suggestions when typing using this application. And it is very useful for users, as well as a big advantage for them. 

**2. One-handed keyboard**
After the developer added the One Hand keyboard feature, a big effect will have an impact on the application. This application will look more cool and interesting to use. Users can operate the keyboard using one hand, they can use the left hand or right hand. Users can move the keyboard to the left side, or to the right side. And can switch to full view mode easily and quickly. Users will be spoiled when typing and will get extraordinary new experiences when operating the keyboard. The presence of this feature will provide convenience for users. And that is a big advantage.

# Conclusion
The two features that I recommend are very important to add, and will have a huge effect on the development of applications in the future. Because, In addition to offering a look of material design, other interesting choices are also available in it, such as the choice of using word suggestions, and using the keyboard using one hand mode. Users of this application will feel very happy with the presence of two new features in it. They will invite other users to use this application, and give the best rating for this application. That is a big advantage for users and application developersAfter the developer added the One Hand keyboard feature, a big effect will have an impact on the application. This application will look more cool and interesting to use. Users can operate the keyboard using one hand, they can use the left hand or right hand. Users can move the keyboard to the left side, or to the right side. And can switch to full view mode easily and quickly. Users will be spoiled when typing and will get extraordinary new experiences when operating the keyboard. The presence of this feature will provide convenience for users. And that is a big advantage.

**Comment by licaon-kter** [comment]
Did you read #22 yet?

**Comment by rkkr** [comment]
Wow you really did put an effort to describe it. The dictionaries won't be added as they take too much space or require a network permission. You are free to implement the one handed made and make a pull request if you want to.
